### ISSUE TITLE
ENV file write right on OSX

### ISSUE THREAD

**Issue by robindata-gmbh** [visualfc/liteide#1000]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
35.2

### What version of Go are you using (`go version`)?
11.2

### What operating system and processor architecture are you using(`go env`)?
OSX

How I can set the write-rights on the env_files? I can't save my changes!

**Comment by visualfc** [comment]
move liteide to $HOME
