### ISSUE TITLE
为什么用了那么多版本，跳转声明经常无法使用？

### ISSUE THREAD

**Issue by zhuwei** [visualfc/liteide#1001]
难道是我用的不对？跳转第三方包也不行。用的很难受啊

**Comment by visualfc** [comment]
什么系统？哪个版本？可以提供一下 liteide 事件记录。
另外 liteide 不要放到有空格的目录中。

**Comment by visualfc** [comment]
可以手动更新 go tools&gocode 试一下。
go get -u github.com/visualfc/gotools
go get -u github.com/visualfc/gocode

将编译好的 gotools 和  gocode 复制到 /usr/bin 中。

**Comment by Lofanmi** [comment]
> 可以手动更新 gotools&gocode 试一下。
> go get -u github.com/visualfc/gotools
> go get -u github.com/visualfc/gocode
> 
> 将编译好的 gotools 和 gocode 复制到 /usr/bin 中。

感谢作者！

更新gotools和gocode到最新版本，问题已解决。特别是gocode，必须使用官方版本，不能使用nsf版本，这个是之前vscode下载下来的。

**Comment by visualfc** [comment]
please download x35.3 and check.

**Comment by yurenchen000** [comment]
弱问, 函数列表 在哪里, 怎么显示出来
