### ISSUE TITLE
Error and crash while still running, when clicking Stop Action in middle process

### ISSUE THREAD

**Issue by radiaku** [visualfc/liteide#1006]
Hello, in the middle executing program ( long running thread ), when I click  `Stop Action` button . Its always crash. ( I must kill it from task manager )
Tried to make simple program to execute loop and sleep and its still crash when I clicked `Stop Action` button.

Checking in taskmanager, its still running until program finished. Any help or fix for this?

this is simple loop code .
![screenshot_5](https://user-images.githubusercontent.com/5983350/48789380-79523580-ed1f-11e8-8fc9-95d97e84dbb9.png)

The process is still running

![screenshot_4](https://user-images.githubusercontent.com/5983350/48789289-4740d380-ed1f-11e8-95d8-3a20c233a3a2.png)

My simple code
```

func main() {

	sum := 0
	for i := 0; i < 1000; i++ {
		sum += i
		fmt.Println(sum)
		time.Sleep(2 * time.Second)
	}

}
```

Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X35.2 qt 4.8.5 (32)

### What version of Go are you using (`go version`)?
go version go1.11 windows/386

### What operating system and processor architecture are you using(`go env`)?
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\Root\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Root\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=sse2
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Root\AppData\Local\Temp\go-build998865738=/tmp/go-build -gno-record-gcc-switches

### What did you do?
Running and stopping

If possible, provide a recipe for reproducing the error.

### What did you expect to see?
stopping the program

### What did you see instead?
program still running.

**Comment by visualfc** [comment]
please use BuildAndRun action
