### ISSUE TITLE
liteide可以有插件机制吗？ 支持别的语言？

### ISSUE THREAD

**Issue by 756445638** [visualfc/liteide#1011]

**Comment by visualfc** [comment]
使用 Qt 编写插件
https://github.com/visualfc/liteide/tree/master/liteidex/src/plugins

**Comment by itfanr** [comment]
请问如何调用插件的？能有个文档吗？谢谢

**Comment by visualfc** [comment]
目前没有开发文档，编辑器扩展可以参考 plugins/markdown 插件。

**Comment by itfanr** [comment]
@visualfc  好的。我仔细读一下代码吧。谢谢
