### ISSUE TITLE
autocomplete dose not support global vars

### ISSUE THREAD

**Issue by jubaobleach** [visualfc/liteide#1014]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
35.2 QT5 MAC Version

### What version of Go are you using (`go version`)?

go version go1.11.1 darwin/amd64

### What operating system and processor architecture are you using(`go env`)?
MACOS Mojave 0.14.2 (18C54)

### What did you do?
simple code here
package main

import (
	"flag"
	"fmt"
	"net"
)

type server_cfg struct {
	LocalIP      string
	LocalPort    int
	CheckPayload int
}

var (
	g_cfg_info server_cfg
)

func main() {

	g_cfg_info. // auto complete not work
}
If possible, provide a recipe for reproducing the error.

![image](https://user-images.githubusercontent.com/58602/50329448-58554e00-0532-11e9-82d1-3a64cc1d6655.png)

### What did you expect to see?
auto complete work

### What did you see instead?
not auto complete vars

**Comment by visualfc** [comment]
please download x35.3 and check.

**Comment by jubaobleach** [comment]
thank U & Good Job ！
