### ISSUE TITLE
x35.3 appimage can't execute

### ISSUE THREAD

**Issue by alex-left** [visualfc/liteide#1015]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?

x35.3
### What version of Go are you using (`go version`)?
not relevant

### What operating system and processor architecture are you using(`go env`)?
not relevant

### What did you do?
donwload the appimage from github and try to execute

### What did you expect to see?
The programs runs without error

### What did you see instead?

```# ./liteidex.AppImage
bash: ./liteidex.AppImage: cannot execute binary file: Exec format error
# file liteidex.AppImage
liteidex.AppImage: data
```

**Comment by visualfc** [comment]
fixed, please download lieidex35.3.linux64-qt5.5.1.AppImage from https://sourceforge.net/projects/liteide/files/x35.3/
https://sourceforge.net/projects/liteide/files/x35.3/liteidex35.3.linux64-qt5.5.1.AppImage/download

**Comment by visualfc** [comment]
https://github.com/visualfc/liteide/releases/download/x35.3/liteidex35.3.linux64-qt4.8.7.AppImage upload
