### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [visualfc/liteide#1018]
i've downloaded Version '35.3' but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all. i guess the **CFBundleVersion** and **CFBundleShortVersionString** entries in your **Info.plist** file are missing.
all apps on macOS are supposed to contain valid version information.

**Comment by core-code** [comment]
awesome, thanks ;)

**Comment by core-code** [comment]
well, thanks for working on it, but i've just downloaded version '35.4' to confirm the fix and ... while the version numbers are now properly there, they are outdated.

when selecting version "35.4" in the Finder, it claims to be version "35.3"

**Comment by visualfc** [comment]
thanks, forgotten update plist.

**Comment by core-code** [comment]
i can confirm everything is OK in 35.5
