### ISSUE TITLE
Back jump works incorrect after Jump to Declaration

### ISSUE THREAD

**Issue by asavchuk** [visualfc/liteide#1021]
Back jump works incorrect after `Jump to Declaration`.

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X35.3, Qt 5.9.5 (32bit)

### What version of Go are you using (`go version`)?
go version go1.11.4 windows/amd64

### What operating system and processor architecture are you using(`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\User\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\go-work
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessag
e-length=0 -fdebug-prefix-map=C:\Users\User\AppData\Local\Temp\go-build208209626
=/tmp/go-build -gno-record-gcc-switches

### What did you do?
Set curson on GetCount() function:
fmt.Println(cr.GetCount())
and press Ctr+Shift+J to jump to declaration
then press Alt+LeftArrow
and it jumps on different line of code (not in the same place)

### What did you expect to see?
Expecting that it will jump back (after Alt+LeftArrow) to the same line of code.

### What did you see instead?
It jumps on different line of code (not in the same place).

**Comment by visualfc** [comment]
fixed in LiteIDE X35.4
