### ISSUE TITLE
中文变量重命名出错

### ISSUE THREAD

**Issue by tomitomy** [visualfc/liteide#1024]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
在 LiteIDE x35.3 和 LiteIDE x35.4 中测试过，其它版本没试

### What version of Go are you using (`go version`)?
Golang 1.11

### What operating system and processor architecture are you using(`go env`)?
Linux Mint 19

### What did you do?

下面的代码，给其中名为“错”的变量重命名(Ctrl+Shift+F2)，结果出错，在“搜索结果”栏的高亮部分就可以看到错误的匹配结果：

```golang
package main

import "fmt"

type 整数 int

func (错 整数) 测试() {
	fmt.Println(错, 错, 错)
}

func 测试(文本 string) (错 int) {
	for 当前字符 := range 文本 {
		错 = 错*10 + int(当前字符) - '0'
	}
	return
}

func main() {}
```

**Comment by visualfc** [comment]
fixed

**Comment by visualfc** [comment]
please download x35.5
