### ISSUE TITLE
Home Brew cask update to version 35.4 leads to 404 (file not found).

### ISSUE THREAD

**Issue by Tricky1975** [visualfc/liteide#1026]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
35.4 (mac)

### What version of Go are you using (`go version`)?
1.11.5

### What operating system and processor architecture are you using(`go env`)?
Mac

### What did you do?
I've LiteIDE installed through a homebrew cask. When I type "brew cask upgrade" the upgrading of liteide throws this error:
~~~
==> Casks with `auto_updates` or `version :latest` will not be upgraded
==> Upgrading 1 outdated package:
liteide 35.3 -> 35.4
==> Satisfying dependencies
==> Downloading https://github.com/visualfc/liteide/releases/download/x35.4/liteidex35.4.macos-qt5.9.5.zip

curl: (22) The requested URL returned error: 404 Not Found
==> Purging files for version 35.4 of Cask liteide
Error: Download failed on Cask 'liteide' with message: Download failed: https://github.com/visualfc/liteide/releases/download/x35.4/liteidex35.4.macos-qt5.9.5.zip
~~~

I guess this should indicate the ruby script used by HomeBrew has not been properly linked to the correct download link, since the file to be downloaded has simply not been found.

If possible, provide a recipe for reproducing the error.

### What did you expect to see?
The new version being succesfully upgraded

### What did you see instead?
The error I showed above.

**Comment by visualfc** [comment]
please download x35.5
