### ISSUE TITLE
How to remove the error: "redeclared in this block previous declaration at"?

### ISSUE THREAD

**Issue by Spiker01** [visualfc/liteide#1030]
Hello. I am a beginner goLang programmer. This is my hobby.

I recently started using LiteIDE, before that I used Geany. I decided to try another IDE. I like it.
 
My system:

> Linux SpSystem 4.10.0-38-generic # 42 ~ 16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU / Linux

> go version
> go version go1.11.1 linux/amd64

I installed the program as follows:
I copied the program files to the home folder
 

> / user01 / home and run it through the file / home / user01 / liteide / bin / liteide.

 
Next, I created a "shortcut" on the desktop with a link to this file.

 The program that I create was compiled normally, but then I saved it in the same folder, but gave a new name to the file. The program has stopped building. It displays an error:

> /usr/lib/go-1.11/bin/go build [/ home / user01 / Programming / GoLang / Parser04]
>   / home / user01 / Programming / GoLang / Parser04
> ./ParserTest03.go:29or: TextFindVar01 redeclared in this block
> previous declaration at ./ParserTest02.go:29imin
> ./ParserTest03.go:30PER: TextFindVar02 redeclared in this block
> previous declaration at ./ParserTest02.go:30imin
> ./ParserTest03.go:32 Lower: TextFindVar01File01 redeclared in this block
> previous declaration at ./ParserTest02.go:32imin
> ./ParserTest03.go:34; a: FindPositionVar01 redeclared in this block
> previous declaration at ./ParserTest02.go:34
> ./ParserTest03.go.33: ResultVar redeclared in this block
> previous declaration at ./ParserTest02.go:35imin
> ./ParserTest03.go:37 (a): UrlVar redeclared in this block
> previous declaration at ./ParserTest02.go:37imin
> ./ParserTest03.go:38II: UrlVar02 redeclared in this block
> previous declaration at ./ParserTest02.go:38imin
> ./ParserTest03.go:40PER: ViborVar01 redeclared in this block
> previous declaration at ./ParserTest02.go40.
> ./ParserTest03.go:41bre: ViborVar02 redeclared in this block
> previous declaration at ./ParserTest02.go:41 ln
> ./ParserTest03.go:44:6: fSlovoReturn redeclared in this block
> previous declaration at ./ParserTest02.go:44:40
> ./ParserTest03.go:44:6: too many errors
> Error: process terminated with code 2.

I tried to open this file in Geany and compile and run it. Everything is working. But in LiteIDE it gives an error (Error above). At the same time, a new file appeared in the folder (build through Geany) and it is launched via LiteIDE.

As I understand it, the environment somehow clings to variables from the old file, with the old name. How do I do so that the file would be built, compiled fine in LiteIDE.

I read it https://github.com/lucasb-eyer/go-colorful/issues/5
,but did not understand how to solve the problem.

How can I build packages through the program interface?

Thank you for watching.

**Comment by visualfc** [comment]
LiteIDE - Build - FileRunt
this action call execute "go run abc.go"

**Comment by Spiker01** [comment]
@visualfc Thanks.
