### ISSUE TITLE
X36版在go module模式下显示导入模块内容太简略

### ISSUE THREAD

**Issue by rocket049** [visualfc/liteide#1047]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X36

### What version of Go are you using (`go version`)?
go1.12.1

### What operating system and processor architecture are you using(`go env`)?
linux amd64

### What did you do?

在go module模式下，右键点击导入的模块，点击“查看import文档”

### What did you expect to see?
显示详细文档，即  `go doc -all path/to/module`  命令显示的文档

### What did you see instead?
显示了简略文档，因该是 `go doc path/to/module`  命令显示的文档

**Comment by visualfc** [comment]
fixed, https://github.com/visualfc/gotools/commit/64c955ca5eea92189b5dc32aacc63775ab4c372f
