### ISSUE TITLE
文件系统目录中“在此打开终端"无法打开终端

### ISSUE THREAD

**Issue by widon1104** [visualfc/liteide#1058]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
liteidex36.linux64-qt5.5.1 liteidex36.linux64-qt5.5.1-system liteidex36.linux64-qt4.8.7 
liteidex35.5.linux64-qt5.5.1这4个版本都试过都不行

### What version of Go are you using (`go version`)?
go version go1.12.5 linux/amd64

### What operating system and processor architecture are you using(`go env`)?
deepin15.10.1

### What did you do?

If possible, provide a recipe for reproducing the error.
就是在深度系统下“在此打开终端"无法打开终端，在ubuntu系统下正常的，不知道是哪里出了问题

### What did you expect to see?
“在此打开终端"会打开终端

**Comment by BLumia** [comment]
概览了一下代码，相关代码：

https://github.com/visualfc/liteide/blob/9bb89f26d58ff49d92d55724efc5d1d5d85da978/liteidex/src/utils/filesystem/filesystemwidget.cpp#L478-L518

看上去只会读取 `LITEIDE_SHELL` 环境变量的值。预设提供的值也不包含 Deepin 的 `deepin-terminal` ：

https://github.com/visualfc/liteide/blob/26e410ec2b1a9960e7afe1c1e02cf251ec42fd0a/liteidex/os_deploy/linux/liteenv/linux64.env#L18

值得一提的是，对于 Debian 系发行版，存在 `x-terminal-emulator` 链接（`/etc/alternatives/x-terminal-emulator`）指向实际用户所设（`update-alternatives --config x-terminal-emulator`）的默认终端。

供参考。

**Comment by widon1104** [comment]
我试了一下，系统装了gnome-terminal以后，“在此打开终端"可以打开gnome-terminal，希望能够支持terminator和deepin-terminal

**Comment by rocket049** [comment]
解决办法： sudo ln -s /usr/bin/deepin-terminal /usr/bin/xterm

**Comment by visualfc** [comment]
可以试一下修改当前 env 环境变量，加入 deepin-terminal
`LITEIDE_SHELL=gnome-terminal;lxterminal;konsole;xfce4-terminal;xterm;deepin-terminal`

**Comment by BLumia** [comment]
> 可以试一下修改当前 env 环境变量，加入 deepin-terminal
> `LITEIDE_SHELL=gnome-terminal;lxterminal;konsole;xfce4-terminal;xterm;deepin-terminal`

您好，想问一下为何 `LITEIDE_SHELL` 中预制的值没有 `x-terminal-emulator`，它在 debian 系发行版中都可以使用，应该比 hardcode 列举的别的终端可执行文件名称要合理一些。或者是有别的缘故不这么做吗？谢谢。

**Comment by visualfc** [comment]
原因是我不熟悉 linux :)
已加入  x-terminal-emulator https://github.com/visualfc/liteide/commit/9cfa10587274b7e203d2dc97edaf3ed2ec03a90c
