### ISSUE TITLE
still version 36.0 as short version string in version 36.1 (macos)

### ISSUE THREAD

**Issue by suschizu** [visualfc/liteide#1067]
Hello!  I've noticed that version 36.1 still contains 36.0 

<img width="391" alt="Screenshot 2019-08-29 at 12 18 31" src="https://user-images.githubusercontent.com/16004333/63932781-264ca200-ca58-11e9-900e-4ff45dce5187.png">

**Comment by core-code** [comment]
this also happened previously:
https://github.com/visualfc/liteide/issues/1018

**Comment by core-code** [comment]
i can confirm this is fixed in 36.2
