### ISSUE TITLE
mac version start fail 

### ISSUE THREAD

**Issue by fastfading** [visualfc/liteide#1080]
<img width="511" alt="image" src="https://user-images.githubusercontent.com/8351732/67910194-b88a3700-fbbc-11e9-97a5-86eb869b03b5.png">

36.2  newest version

**Comment by larryhu** [comment]
Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/QtPrintSupport.framework/Versions/5/QtPrintSupport
  Referenced from: /Applications/LiteIDE.app/Contents/MacOS/LiteIDE
  Reason: image not found

Binary Images:
       0x109a85000 -        0x109a88ff3 +com.visualfc.liteide (36.2 - X36) <44E413B8-657C-30BF-9DE4-665510DE8DBD> /Applications/LiteIDE.app/Contents/MacOS/LiteIDE
       0x109a8b000 -        0x109b73ffb +libliteapp.1.dylib (36.0 - X36) <2FC42605-CA94-3E0E-8235-A4DC151D071B> /Applications/LiteIDE.app/Contents/MacOS/libliteapp.1.dylib
       0x10af1d000 -        0x10af876ef  dyld (655.1.1) <CE635DB2-D47E-3C05-A0A3-6BD982E7E750> /usr/lib/dyld

**Comment by visualfc** [comment]
please download https://github.com/visualfc/liteide/releases/download/x36.2/liteidex36.2.macos-qt5.12.5-1.zip

**Comment by izanagi1995** [comment]
Link is dead !
