### ISSUE TITLE
希望增加高亮匹配中括号、小括号和尖括号

### ISSUE THREAD

**Issue by ResearchMore** [visualfc/liteide#1082]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
liteidex36.1.windows-qt5.9.5

### What version of Go are you using (`go version`)?
go version go1.13.1 

### What operating system and processor architecture are you using(`go env`)?
windows/amd64

### What did you do?
coding
If possible, provide a recipe for reproducing the error.

### What did you expect to see?
在查看代码（任何编程语言）的时候，当前只能高亮匹配大括号{}，无法高亮匹配中括号[]，小括号()，尖括号<>

### What did you see instead?
希望增加高亮匹配中括号[]、小括号()和尖括号<>

**Comment by visualfc** [comment]
高亮匹配指的是什么，现在对于 Golang ， [] () 都是匹配的。

**Comment by ResearchMore** [comment]
高亮匹配就是点击{}、[]、()和<>，的某一端，例如左端，能高亮显示对应的右端。就像目前在.go类型文件里，高亮匹配的{}、[]和()一样。如果可能，期望能增加一下：
1、其他类型的语言也能高亮匹配（或者做成在配置里面可以勾选是否匹配）
2、能高亮匹配<>
