### ISSUE TITLE
请教一个关于菜单加速键的问题

### ISSUE THREAD

**Issue by ysx1993** [visualfc/liteide#1085]
![Snipaste_2019-11-13_17-36-17](https://user-images.githubusercontent.com/12573603/68751201-26624400-063c-11ea-982f-55edde83bbcc.png)
请问这个红框框出来的加速键如何默认显示出来？Qt里面有什么接口可以设置吗，还是操作系统决定的？因为我看到liteide时默认显示的，qtcreator则是默认不显示的。

**Comment by visualfc** [comment]
应该是 Qt 和操作系统相关的。
我只是在翻译时使用 &File => 文件(&F)
