### ISSUE TITLE
no linux binaries anymore?

### ISSUE THREAD

**Issue by dodona2** [visualfc/liteide#1116]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
36.3

### What version of Go are you using (`go version`)?
 go1.13.9 linux/amd64

### What operating system and processor architecture are you using(`go env`)?
Fedora 31
GOARCH="amd64"

### What did you do?
try to download/install binaries

If possible, provide a recipe for reproducing the error.
go to download page

### What did you expect to see?
liteidex37.linux64-qt5.5.1

### What did you see instead?
only windows ans macos packages

**Comment by tliron** [comment]
This seems to happen on every release, it takes a long time for the assets to show up in the "releases" page.
