### ISSUE TITLE
TROJAN found: Trojan:Win32/Wacatac.C!ml in release: https://github.com/visualfc/liteide/releases/tag/x37.1

### ISSUE THREAD

**Issue by marang** [visualfc/liteide#1117]
build: liteidex37.1.windows-qt5.9.5.zip

> Windows Security: 
> Threat found - action needed. Severe
> 
> Status: Active
> Active threats have not been remediated and are running on your device.
> 
> Thrat detected: Trojan:Win32/Wacatac.C!ml
> Alert level: Severe
> Date: 25/04/2020 10:37
> Category: Trojan
> Details: This program is dangerous and executes commands from an attacker.
> 
> Link: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fWacatac.C!ml&threatid=2147749372
> 
> 
> Affected items:
> - liteide\bin\gocode.exe
> - liteide\bin\gotools.exe

This didn't happen with version 37.0, only on this 37.1 version

**Comment by tadan0** [comment]
Got the same message from Windows Security when extracting both 37.1 and 37 from the GitHub releases pages.

**Comment by visualfc** [comment]
download liteidex37.1-1.windows-qt5.9.5.zip (compile by go1.14.1) and try

**Comment by marang** [comment]
tried 37.1 and 37.1-1, both work and no trojan-warning anymore. thank you!
