### ISSUE TITLE
gotools.exe 总被Defender杀

### ISSUE THREAD

**Issue by gzw13999** [visualfc/liteide#1124]
提示检测到威胁 Trojan:Win32/Wacatac.C!ml
特洛伊木马
这个程序很危险，而且执行来自攻击者的命令。

**Comment by visualfc** [comment]
下载 liteidex37.1-2.windows-qt5.9.5.zip 试一下，或者自行编译 gocode & gotools

go get -u github.com/visualfc/gotools
go get -u github.com/visualfc/gocode

Windows/Linux:  复制 GOPATH/bin gotools and gocode 到 liteide/bin

**Comment by gzw13999** [comment]
gotools.exe 好了
gomodifytags.exe 又开始被杀了。

**Comment by gzw13999** [comment]
我知道有 #1127  
我这只是有好提示，安装包要更新了。
