### ISSUE TITLE
无法跳转到replace的本地项目

### ISSUE THREAD

**Issue by zhang8h** [visualfc/liteide#1128]

**Comment by visualfc** [comment]
更新一下 go tools & gocode ，看能否解决问题。
go get -u github.com/visualfc/gotools
go get -u github.com/visualfc/gocode

Windows/Linux: copy GOPATH/bin gotools and gocode to liteide/bin
MacOS: copy GOPATH/bin gotools and gocode to LiteIDE.app/Contents/MacOS

**Comment by zhang8h** [comment]
感谢您的回复，我去试试

**Comment by zhang8h** [comment]
按您建议的步骤尝试了，这个情况依然存在的，输入replace 其他项目的 包名也没有自动补全功能，甚至这个包名都不出现在提示框中；目前我是将本项目引用的方法都拷贝到了这个项目中，没有使用replace了

**Comment by visualfc** [comment]
能否提供一个简单的可重现 demo 供测试分析？

**Comment by zhang8h** [comment]
您好，再次感谢您的回复，我刚刚在整理demo时发现如果我写成相对路径就没有问题；如下：
```
module my/demo

go 1.14

replace my/utils => ../utils

require my/utils v0.0.0-00010101000000-000000000000
```
写成绝对路径就不行；如下：
```
module my/demo

go 1.14

replace my/utils => G:\test\utils

require my/utils v0.0.0-00010101000000-000000000000
```

实在抱歉，因为我这里无法直接上传文件，所以我把demo上传到了我的一个测试地址中；
demo地址为：[https://github.com/zhang8h/zhang8h.github.io/blob/master/test.zip](https://github.com/zhang8h/zhang8h.github.io/blob/master/test.zip)

**Comment by visualfc** [comment]
已修复  gotools & gocode  ，现在可以解析 GoModule 的 replace 为绝对路径。

需要更新一下 gotools & gocode 
go get -u github.com/visualfc/gotools
go get -u github.com/visualfc/gocode

Windows/Linux: copy GOPATH/bin gotools and gocode to liteide/bin
MacOS: copy GOPATH/bin gotools and gocode to LiteIDE.app/Contents/MacOS

**Comment by zhang8h** [comment]
非常感谢，我这里更新 gotools & gocode 后，已经可以正常跳转了，谢谢您
