### ISSUE TITLE
Feature request - View to display notes (TODO and BUG) in current folder

### ISSUE THREAD

**Issue by JonPulfer** [visualfc/liteide#114]
Hi,

It would be really great if a view pane could be set up to list BUG and TODO notes in the current folder and be able to click on one of the notes to jump to it.

Kind regards
Jon Pulfer

**Comment by softaria** [comment]
+2

**Comment by vedranvuk** [comment]
+3

**Comment by martin-flaregames** [comment]
This would be awesome! As an Eclipse user I will really appreciate to see `TODO`, `FIXME`, `BUG`, and `XXX` as default filter. An option for creating my own tags would also be a nice to have feature.

**Comment by imilo** [comment]
Any progress with this? Very useful feature

**Comment by visualfc** [comment]
fixed in x33

**Comment by docblue** [comment]
X33.2 windows port 没看到TODO视图啊

**Comment by visualfc** [comment]
classview / outline
