### ISSUE TITLE
为什么在import的补全中有一个奇怪的转义？

### ISSUE THREAD

**Issue by xin344** [visualfc/liteide#1143]
### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X37.1

### What version of Go are you using (`go version`)?
1.14.4

### What operating system and processor architecture are you using(`go env`)?
Windows 10 2004

### What did you do?
使用import补全

### What did you expect to see?
补全import包

### What did you see instead?
![liteide](https://user-images.githubusercontent.com/6903628/87442319-ba026f00-c626-11ea-8ebe-708b43a99fa5.png)

**Comment by jerrylu2011** [comment]
楼上兄弟，你在代码区，代码补全是一直都在的么？就是不管你写不写代码都有个补全提示框在你光标处，敲回车就出来第一个。我的一直这样，好烦。每次要旁边点鼠标或者按esc。
<img width="564" alt="Screen Shot 2020-07-15 at 9 49 03 AM" src="https://user-images.githubusercontent.com/42889825/87553014-72a8cc80-c680-11ea-8f14-8296f20abeb1.png">

**Comment by xin344** [comment]
> 楼上兄弟，你在代码区，代码补全是一直都在的么？就是不管你写不写代码都有个补全提示框在你光标处，敲回车就出来第一个。我的一直这样，好烦。每次要旁边点鼠标或者按esc。
> <img alt="Screen Shot 2020-07-15 at 9 49 03 AM" width="564" src="https://user-images.githubusercontent.com/42889825/87553014-72a8cc80-c680-11ea-8f14-8296f20abeb1.png">

我没有这个情况

**Comment by visualfc** [comment]
please update x37.3
