### ISSUE TITLE
Dlv server error! 进程崩溃或运行终止 62097

### ISSUE THREAD

**Issue by mmcer** [visualfc/liteide#1145]
LiteIDE 37.1
go version go1.14.5 windows/amd64

选择使用 delve来进行调试，即使是最简单的 hello world，在预期的输出后，最后面都会报错，错误信息如下：
C:/Software/liteide/bin/dlv.exe --headless --api-version=2 --accept-multiclient exec C:/Portal/Go/src/pi/pi.debug.exe [C:/Portal/Go/src/pi]
time="2020-07-17T10:39:33+08:00" level=warning msg="CGO_CFLAGS already set, Cgo code could be optimized." layer=dlv

C:/Software/liteide/bin/dlv.exe connect 127.0.0.1:3836 [C:/Portal/Go/src/pi]
API server listening at: 127.0.0.1:3836
Hello world
Dlv server error! 进程崩溃或运行终止
Dlv server exited with code 62097
Dlv error! 进程崩溃或运行终止
Dlv exited with code 62097

如果使用 Build+Run 的方式，是没有问题的。
如果选择使用 gdb，无论是调试还是直接 Build+Run，也是没有问题的。

当发生这个错误的时候，在任务管理器里是可以查询到有一个 dlv.exe 进程没有正确退出。

**Comment by visualfc** [comment]
fixed https://github.com/visualfc/liteide/commit/281afbced82192585d3922d286d9f13fd261b950
