### ISSUE TITLE
今天下载的windows版37.1-2和37.1-1防火墙提示有病毒

### ISSUE THREAD

**Issue by snans** [visualfc/liteide#1146]
下载最新的37.1-2和37.1-1都被windows10的防火墙提示查出有病毒，涉及

# “bin\gomodifytags.exe”

---
**原文如下：**
已检测到威胁:Trojan:Win32/Wacatac.B!ml
警报级别:严重
日期:2020/7/19 21:06
类别:特洛伊木马
详细信息:这个程序很危险，而且执行来自攻击者的命令。

---
请查一下是什么原因？会不会gomodifytags.exe名称被记录在案导致？类似：
[https://r.virscan.org/language/zh-cn/report/823261df231d188aa32bf749fa16f30a](https://r.virscan.org/language/zh-cn/report/823261df231d188aa32bf749fa16f30a)

**Comment by visualfc** [comment]
https://github.com/visualfc/liteide/releases/download/x37.1/liteidex37.1-3.windows-qt5.9.5.zip
