### ISSUE TITLE
【Solved】LiteIDE不能自动提示导入第三方包

### ISSUE THREAD

**Issue by duguanyue** [visualfc/liteide#1147]
## LiteIDE版本
- X37.1
## 系统版本:
- Mac Mojave 10.14.6
## 问题描述
使用官方包, 比如 http, 会出现提示: "Warning: package not found, please enter to import net/http"
但是使用第三方包, 比如 gin, 就没有这样的提示, 但是包是有的, 因为在输入 gin.New() 之后保存, gin包就自动导入了.
但是这样就没有方法提示, 很不方便 .

GOPATH, GOROOT都有配置, gocode使用的是$GOPATH/bin下的, gotools是按说明build之后cp到 MacOS/下的.

求帮助.

**Comment by visualfc** [comment]
更新 gocode 试一下
go get -u github.com/visualfc/gotools
go get -u github.com/visualfc/gocode

Windows/Linux: copy GOPATH/bin gotools and gocode to liteide/bin
MacOS: copy GOPATH/bin gotools and gocode to LiteIDE.app/Contents/MacOS

**Comment by duguanyue** [comment]
谢谢, 方法可用. 之前使用stamblerre/gocode使用第三方包没有提示,  换成visualfc/gocode就可以了.
