### ISSUE TITLE
Compiling with the latest version of Qt

### ISSUE THREAD

**Issue by xyproto** [visualfc/liteide#1151]
### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?

commit b4809d3f526f499de80903ca670f27a90eeded73 (tag `x37.1`)

### What version of Go are you using (`go version`)?

go version go1.14.6 linux/amd64

### What operating system and processor architecture are you using(`go env`)?

Arch Linux

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/alexander/.cache/go-build"
GOENV="/home/alexander/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/alexander/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build237457399=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

If possible, provide a recipe for reproducing the error.

I tried to rebuild `liteide` for Arch Linux. This PKGBUILD has worked before, but stopped working after Qt5 was upgraded:

https://github.com/archlinux/svntogit-community/blob/59bab176c2d6e0a68d560bf35d80ab1fc0cb473a/trunk/PKGBUILD

### What did you expect to see?

That it compiled.

### What did you see instead?

```
In file included from ../../../../liteidex/src/utils/dlvclient/dlvclient.cpp:30:
../../../../liteidex/src/3rdparty/qjsonrpc/src/json/qjsondocument.h:135:32: error: ‘Data’ in namespace ‘QJsonPrivate’ does not name a type
135 |     friend class QJsonPrivate::Data;
|                                ^~~~
../../../../liteidex/src/3rdparty/qjsonrpc/src/json/qjsondocument.h:135:5: error: friend declaration does not name a class or function
135 |     friend class QJsonPrivate::Data;
|     ^~~~~~
../../../../liteidex/src/3rdparty/qjsonrpc/src/json/qjsondocument.h:139:37: error: expected ‘)’ before ‘*’ token
139 |     QJsonDocument(QJsonPrivate::Data *data);
|                  ~                  ^~
|                                     )
../../../../liteidex/src/3rdparty/qjsonrpc/src/json/qjsondocument.h:141:19: error: ‘Data’ in namespace ‘QJsonPrivate’ does not name a type
141 |     QJsonPrivate::Data *d;
|                   ^~~~
make[3]: *** [Makefile:516: .obj/release-shared/dlvclient.o] Error 1
```

**Comment by visualfc** [comment]
https://github.com/visualfc/liteide/releases/tag/x37.2

**Comment by xyproto** [comment]
Thanks! I encountered this issue before x37.2 was released and didn't notice that there was a new release. x37.2 works great, and I'm pushing a new Arch Linux package for `liteide` to `[community]` now. :+1:
