### ISSUE TITLE
dlv更新

### ISSUE THREAD

**Issue by hrbustgithub** [visualfc/liteide#1155]
liteidex37.1-3.windows-qt5.9.5     go 1.15

go1.15发布了，但是liteide内置的dlv调试器没有更新。
可以先到https://github.com/go-delve/delve.git 编一个。
如果可能，还是更新一下，方便点。

**Comment by hiwoshixiaoyu** [comment]
遇到了一样的问题，1.15无法使用了

**Comment by visualfc** [comment]
fixed by x37.3
