### ISSUE TITLE
Delve debugger option setup

### ISSUE THREAD

**Issue by Davidrjx** [visualfc/liteide#1164]
### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X37.1
Qt 5.9.5

### What version of Go are you using (`go version`)?
go version go1.11.2 windows/amd64

### What operating system and processor architecture are you using(`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\{USERNAME}\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\go_path\local_workspace
set GOPROXY=
set GORACE=
set GOROOT=E:\Go
set GOTMPDIR=
set GOTOOLDIR=E:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\RENJIA~1\AppData\Local\Temp\go-build054755954=/tmp/go-build -gno-record-gcc-switches

### What did you do?

choose "debugger/delve", then start to debug(F5) golang source code, like kube-apiserver

### What did you expect to see?

normal to enter debug windows or pre-setup a certain breakpoint

in other words, how to append --check-go-version to dlv command? 

### What did you see instead?
 
debug output seems like

```
E:/tool_sws/liteide/bin/dlv.exe --headless --api-version=2 --accept-multiclient exec E:/go_path/local_workspace/src/k8s.io/kubernetes/cmd/kube-apiserver/kube-apiserver.debug.exe [E:/go_path/local_workspace/src/k8s.io/kubernetes/cmd/kube-apiserver]
time="2020-10-12T12:03:49+08:00" level=warning msg="CGO_CFLAGS already set, Cgo code could be optimized." layer=dlv

E:/tool_sws/liteide/bin/dlv.exe connect 127.0.0.1:6739 [E:/go_path/local_workspace/src/k8s.io/kubernetes/cmd/kube-apiserver]
API server listening at: 127.0.0.1:6739
Version of Go is too old for this version of Delve (minimum supported version 1.12, suppress this error with --check-go-version=false)

Dlv server exited with code 1
Dlv exited with code 1
```

**Comment by visualfc** [comment]
fixed https://github.com/visualfc/liteide/commit/263527f9883ee251b98f742722aa8dba21d41136
