### ISSUE TITLE
Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by hfmrow** [visualfc/liteide#1165]
Hi,
| Name                                                       | Version / Info / Name                          |
| ---------------------------------------------------------- | ---------------------------------------------- |
| GOLANG                                                     | V1.15.2 -> GO111MODULE="off", GOPROXY="direct" |
| DISTRIB                                                    | LinuxMint Xfce                                 |
| VERSION                                                    | 20                                             |
| CODENAME                                                   | ulyana                                         |
| RELEASE                                                    | #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020    |
| UBUNTU_CODENAME                                            | focal                                          |
| KERNEL                                                     | 5.4.0-48-generic                               |
| HDWPLATFORM                                                | x86_64                                         |
| GTK+ 3                                                     | 3.24.20                                        |
| GLIB 2                                                     | 2.64.3                                         |
| CAIRO                                                      | 1.16.0                                         |
| [GtkSourceView](https://github.com/hfmrow/gotk3_gtksource) | 4.6.0                                          |
| [LiteIDE](https://github.com/visualfc/liteide)             | 37.3 qt5.x                                     |
| Qt5                                                        | 5.12.8 in /usr/lib/x86_64-linux-gnu            |

I'm using your excellent IDE for long time ago, never had issue on install except for this latest version, i've tried github: https://github.com/visualfc/liteide/releases/download/x37.3/liteidex37.3.linux64-qt5.5.1.tar.gz
and same from sourceforge.

as everytime, i put it to '/opt/liteide' with user rights.
but this time i got:
```bash
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Abandon (core dumped)

```
Just for information, LiteIDE 37.1-qt5.x  work perfectly with same installation as described above.
I've tried to find solutions but each have failed, have you an idea to pass through this state ?

Thank for your work and your program, as i said, it's an excellent IDE for Golang development.

**Comment by gshields** [comment]
Same issue with ubuntu 20.04. I did apt install qt5-default,
Tried both the tar and the app image both fail with 37.3
Installed 37.1 and now it work
37.3 is broken for Ubuntu

**Comment by hfmrow** [comment]
Debug informations:

```bash
$ export QT_DEBUG_PLUGINS=1; /opt/liteide/bin/liteide
QFactoryLoader::QFactoryLoader() checking directory path "/opt/liteide/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/opt/liteide/plugins/platforms/libqxcb.so"
Found metadata in lib /opt/liteide/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 328961
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/opt/liteide/bin/platforms" ...
Cannot load library /opt/liteide/plugins/platforms/libqxcb.so: (/opt/liteide/plugins/platforms/../../lib/libQt5XcbQpa.so.5: undefined symbol: _ZN11QFontEngine14bitmapForGlyphEj6QFixedRK10QTransform)
QLibraryPrivate::loadPlugin failed on "/opt/liteide/plugins/platforms/libqxcb.so" : "Cannot load library /opt/liteide/plugins/platforms/libqxcb.so: (/opt/liteide/plugins/platforms/../../lib/libQt5XcbQpa.so.5: undefined symbol: _ZN11QFontEngine14bitmapForGlyphEj6QFixedRK10QTransform)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Abandon (core dumped)
```

**Comment by hfmrow** [comment]
And finally I found a solution that works for me (with my use of liteide)

rename 'libQt5XcbQpa.so.5'

like that:
/opt/liteide/lib/libQt5XcbQpa.so.5-

this way liteide does not use the built-in library but uses the library installed in Ubuntu 20 ...

**Comment by tetrahedronix** [comment]
This script may also solve the problem

```
#!/bin/sh

export LD_LIBRARY_PATH="/PATH/TO/liteide/lib:$LD_LIBRARY_PATH"

cd /PATH/TO/liteide/bin

./liteide
```

**Comment by hfmrow** [comment]
Yes thanks,
Added to .desktop file:
```bash
Exec=sh -c "export LD_LIBRARY_PATH=/opt/liteide/lib:$LD_LIBRARY_PATH; /opt/liteide/bin/liteide"
```
where "/opt/liteide/" is path to liteide.

**Comment by bertvandepoel** [comment]
This is a workaround, not a fix. This issue should not be closed, since it's a regression.
