### ISSUE TITLE
visualfc/gocode:  inconsistent vendoring

### ISSUE THREAD

**Issue by dmgk** [visualfc/liteide#1167]
Reporting here because `visualfc/gocode` repo doesn't support issues.

When trying to update LiteIDE FreeBSD port, with current `visualfc/gocode` master I get:

```
$ go build -mod=vendor
go: inconsistent vendoring in /gocode-a8c0af008930:
        github.com/visualfc/gotools@v1.3.3: is explicitly required in go.mod, but vendor/modules.txt indicates github.com/visualfc/gotools@v1.3.2

run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory
```

Either go.mod needs to be updated to be in sync with vendor contents or vendor needs to be refreshed.

**Comment by visualfc** [comment]
fixed
