### ISSUE TITLE
macos bigsur上打不开

### ISSUE THREAD

**Issue by dwSun** [visualfc/liteide#1170]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
liteidex37.3.macos-qt5.14.2.zip

### What version of Go are you using (`go version`)?
go version go1.13.15 darwin/amd64

### What operating system and processor architecture are you using(`go env`)?
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/david/Library/Caches/go-build"
GOENV="/Users/david/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/david/Code/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/david/miniconda3/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/david/miniconda3/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="/dev/null"
CXX="/dev/null"
CGO_ENABLED="0"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdeb

### What did you do?

If possible, provide a recipe for reproducing the error.
下载，解压，启动，安全设置通过，重新启动app

### What did you see instead?
dock上有图标，没有任何窗口显示，风扇狂转，任务管理器显示 LiteIde占用99%cpu

**Comment by dwSun** [comment]
37.1可以正常打开

**Comment by visualfc** [comment]
> 37.1可以正常打开

我这没有 macOS bigsur 的测试环境。可能的原因有如下：
1.  Qt 版本
   x37.3 使用 Qt 5.14 编译，x37.1 使用 Qt 5.12 编译
2. terminal 插件
   x37.3 相比 x37.1 多了一个 terminal 插件
3. gotools & gocode
  编辑器初始化时要对 Go 源码库进行查询。

**Comment by u8x9** [comment]
遇到相同的问题

**Comment by lovenotes** [comment]
感谢，哈哈，回滚版本去了

**Comment by visualfc** [comment]
https://github.com/visualfc/liteide/releases/download/x37.3/liteidex37.3.macos-qt5.12.10.zip
可以试试使用 qt5.12.10 编译的是否可用。

**Comment by dwSun** [comment]
liteidex37.3.macos-qt5.12.10.zip也是打不开，跟 liteidex37.3.macos-qt5.14.2.zip 一摸一样的现象，可能不是qt的问题。

**Comment by visualfc** [comment]
https://github.com/visualfc/liteide/releases/download/x37.3/liteidex37.3.macos11-qt5.12.10.zip 试试这个。

**Comment by dwSun** [comment]
> https://github.com/visualfc/liteide/releases/download/x37.3/liteidex37.3.macos11-qt5.12.10.zip 试试这个。

可以了，看上去没啥问题
