### ISSUE TITLE
macOS升级11.0后崩了，无法启动

### ISSUE THREAD

**Issue by xgene** [visualfc/liteide#1175]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?

37.3
### What did you do?

If possible, provide a recipe for reproducing the error.

**Comment by visualfc** [comment]
liteidex37.3.macos11-qt5.12.10.zip
https://github.com/visualfc/liteide/releases/download/x37.3/liteidex37.3.macos11-qt5.12.10.zip
