### ISSUE TITLE
liteidex37.3.linux64-qt5.5.1启动时报错libqxcb.so

### ISSUE THREAD

**Issue by ofooo** [visualfc/liteide#1178]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
liteidex37.3
解压文件：liteidex37.3.linux64-qt5.5.1.tar.gz

### What version of Go are you using (`go version`)?
go version go1.13.8 linux/amd64

### What operating system and processor architecture are you using(`go env`)?
我的系统是ubuntu1 20.04
Linux version 5.4.0-54-generic (buildd@lcy01-amd64-024) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020

### What did you do?

If possible, provide a recipe for reproducing the error.
我输入 ```QT_DEBUG_PLUGINS=1 liteide```，启动程序时报错如下：
```
QFactoryLoader::QFactoryLoader() checking directory path "/usr/local/liteide/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/usr/local/liteide/plugins/platforms/libqxcb.so"
Found metadata in lib /usr/local/liteide/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 328961
}
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/local/liteide/bin/platforms" ...
Cannot load library /usr/local/liteide/plugins/platforms/libqxcb.so: (/usr/local/liteide/plugins/platforms/../../lib/libQt5XcbQpa.so.5: undefined symbol: _ZN11QFontEngine14bitmapForGlyphEj6QFixedRK10QTransform)
QLibraryPrivate::loadPlugin failed on "/usr/local/liteide/plugins/platforms/libqxcb.so" : "Cannot load library /usr/local/liteide/plugins/platforms/libqxcb.so: (/usr/local/liteide/plugins/platforms/../../lib/libQt5XcbQpa.so.5: undefined symbol: _ZN11QFontEngine14bitmapForGlyphEj6QFixedRK10QTransform)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

已放弃 (核心已转储)
```

### What did you expect to see?
我期望能正常启动ide

### What did you see instead?
我换了安装包，版本是37.1, 可以启动正常。希望作者看看37.3是不是有什么问题。谢谢。

**Comment by bertvandepoel** [comment]
While I don't speak Chinese, I think I'm experiencing the same Issue. With version X37.1, I have no problems on Ubuntu 20.04 with Qt5, but version X37.3 throws these errors with xcb. It also seems to be looking in the wrong location. The libqxcb.so is available in /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so and should be found automatically. I'm not quite sure why it's prepending a bunch of "../" in front of the .so, that might be part of the problem.

**Comment by consciousnessdev** [comment]
> While I don't speak Chinese, I think I'm experiencing the same Issue. With version X37.1, I have no problems on Ubuntu 20.04 with Qt5, but version X37.3 throws these errors with xcb. It also seems to be looking in the wrong location. The libqxcb.so is available in /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so and should be found automatically. I'm not quite sure why it's prepending a bunch of "../" in front of the .so, that might be part of the problem.

Try This solution https://github.com/visualfc/liteide/issues/1165

**Comment by bertvandepoel** [comment]
I don't have liteide installed in opt. I assume there are ways to fix this by loading extra libraries even on other locations. I however still think this is a regression bug since it used to work just fine with previous versions and just now stopped working correctly. I'm hopeful @visualfc will look into it further and consider fixing it in the next version.

**Comment by visualfc** [comment]
fixed https://github.com/visualfc/liteide/releases/tag/x37.4

**Comment by bertvandepoel** [comment]
I can confirm it works perfectly again on my end. Thank you for fixing this issue!
