### ISSUE TITLE
BUG：在Terminal 设置了 $GOBIN 之后无法消除

### ISSUE THREAD

**Issue by benjamin-yin001** [visualfc/liteide#1180]
今天新开了一个项目，不喜欢 module模式，就没用。
发现模板默认的hello-world程序，用菜单go install 之后没反应，用菜单go clean发现是删除的另一个目录。
因为那个目录已经删除了，所以想起前几天测试的时候，在LiteIDE的Terminal里设置了 $GOBIN为哪个目录，没想到自己记住了。
试了多种办法也没法消除这个影响。

**Comment by visualfc** [comment]
在终端下可以使用 `go env GOBIN` 查看是否设置了 GOBIN 环境
可以使用 `go env -w GOBIN=` 删除 GOBIN 设置

**Comment by benjamin-yin001** [comment]
卧槽，go env 和系统的env不一样啊。
go team 的这些人啊，还他妈和中小学生一样幼稚。都他妈10年了，还是一个半成品。有别的编程语言的好的思想模式吧，还非不学，抄袭都不愿意抄袭，非要想孔乙己一样扭捏作态。一个包管理做了好几个版本了，现在的module还是难用。
