### ISSUE TITLE
终端几乎不可用

### ISSUE THREAD

**Issue by brucezhao** [visualfc/liteide#1183]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X37.3 Based on Qt 5.12.10(64bit)

### What version of Go are you using (`go version`)?
Go 1.15.7

### What operating system and processor architecture are you using(`go env`)?
darwin amd64

打开终端窗口时提示non-login shell，几乎什么功能都没有。

21:09:10: non-login shell [/bin/bash] in /Users/bruce

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ ls
bash: ls: command not found

**Comment by visualfc** [comment]
可以在终端窗口工具条的选项中设置登录模式和切换可使用的 shell
![屏幕快照 2021-02-24 下午9 42 46](https://user-images.githubusercontent.com/714279/109009234-4448a080-76e9-11eb-99be-76724136c9f4.png)

**Comment by brucezhao** [comment]
谢谢，之前没有看到这个选项。
