### ISSUE TITLE
Problem in compile in Ubuntu 18.04 32 bit

### ISSUE THREAD

**Issue by bikashpdash** [visualfc/liteide#1189]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
37.4

### What version of Go are you using (`go version`)?
1.16.3

### What operating system and processor architecture are you using(`go env`)?
Ubuntu 18.04 32 bit intel i3

### What did you do?

If possible, provide a recipe for reproducing the error.

### What did you expect to see?
I expected a build success

### What did you see instead?
Build error

./build_linux_qt5.sh: 50: cd: can't cd to /home/bikash/Downloads/liteide/liteidex/src/github.com/visualfc/gotools
./build_linux_qt5.sh: 51: cd: can't cd to /home/bikash/Downloads/liteide/liteidex/src/github.com/visualfc/gocode
./build_linux_qt5.sh: 52: cd: can't cd to /home/bikash/Downloads/liteide/liteidex/src/github.com/fatih/gomodifytags
error, go install fail

**Comment by ivanruvalcaba** [comment]
I also have the same issue here. I thought it was a issue related to my system but now I see that it is not. In my case, the problem occurred in Debian Testing (32 bit), up-to-date and Golang 1.16.2.

Any possible solution?

**Comment by visualfc** [comment]
git clone https://github.com/visualfc/gotools liteidex/src/github.com/visualfc/gotools
git clone https://github.com/visualfc/gocode liteidex/src/github.com/visualfc/gocode
git clone https://github.com/fatih/gomodifytags liteidex/src/github.com/fatih/gomodifytags

**Comment by bikashpdash** [comment]
Than you @visualfc  
I think this issue is common hence this should be included in install documentation or there should be instructions to update these sub modules.
