### ISSUE TITLE
会持续更新吗

### ISSUE THREAD

**Issue by nameliba** [visualfc/liteide#1208]
后面会有新版本吗?会持续更新吗?

非常好用的软件，已用2年。

**Comment by kkstun** [comment]
我也希望更新，挺好用的。不用频繁更新。

**Comment by mumuhhh** [comment]
+1

**Comment by lstarboy** [comment]
我也一直在用，非常好用！希望作者更新

**Comment by lstarboy** [comment]
我也一直在用，不同的运行方式（BuildAndRun，Test，Debug， Mod）直接点击工具栏一个按钮搞定，在VSCode要配置半天，希望作者更新！另外希望代码编辑区能够进行上下两栏切分。便于代码对比

**Comment by xdeng** [comment]
希望更新
