### ISSUE TITLE
Editor absolutely needs go.work

### ISSUE THREAD

**Issue by Fruchtgummi** [visualfc/liteide#1224]
I can't work with LiteIDE at all at the moment. It doesn't understand go.work and for microservices development I have to link all imports to a repo. go.work works correctly of course, but autocompletion and jumping to the declaration go wrong.

Will there be an update for this or do I have to change the editor?

**Comment by visualfc** [comment]
go get -u github.com/visualfc/gotools
go get -u github.com/visualfc/gocode

Windows/Linux: copy GOPATH/bin gotools and gocode to liteide/bin
MacOS: copy GOPATH/bin gotools and gocode to LiteIDE.app/Contents/MacOS
