### ISSUE TITLE
MacOS download 38.0 still contains version nr 37.4

### ISSUE THREAD

**Issue by suschizu** [visualfc/liteide#1226]
### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
https://github.com/visualfc/liteide/releases/download/x38.0/liteidex38.0.macos-qt5.15.2.zip

### What operating system and processor architecture are you using(`go env`)?
macOS intel 

### What did you do?
downloaded version 38.0 but app says it's version 37.4

<img width="237" alt="Screenshot 2022-05-22 at 18 59 37" src="https://user-images.githubusercontent.com/16004333/169706889-9fc7cf75-95c5-43ab-848f-59d4cb2e329f.png">

### What did you expect to see?
version nr 38.0

### What did you see instead?
version nr 37.4

I think you forgot to update the info.plist > ShortVersionString and BundleVersion

**Comment by visualfc** [comment]
thanks, updated.
