### ISSUE TITLE
No automatic suggestion of functions and variables if the package contains a generic

### ISSUE THREAD

**Issue by MirkoGamerman** [visualfc/liteide#1237]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X38

### What version of Go are you using (`go version`)?
go version go1.19 windows/amd64

### What operating system and processor architecture are you using(`go env`)?
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\GAMER\AppData\Local\go-build
set GOENV=C:\Users\GAMER\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\GAMER\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\GAMER\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=d:\GO\src\bitbucket.org\MirkoGamerman\rocket2messbot\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\GAMER\AppData\Local\Temp\go-build2532339379=/tmp/go-build -gno-record-gcc-switches

### What did you do?

If possible, provide a recipe for reproducing the error.

package proba

var A int

func Min[T int](a ...T) (min T) {
	min = a[0]
	for _, v := range a {
		if v < min {
			min = v
		}
	}
	return min
}

/////////////////////////////////////////
package main

import (
	"demo1/proba"
)

func main() {
	proba.Min(4, 3)
	proba. <--------------
	return
}
### What did you expect to see?
proba.Min
proba.A

### What did you see instead?
Nothing happens 

Code Completer (Ctrl+Space)  don't work

**Comment by visualfc** [comment]
update gocode latest fixed typeparam
https://github.com/visualfc/gocode

**Comment by MirkoGamerman** [comment]
After update - works correctly
