### ISSUE TITLE
Enhancement: DlvDebugger: (Delve) - Ability to pass args to the "dlv.exe ... exec" target (via dlv --)

### ISSUE THREAD

**Issue by Blasikov** [visualfc/liteide#1253]
### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
x38

### What version of Go are you using (`go version`)?
1.19

### What operating system and processor architecture are you using(`go env`)?
Win10 amd64

### What did you do?
Debugging via LiteIDE (DlvDebugger) and delve

Standard F5 (start debugging) builds fooBar.debug.exe and forms this command line (all good):
C:/apps/liteide/bin/dlv.exe --headless --api-version=2 --accept-multiclient --check-go-version=false exec C:/Users/blasi/go/src/fooBar/fooBar.debug.exe

Would like to be able to specify/pass args to the "dlv.exe ... exec" target:

Like this:
C:/apps/liteide/bin/dlv.exe --headless --api-version=2 --accept-multiclient --check-go-version=false exec C:/Users/blasi/go/src/fooBar/fooBar.debug.exe -- {arg1 for fooBar} {arg2 for fooBar} {arg{n} for fooBar} ...

According to the Delve md (https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv.md), this may be passed to dlv as "--".   I tried to place in the DlvDebugger settings, but it is in the wrong spot for dlv to understand it.

Thanks for all of the great work you do for this project and us Gophers!

**Comment by visualfc** [comment]
target args use liteide build custom config TARGETARGS

**Comment by Blasikov** [comment]
That worked great, thanks!
