### ISSUE TITLE
liteidex38.2.linux64-qt4.8.7.AppImage won't start, missing libraries?

### ISSUE THREAD

**Issue by hsandor** [visualfc/liteide#1262]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
liteidex38.2.linux64-qt4.8.7.AppImage

### What version of Go are you using (`go version`)?
go version go1.20.1 linux/amd64

### What operating system and processor architecture are you using(`go env`)?
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sanyi/.cache/go-build"
GOENV="/home/sanyi/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/sanyi/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/sanyi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/sanyi/bin/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/sanyi/bin/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build392490086=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
- downloaded the new, X38.2 version (tried it with 38.1 too)
- made it executable
- started it as the previous versions for years

If possible, provide a recipe for reproducing the error.
- nothing special, just tried to launch it
- appimages worked up to X38
- note: liteidex38.0.linux64-qt5.5.1.AppImage is 48MB, liteidex38.2.linux64-qt4.8.7.AppImage is 29MB, something probably missing here

### What did you expect to see?
- LideIDE runs as all previous versions for years

### What did you see instead?
./liteidex38.2.linux64-qt4.8.7.AppImage: error while loading shared libraries: libQtGui.so.4: cannot open shared object file: No such file or directory

and the same with the previous version:
./liteidex38.1.linux64-qt4.8.7.AppImage: error while loading shared libraries: libQtGui.so.4: cannot open shared object file: No such file or directory

./liteidex38.1.linux64-qt5.5.1.AppImage
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted

**Comment by visualfc** [comment]
fixed: upload fixed bundle/appimage for linux64
https://github.com/visualfc/liteide/releases/tag/x38.2
https://sourceforge.net/projects/liteide/files/x38.2/

**Comment by hsandor** [comment]
Thank you,
both liteidex38.0.linux64-qt5.5.1.AppImage and liteidex38.2.linux64-qt5.5.1.AppImage are working now.
