### ISSUE TITLE
go1.21后自动提示功能不行了

### ISSUE THREAD

**Issue by rocket049** [visualfc/liteide#1285]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
38.2

### What version of Go are you using (`go version`)?
go version go1.21.1 linux/amd64

### What operating system and processor architecture are you using(`go env`)?
ubuntu22.04

### 故障现象

go1.21后自动提示功能不行了。

可以参考 vim-go 和 vscode 的go插件，它们升级后都能用。

**Comment by visualfc** [comment]
下载 x38.3
