### ISSUE TITLE
X38.3, 重命名符号(Module), 搜索出来的不全.

### ISSUE THREAD

**Issue by nuan1989** [visualfc/liteide#1297]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
版本: X38.3

### What version of Go are you using (`go version`)?
go1.20.4

### What operating system and processor architecture are you using(`go env`)?
win7,64位

### What did you do?
demo包调用B包, B包调用A包,    

重命名A包的方法,  demo里面的包方法没跟着重构.
测试代码demo
https://erp.nos-eastchina1.126.net/11/demo.rar

![1](https://github.com/visualfc/liteide/assets/43518669/85b46b1c-e285-4b17-ab21-2d3ade96c23f)

**Comment by visualfc** [comment]
```
go install github.com/visualfc/gotools@latest
go install github.com/visualfc/gocode@latest

Windows/Linux: copy GOPATH/bin gotools and gocode to liteide/bin
MacOS: copy GOPATH/bin gotools and gocode to LiteIDE.app/Contents/MacOS
```
