### ISSUE TITLE
语法提示希望能改善到sublime一样

### ISSUE THREAD

**Issue by ghost** [visualfc/liteide#134]
sublime中安装了gosublime插件后, 语法提示, 可以按任意字母匹配, 比如:
ReadInt32Array这个方法, 我可以输入:Re32, 就可以准确的匹配到这个方法.
而, 目前liteide中, 需要输入: ReadInt32, 才能匹配到这个方法, 要多打好多个字母.
希望能提升这个体验, 谢谢.

**Comment by visualfc** [comment]
FIXIE
