### ISSUE TITLE
Buffer not updated when file is modified

### ISSUE THREAD

**Issue by LeGEC** [visualfc/liteide#145]
When an editor is opened, and the underlying file is modified on disk, liteIDE correctly detects the first modification and reacts accordingly.

However, the following modifications on the same file will trigger no reaction from liteIDE. More specifically : the file will not be reloaded if it is further modified on disk.

**Comment by asimsalam** [comment]
I still see this issue with version X36 on CentOS 7.6.1810.
Is this a regression, if it was fixed earlier?
