### ISSUE TITLE
LiteIDE support for go oracle

### ISSUE THREAD

**Issue by mzimmerman** [visualfc/liteide#153]
The go oracle is at https://code.google.com/p/go.tools/oracle and can tell you certain things about your code.

LiteIDE has:
1. F1 where it shows the "type" of the highlighted item.
2. F2 where it will "jump" your editor to where the function/class/type is declared.

I'd like support for go oracle to get more helpful information about the code I'm looking at.  [User manual available here](https://docs.google.com/document/d/1SLk36YRjjMgKqe490mSRzOPYEDe0Y_WQNRv-EiFYUyw/view).

**Comment by alfaha** [comment]
I concur. Like callers/callees and code coverage highlight.
