### ISSUE TITLE
"open with" (windows) issue returned in version X21

### ISSUE THREAD

**Issue by xunfin** [visualfc/liteide#157]
Issue 26 (See https://code.google.com/p/liteide/issues/detail?id=26 ) appeared to have been fixed, but has returned in version 21 of liteide.

To get a .go file to open with liteide in windows I have to go through:

Explorer directory view ..Folder options>>File Types>>(.go files)>>advanced>>edit , and then manually set the path.

**Comment by visualfc** [comment]
now add folder view. quick open file.
