### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [visualfc/liteide#159]
I would like to point out that identifiers like "[`__LITEAPI_H__`](https://github.com/visualfc/liteide/blob/ffdca6233155ff082e1a4959c3fb7e1263daaa56/liteidex/src/api/liteapi/liteapi.h#L24)" and "[`__LITEOBJ_H__`](https://github.com/visualfc/liteide/blob/88a4958a39c9e9d1b5db04e6ecb5b433884878d8/liteidex/src/api/liteapi/liteobj.h#L24)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by visualfc** [comment]
Coding style

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by visualfc** [comment]
thanks, i'll write a tool to update.

**Comment by visualfc** [comment]
__LITEAPI_H__ => LITEAPI_H

**Comment by visualfc** [comment]
fix it , auto check and update by tools/check_hpp
https://github.com/visualfc/liteide/commit/9fae87f274084e8327bf058442a62ffc5cdeb2dc
https://github.com/visualfc/liteide/commit/df6f881d52d787672b4a55eed8f6b5c995fd37df

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/visualfc/liteide/commit/df6f881d52d787672b4a55eed8f6b5c995fd37df "Deletion of a few underscores from include guards").
