### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [visualfc/liteide#160]
[An extra null pointer check is not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8) like the following.
- [GolangDocPlugin](https://github.com/visualfc/liteide/blob/88a4958a39c9e9d1b5db04e6ecb5b433884878d8/liteidex/src/plugins/golangdoc/golangdocplugin.cpp#L42)
- [GopathProjectFactor](https://github.com/visualfc/liteide/blob/1d808bfe345622001cd1c99f487188f8292e94cd/liteidex/src/plugins/golangtool/gopathprojectfactor.cpp#L61)
- [PackageProject](https://github.com/visualfc/liteide/blob/88a4958a39c9e9d1b5db04e6ecb5b433884878d8/liteidex/src/plugins/golangpackage/packageproject.cpp#L94)
- [QSqlEditor](https://github.com/visualfc/liteide/blob/1d808bfe345622001cd1c99f487188f8292e94cd/liteidex/src/plugins/qsqleditor/qsqleditor.cpp#L70)

**Comment by visualfc** [comment]
personal habit
