### ISSUE TITLE
QtGui/QWidget : No such file or directory

### ISSUE THREAD

**Issue by pierrre** [visualfc/liteide#164]
OS: ArchLinux
QT version: 5 (or 4, I don't know)

When I run `./build_linux.sh`:

```
In file included from ../../../../liteidex/src/3rdparty/qt_browser/chasewidget.cpp:42:0:
../../../../liteidex/src/3rdparty/qt_browser/chasewidget.h:45:25: erreur fatale: QtGui/QWidget : Aucun fichier ou dossier de ce type
 #include <QtGui/QWidget>
```

"Aucun fichier ou dossier de ce type" (french) = "No such file or directory"

http://stackoverflow.com/questions/14260475/qdialog-not-such-file-or-directory-qt-windows

Solution? http://stackoverflow.com/a/14260985

**Comment by visualfc** [comment]
http://wenku.baidu.com/view/28c3cd2f453610661ed9f4e6.html
