### ISSUE TITLE
Request\suggestion: Syntax high-light for "goto" Label: definitions

### ISSUE THREAD

**Issue by xunfin** [visualfc/liteide#169]
The golang GOTO statement has an associated label ie http://golang.org/ref/spec#Goto_statements

Would like the label to be highlighted.. Not very familiar with Kate editor but something like this seems to work:
- In \share\liteide\liteeditor\kate\go.xml add 

``` xml
<RegExpr attribute="RegionMarker" String="[\s]*[\w]+:(\s|$)/>
```

into `<contexts>`

and also 

``` xml
<itemData name="RegionMarker" defStyleNum="dsRegionMarker" spellChecking="false"/>
```

into `<itemDatas>`
- In \share\liteide\liteeditor\color\default.xml modify the "name="RegionMarker" element to something like (bolded, some indicative color)

``` xml
<style name="RegionMarker" foreground="#008000" bold="true"/>
```

The regex "[\s]*[\w]+:(\s|$) appears to work as gofmt always moves the label to the line beginning, and places it on a separate line, but may retain a space separated comment. The labels maybe indented eg possible cases

``` golang
Label1: \\label comment
Label2:
    Label3: \\indented label
    Label4
```

Are there other cases/conflicts?

**Comment by visualfc** [comment]
fixed, now liteide golang parser not use kate.
