### ISSUE TITLE
请添加html,css,js文件的支持。

### ISSUE THREAD

**Issue by xulei8** [visualfc/liteide#175]
这个编辑器的功能已经非常强大了，可做go language的web开发时，需要大量编辑html ,js ,css文件。可以在新建里面，加上这几个文件的引导，实现这些文件类型的染色和提示功能，可加入折叠功能。 这样，我就可完全代替其他编辑器了。电脑中就不需要安装其他编辑器了。

**Comment by visualfc** [comment]
目前已加入语法支持。
