### ISSUE TITLE
请添加自定义文件名，自定义语法，自定义提示功能。

### ISSUE THREAD

**Issue by xulei8** [visualfc/liteide#176]
请添加自定义文件名，自定义语法，自定义提示功能。加入这些功能以后，就是万能编辑器了。我很喜欢这个开发工具，要是能像eidtplus一样天天用就好了。

**Comment by visualfc** [comment]
语法文件位于 share/liteide/liteeditor/kate 目录下 代码提示需要编写插件实现。
