### ISSUE TITLE
Not all variables display in variables windows

### ISSUE THREAD

**Issue by GuyBrand** [visualfc/liteide#185]
Hi .

While debugging , I often get some variables that do not display in the variables windows .
I cant set a watch on them .
Console -> print returns No symbol \"XXXX\" in current context.

But if I use fmt.Println , they do print .

func Sample() {
    for j := 1; j < 3; j++ {
        print(j)
    }

displays j

while 
func Sample() {
    j := 1
    print(j)

does not :(

Using X22 , Win64 .

   Thanks in advance . 
      Guy .

**Comment by visualfc** [comment]
now debug always use -gcflags "-N -l"
