### ISSUE TITLE
不知道是不是liteide的bug，很奇怪

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [visualfc/liteide#187]
代码如下
package main

import "fmt"

func main() {

	x := 1
	y := 2

	fmt.Println(x)
	fmt.Println(y)
}

在amd64，debian7下，用liteide编译以后，直接f5，断在main函数入口，按f10，结果不往下走，需要连续按6次，然后才往下走，这个问题在windows和mac下不存在，32位的linux没有环境测试，我开始的时候怀疑是不是gdb太老，用7.7的源码重新编译了一份，liteide配置了下路径，结果还是一样的，好诡异

刚virtualbox测试了下32位的linux，也有问题

**Comment by visualfc** [comment]
请加载最新的X27版本看是否解决您的问题。
