### ISSUE TITLE
Can't override the binary

### ISSUE THREAD

**Issue by helambuapps** [visualfc/liteide#197]
Im new to Go and LiteIDE and Im stuck,

I created a folder named "go" on my Desktop and a file named "hello.go" inside the folder.

~/Desktop/go/hello.go

``` go
package main

import (
    "fmt"
)

func main() {
    fmt.Println("helambu")
}
```

When I open the file on LiteIDE, build and run, it works for the first time, however, if I change something for example the line fmt.Println("helambu") to fmt.Println("balambu"), build and run it again unfortunately it still runs the previous instance because for some reason LiteIDE can't override the previous build. 

Im sure it is not a POSIX permission issue. It is quite annoying to manually delete the file every time before building and running.

However, I can directly run it from the terminal window.

```
$  go run ~/Desktop/go/test.go
```

**Comment by visualfc** [comment]
fixed, please download latest version.
