### ISSUE TITLE
windows下貌似监控源码外部修改通知没有以前的即时感

### ISSUE THREAD

**Issue by insionng** [visualfc/liteide#203]
说的是v22版,旧版没问题,是在我的win7 64下面出现的情况,主要体现在我用sublime在外部编辑过源码后,liteide没有即时发现,偶尔是的确发现了外部更新并及时提醒了,然后后面又开始无视外部更新,反正liteide源码编辑区内的源码有时候会脱节没法和外部保持同步.

难道不是监控事件实现,而是通过不断扫描源码来发现是否被外部修改的?我没有看ide源码也没有仔细看这个问题是否曾被提及过,希望不会重复发了.但愿引起重视.

**Comment by visualfc** [comment]
请下载最新版本测试
