### ISSUE TITLE
打开新目录会异常退出

### ISSUE THREAD

**Issue by xjing521** [visualfc/liteide#208]
A,B代表两个项目
1，正在编辑A项目，因临时需要修改B项目，遂关闭A目录(通过右键点击项目关闭目录)，打开B目录(通过打开目录图标)
2，通过点击“管理GOPATH”图标更改path路径
3，等待约3秒 会自动闪退
4，重新打开liteide重新配置方可正常
以上情况测试100%出现几率，系统windows7X64，原来以为是操作不当，后来怎么试每次都会出现

**Comment by visualfc** [comment]
请加载最新的X27版本看是否解决您的问题。
