### ISSUE TITLE
Feature request: Ctrl+Click support

### ISSUE THREAD

**Issue by jamiefoster** [visualfc/liteide#215]
It would be great if Ctrl+Click on an element would have the same effect as pressing CTRL+SHIFT+J (Jump to declaration)

**Comment by visualfc** [comment]
fix it
please download x27 and check

**Comment by matrixik** [comment]
Working for me, and is fast.
Thank you.

**Comment by jamiefoster** [comment]
When I hold Ctrl and click with the left button, I get the context menu (just like right clicking). Is this normal?

**Comment by jamiefoster** [comment]
Working here as well. Thank you! Thank you!
