### ISSUE TITLE
关于LiteIDE编辑器自动补全和行内编辑换行的问题

### ISSUE THREAD

**Issue by lichhaosysu** [visualfc/liteide#230]
我发现不管是小括号，单引号，双引号，LiteIDE在自动补全之后，我都没有办法跳过自动补全后的那一半，继续输入。
比如我输入一个双引号，编辑器自动补全了另外一半，我输入完成后，必须按方向键跳过补全的那个双引号，这样导致输入的效率极慢，在eclipse里面 我只需要直接输入同样一个双引号 就能继续输入，建议LiteIDE也这样做。
另外，LiteIDE好像没有支持行内直接换行的快捷键，即输入的时候 每次都要按end到一行末尾再换行 觉得蛋疼无比。希望能增加一个这样的快捷键，跳过该行后面的内容直接换行（vim中的o）

**Comment by fetag** [comment]
X30.2, Same issue.
