### ISSUE TITLE
再次报那个linux下输入法的问题

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [visualfc/liteide#235]
上次报说，在linux下fmt.Println后面输入中文的时候，会被gocode的提示抢占，后来根据大神的指点，改了快捷键为alt+/

但是现在第一次打开文件的时候可以在fmt.Println后面输入中文，只要输入过一次，后面ctrl+space就切换不了了;因为不知道具体原因，我自己测试了下

如果我输入的代码是这样
package main

import "fmt"

func main() {
    fmt.Pri
}
问题就出现了，如果后面的几个字手工输入，则可以切换中文输入法;
如果是按快捷键补全（alt+/），切换中文100%失败，除非关闭当前文件，重新打开;
测试了很多次都是这样

我liteide重启了几次，测试结果都是这样的
现在打印中文，基本上都是关闭，打开，太麻烦了

测试版本：linux，debian7，amd64
mac：无此bug
win：无此bug

**Comment by visualfc** [comment]
请下载 x27版本看是否解决了您的问题。
