### ISSUE TITLE
右键，选择重构，重命名的时候，引用不全

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [visualfc/liteide#244]
如题，如果都在同一个文件夹里面还行，如果是定义了多个GOPATH，基本上就只能文件夹搜索，然后一个个改了，我看到有个叫go-oracle的工具，似乎是能找到相关的引用的，不知道是不是可以根据GOPATH 去找引用，下面一个是atom编辑器的go-oracle插件演示
https://atom.io/packages/go-oracle

**Comment by rwxdfbb** [comment]
能不能指定目录查找呢，通常情况下，重构过的名称有很多在其他包或文件夹下引用

**Comment by visualfc** [comment]
下一版本会做全局查找支持。
