### ISSUE TITLE
configuration for showing the whitespace 

### ISSUE THREAD

**Issue by liuhewei** [visualfc/liteide#260]
It's not an issue but a suggestion. I wonder if you can add a configure item in LiteEditor for showing whitespaces in code? It's very useful for checking if there is wrong-input spaces or tabs.

For example, here is the effect in Sublime Text:
![image](https://cloud.githubusercontent.com/assets/4601961/4766228/7acaf98c-5b4d-11e4-856b-7e11efbce875.png)

**Comment by visualfc** [comment]
please down x27, support tab and space show option.

**Comment by dvirsky** [comment]
@visualfc would it be possible to alter this config dynamically? For instance, there is no option for yaml files, and when opened they are edited with tabs which is a syntax error in yaml.

**Comment by dvirsky** [comment]
Oh nevermind, I found that I can just add a yaml KATE definition file and it will be configurable. I'm opening a PR for adding yaml.xml
