### ISSUE TITLE
Suggestion for quickly locating the source file in project

### ISSUE THREAD

**Issue by liuhewei** [visualfc/liteide#263]
Hi, 

Another feature suggestion for quickly locate/goto/open the source file with given name string/regex. It's very common in IDE I think. For example, it's the "Ctrl+P" in sublime text.

My work depends a lots on this feature, because when I see a modification in SCM tools, or some other information in call-stack, debugging, warning windows, I always want to quickly open this file firstly. It's hard for me to do this in LiteIDE, or I might haven't find the usage in it?

I have to use LiteIDE and SublimeText in the same time. I hope most time I can only open LiteIDE and do my works. 

Does it make sense to you guys? Looking forward to your response. Thanks.

**Comment by pm-kartik-sura** [comment]
+1

**Comment by visualfc** [comment]
fixit Ctrl+P to QuickOpen
