### ISSUE TITLE
liteide的跳转为什么比gosublime插件好？

### ISSUE THREAD

**Issue by lubia** [visualfc/liteide#264]
gosublime插件只能跳转到某个package的可导出函数或者struct，不能跳转到struct的方法，
请问liteide是怎样实现的？
据我了解，liteide和gosublime都使用了gocode来实现跳转，而gocode是不能跳转到struct的方法的，
请问liteide是怎样实现的？

**Comment by visualfc** [comment]
liteide 不是用gocode实现的

**Comment by lubia** [comment]
已采用godef，tks
