### ISSUE TITLE
Wrong identifier selection in the Editor window

### ISSUE THREAD

**Issue by vcrobe** [visualfc/liteide#268]
In the Editor window when you double click an identifier it selects **all matches in the file** including comments and identifiers with the same name starting with an underscore.

It should select the identifier inside its scope (i.e. function only).

![wrongidentifier](https://cloud.githubusercontent.com/assets/7717678/4825162/0006bf4c-5f62-11e4-80f4-3a9ff68aea17.png)

I see this behavior since version x22. That was the first version I used.

**Comment by visualfc** [comment]
select the identifier match word only
