### ISSUE TITLE
need  to be optimized Ctrl+R BuildAndRun功能需要优化

### ISSUE THREAD

**Issue by studentht** [visualfc/liteide#309]
如果编辑窗口的文件不是包含main函数的go文件，Ctrl+R后会提示“错误：进程无法启动”，必须将编辑文件切换到main函数所在go文件后才能BuildAndRun，请问能否优化下，在项目内任何编辑任何文件时都可以BuildAndRun整个项目

**Comment by visualfc** [comment]
请下载X27版本，支持编译项目锁定功能。

**Comment by studentht** [comment]
已经在使用了，非常赞的功能，辛苦了。:+1:
