### ISSUE TITLE
无法正常输入大写字母

### ISSUE THREAD

**Issue by yangwenmai** [visualfc/liteide#315]
mac os ,LiteIDE X25
使用键盘caps lock无法键入大写字母，必须使用shift+字母才能键入大写字母。

**Comment by longtengdidu** [comment]
很久之前就有这个问题，目前27.1依旧还有

**Comment by visualfc** [comment]
我只有MACOSX虚拟机

**Comment by yangwenmai** [comment]
现在发现，我跟#404 这个是一样的，不是写着写着变了，而是在第三方输入法情况下，100%重现。希望能解决。

**Comment by artfantasy** [comment]
同样，希望能在下个版本解决，试了非常多的第三方输入法，都有这个问题。。

**Comment by visualfc** [comment]
下载Qt5编译版本
