### ISSUE TITLE
 Cannot mix incompatible Qt library (version 0x40806) with this library (version 0x40801)

### ISSUE THREAD

**Issue by ghost** [visualfc/liteide#316]
[netroby@localhost ~]$ opt/liteide/bin/liteide
Cannot mix incompatible Qt library (version 0x40806) with this library (version 0x40801)
已放弃 (核心已转储)

**Comment by nange** [comment]
每次更新下来都会处理一次这个问题，比较麻烦，有没有一种机制，比如系统有就用系统的，没有就用自带的？

**Comment by visualfc** [comment]
https://sourceforge.net/projects/liteide/files/?source=navbar

liteidex27-1.linux-64.tar.bz2
liteidex27-1.linux-64-system-qt4.8.tar.bz2

下载文件提供了两种，系统有Qt4.8的，下载第二个就可以了。

在 2015年2月12日 下午10:37，LanceLi <notifications@github.com>写道：

**Comment by larryhu** [comment]
thanks

**Comment by renhuihhh** [comment]
I got same problem ... And it works , 因为是自己的ubuntu机器上已经有qt的环境了
