### ISSUE TITLE
Support Icon Themes

### ISSUE THREAD

**Issue by dvirsky** [visualfc/liteide#329]
Hi. I really enjoy LiteIDE but the main icon bar ("B" "BR" etc) really makes it hard for me :)
I replaced some of the icons with icons from IntelliJ locally and IMO it's more visually appealing. 
I'm not sure this can be legally distributed, and not all icons can be be mapped directly to LiteIDE, but this brought me to the thought that icon themes would be a nice addition.

Just for reference, I'm attaching a screeshot of my LiteIDE with IntelliJ IDEA icons. 
![liteide](https://cloud.githubusercontent.com/assets/503226/5517843/2cd4a91c-890b-11e4-80a1-a032dffa5748.png)

Alternatively, I'm willing to work on improving the icon theme without this support, let me know what you think.

**Comment by tschundeee** [comment]
@dvirsky looks great. Did you also alter the theme? I'm on mac and the dark theme there looks very different from what you got there.

**Comment by dvirsky** [comment]
@tschundeee This is on Linux, and I'm using a dark theme. I personally only modified the icons.

**Comment by dvirsky** [comment]
@visualfc FYI I've asked the IntelliJ people, their icon set is released under Apache 2, and since LiteIDE has an LGPL license, we can simply use their icon set, apart from a couple that contain their trademark (which are not needed anyway).

**Comment by GoBijan** [comment]
Thumbs up!
