### ISSUE TITLE
我是来灌水的。。

### ISSUE THREAD

**Issue by micln** [visualfc/liteide#336]
http://golanghome.com/post/550
这些东西阔以都集成进去吗？

因为我之前有想法搞个Go开发工具集，后来想想这不就是个IDE么。。。。

所以拜托大神了。。

**Comment by visualfc** [comment]
liteide集成了goimports功能，编译配置默认支持go vet, go lint, gopm，文件需要自己安装，配置文件是share/liteide/litebuild/gosrc.xml自己可以参考扩展。
