### ISSUE TITLE
Feature request: vim mode

### ISSUE THREAD

**Issue by veegee** [visualfc/liteide#339]
Any decent editor needs to have a vim mode

**Comment by diegogub** [comment]
+1

**Comment by perepechaev** [comment]
+1

**Comment by johnnadratowski** [comment]
+1

**Comment by luanzhu** [comment]
+1

**Comment by haoyixin** [comment]
+1

**Comment by jiaqingw** [comment]
+1

**Comment by azinman** [comment]
+1

**Comment by JerryZhou** [comment]
+1

**Comment by edel** [comment]
+1

**Comment by ashwin** [comment]
+1

**Comment by freshcn** [comment]
+1

**Comment by hqy** [comment]
+1

**Comment by godlikeJia** [comment]
+10086

**Comment by insanehui** [comment]
+1

**Comment by visualfc** [comment]
please download liteidex30.2 and test vim mode

**Comment by insanehui** [comment]
how can I use % key to match “{” "}"s in vim mode? thanks!!

**Comment by posener** [comment]
@visualfc , This feature is great!
I see that the keyboard shortcuts stopped working once the vim mode is on. Is there any way to use them in this mode (for example the ctrl-p, alt-left, etc...)
