### ISSUE TITLE
Two Question 

### ISSUE THREAD

**Issue by studentht** [visualfc/liteide#340]
1.大纲列表  functions 总是出现，即使一个package中没有function，Functions图标也会出现。但是对于const，如果一个package没有const，则const图标就不会出现。测试发现，当且仅当一个package一个function都没有(类方法和包函数)时，functions图标才会不显示。
如下图所示
![ide functions](https://cloud.githubusercontent.com/assets/8980106/5605609/8d334130-943f-11e4-975e-674b5ff45c99.png)
![ide functions_2](https://cloud.githubusercontent.com/assets/8980106/5605610/8d35d616-943f-11e4-86ed-b1ee7aa35d30.png)

2.一个函数返回类对象时，这个函数会出现在大纲的functions中和类方法列表中（即同时出现在两个位置）。。这个科学吗？

**Comment by visualfc** [comment]
返回类对象方式划分在类方法列表中，这是按godoc的默认分类。加入到Functions中是为了好找。应该保留哪个还没想好，您对此有什么看法？

**Comment by visualfc** [comment]
已修复，划分在Function中。
