### ISSUE TITLE
Wrong menu in the re-position icon

### ISSUE THREAD

**Issue by scorredoira** [visualfc/liteide#347]
With the arrows icon it was possible to re-position tool windows, but in version 26 the menu that displays is the same as the drop down.

![image](https://cloud.githubusercontent.com/assets/1644405/5759594/3202dada-9ccf-11e4-8465-7054fdc9171d.png)

![image](https://cloud.githubusercontent.com/assets/1644405/5759531/d9467410-9cce-11e4-9712-e09110a86a54.png)

 Also that icon has disappeared in the bottom window with the build output.

**Comment by scorredoira** [comment]
Reviewing the commit history, it seems to be fixed by this commit?

https://github.com/visualfc/liteide/commit/87c2e79cc436b667ab6b72e6cbd510c993ca773c

**Comment by visualfc** [comment]
liteide option liteapp style
SidebarStyle
SplitterStyle -> enable move

this request re-start liteide

**Comment by scorredoira** [comment]
thank you!
