### ISSUE TITLE
Multiple windows causes key bindings to fail

### ISSUE THREAD

**Issue by lologarithm** [visualfc/liteide#350]
System: Ubuntu 14.04 64bit

1. Open single window, press CTRL+B, everything builds. 
2. Select 'Open Folder in New Window' from menu
3. Open up and try to build in new window via CTRL+B, nothing happens
4. Go back to original window and press CTRL+B, nothing happens

Expected that the windows would build when focused and I press CTRL+B

Are there any logs I can collect that can help you with this issue?

**Comment by visualfc** [comment]
fix it.
please download x27

**Comment by benechols-wf** [comment]
Fixed - this  can be closed.
