### ISSUE TITLE
Use Qt 4.5 or later. Fixes font alignment bug in buttons and context menus in OSX

### ISSUE THREAD

**Issue by nacho4d** [visualfc/liteide#357]
I have found LiteIDE to be a very good editor! Thanks!

I've noticed that in X26 version in OS X 10.10:
- Font vertical alignment is incorrect in buttons, labels and _context menus_.
- Also text colors are sometimes incorrect in active/inactive tab buttons.
- Context menus sizes are small
- Othe minor stuff

Those are qt bugs but are solved in 5.4.

Please compare the same X26 version
Binary from SourceForge:
![x26](http://i61.tinypic.com/119rofb.png)
Binary compiled with Qt5.4
![x26 with qt5.4](http://i61.tinypic.com/u5xj9.png)

Please consider using the latest version of qt :)
(If you use the latest version of qt I think this comment will be unneeded too:
https://github.com/visualfc/liteide/blob/master/liteidex/src/liteapp/main.cpp#L67 )

Thanks!

**Comment by visualfc** [comment]
macos default build qt5.6.2
