### ISSUE TITLE
Clear All增加快捷键

### ISSUE THREAD

**Issue by jiangyubao** [visualfc/liteide#367]
在Event Log、Build Output、Debug Output输出列表里面，鼠标右键，显示的菜单有一个Clear All，这时候按下'r‘则触发Clear All的行为；

这样的好处是，鼠标只右键，左手的键盘按下r键，双手操作，操作速度非常快；

**Comment by visualfc** [comment]
Build output 目前是自动清除，也可以自行配置快捷键。

**Comment by jiangyubao** [comment]
no need such feature
