### ISSUE TITLE
error line jump，key binding, and feature request

### ISSUE THREAD

**Issue by wheelcomplex** [visualfc/liteide#37]
ctrl+g no effect
FIX BY:  LiteIDE-Option-LiteApp-Keybord change goto line key binding to ctrl+L

double click on error log, jump to line:
./qps-http-app-server.go:528: undefined: aaa
 exit code 2, process exited normally. 
FIX BY: LiteIDE-Option-LiteBuild- gosrc.xml  change
<config id="ErrRegex" name="ERRREGEX" value="([\w\d_\\/\.]+):(\d+):"/>
TO
<config id="ErrRegex" name="ERRREGEX" value="([\w\d_\-\\/\.]+):(\d+):"/>
restart liteide.

and more:

此外，有个几个小小的建议：
1. 在编辑时，双击选择某单词后，同一屏幕的相同单词都高亮， 可能不是总是需要这个特性，可能搞成ctrl+双击才高亮;
1. 现在的搜索，当某个单词处于折叠的位置，光标并不会定位到该位置； 期望的行为是： 自动打开折叠并定位;

3.当高亮某单词时，ctrl+g（search next）和ctrl+shift+g自动search此单词，而非前一次搜索的单词（似乎ultraeditor是这个行为）;
1.  ctrl+f或ctrl+h打开搜索或替换，当点击某个行为时（搜索/替换/全部替换等），自动hide输入界面;
2. find all 能力， notepad++ 有这个能力， 点击find all，在output 窗打开所有包含该单词的行的列表，双击某一行就跳转过去。
3. 列编辑能力，geany/notepad++/UE/sublime都有的，按住shift+alt，然后按箭头上下左右或鼠标划选，可以选择文本块；如果是按住上述组合后选择多个列后，键盘输入的字符会出现在每一行。
4. 缩进指示线，like sublime;
5.  ctrl+f或ctrl+h打开搜索或替换，触发界面后，光标定位在输入栏且默认全选前一次的文本;

**Comment by luciotato** [comment]
First: Great work! Congratulations!

Second: Request:
Can you please add a keybinding for next-error (F4), previous-error (Shift-F4)
(something similar to sublime)

Thanks

**Comment by rwxdfbb** [comment]
This is a good idea, and I also have a request: please add block edit mode, for example press the key "Alt"

Thanks

At 2015-02-05 18:32:30,"Lucio M. Tato" <notifications@github.com> wrote:


First: Great work! Congratulations!

Second: Request:
Can you please add a keybinding for next-error (F4), previous-error (Shift-F4)
(something similar to sublime)

Thanks

**Comment by wheelcomplex** [comment]
well done, thanks.
