### ISSUE TITLE
Feature Request 行移动和项目

### ISSUE THREAD

**Issue by spance** [visualfc/liteide#372]
同其它编辑器一样，希望能增加行/选区的上移/下移。
增加个快捷键 Ctrl+shift+up/down

还有，以前有锁定工具栏，现在怎么没有了，还是希望加上。

另外有个改进建议，最好能有project概念，
在一个project下，有自己的gopath，有编辑参数、运行参数等等。
这样就能在多个project下切换非常方便，项目有自己的profile就不需要人来改了。

感谢如此好的作品，感谢作者辛苦的劳动。

**Comment by armink** [comment]
完全赞同，正要发这个issue。
行/选区的上移/下移alt+up/down，及复制行 Ctrl+shift+up/down，是使用频率非常高的快捷键。

**Comment by visualfc** [comment]
x27.1已发布，增加行移动/复制功能。
