### ISSUE TITLE
含有汉字的类名、函数名不能正确着色

### ISSUE THREAD

**Issue by linlexing** [visualfc/liteide#374]
X27版本，含有汉字的类名、函数名不能正确着色，比如：
```go
type Dept struct {
	Name  string
}
type T部门 struct {
	C名称  string
}
```
第二个结构中，汉字后面的关键词都会变成灰色

**Comment by visualfc** [comment]
https://github.com/visualfc/liteide/commit/cb8f5a3fc893a1db102f579b3529d56820506447
对于非ANSI字符作了位置调整。
https://github.com/visualfc/liteide/commit/bc206629ce10b9e77097ef221d148485d946e6a9
AstView作了UTF8支持。

**Comment by linlexing** [comment]
新的代码应用后，发现几个问题：
* 类名首字母与后面汉字颜色不一致
* 函数名含有汉字时，会有多种颜色,如下面的代码中，【向】是绿色，【径】是蓝色
```go
func (dept *T部门) F向上路径(root string) []*T部门 {
} 
```
* 结构体中成员含有汉字的，不能正确格式化，如下面，两个string没有对其
```go
type T角色 struct {
	C名称   string
	C部门代码 string
}
```
>为了看到改动效果，对照着说明编译了一次。我用qt5.4进行编译，手工复制了依赖的qt5.4的dll和其他的文件，成功运行，然后主要的不同就是菜单的快捷键字母默认不显示，需要按下alt才显示，好不习惯

**Comment by visualfc** [comment]
x27.1源码已修复，请更新源码编译

**Comment by visualfc** [comment]
x27.1已发布
