### ISSUE TITLE
trying to open a UNC network path on Windows causes crash

### ISSUE THREAD

**Issue by apmckinlay** [visualfc/liteide#375]
e.g. `\\psf\Dropbox\Go\src\github.com\apmckinlay\gsuneido`

tried both drag and drop and File > Open Folder

if I map a drive letter, e.g. `net use v: \\psf\Dropbox`

then this works: `V:\Go\src\github.com\apmckinlay\gsuneido`

this is on 64 bit Windows 8.1 with LiteIDE x27

**Comment by visualfc** [comment]
QFileSystemModel with UNC path on Windows problem
http://qt-project.org/forums/viewthread/32606

the bug liteide can not be repaired, but can check error.

**Comment by visualfc** [comment]
x27.1 no support UNC path , but check UNC path and report error message and not crash.
please x27.1 and test.
