### ISSUE TITLE
汉字文件名称显示乱码

### ISSUE THREAD

**Issue by linlexing** [visualfc/liteide#386]
当文件名称含有汉字且编译出错时，下方的提示信息中，文件名称将是乱码，并且双击不会跳到正确的行

**Comment by ZoomQuiet** [comment]
这个应该是特性,
不是 bug 吧...

2015-02-13 16:28 GMT+08:00 linlexing <notifications@github.com>:

> 当文件名称含有汉字且编译出错时，下方的提示信息中，文件名称将是乱码，并且双击不会跳到正确的行
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/visualfc/liteide/issues/386>.
>



-- 
Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by visualfc** [comment]
建议不使用中文目录和文件名
