### ISSUE TITLE
类视图汉字显示为乱码

### ISSUE THREAD

**Issue by linlexing** [visualfc/liteide#387]
类名或者成员如果含有汉字，这左边类视图中这些都显示为乱码。

>汉字在基础软件编程中可以不用，但是描述具体的行业业务逻辑时，用汉字可以少很多注释，而且不用汉字，行业业务逻辑用英文不好表述，只能用拼音缩写，那真是天书了。好不容易有个国人开发的项目，就提了很多中文处理的需求，作者辛苦了。

**Comment by visualfc** [comment]
x27.1源码已修复

**Comment by visualfc** [comment]
x27.1 已修复，请下载测试。
