### ISSUE TITLE
Debugging Broken

### ISSUE THREAD

**Issue by ishbir** [visualfc/liteide#391]
I'm trying to debug my tests and get the following errors in the GDB console:

```
(gdb) 
&"Warning: /usr/lib/go/src/pkg/runtime: No such file or directory.\n"
10000008^done,source-path="/usr/lib/go/src/pkg/runtime:$cdir:$cwd"
(gdb) 
&"set substitute-path /go/src/pkg/runtime /usr/lib/go/src/pkg/runtime\n"
10000009^done
(gdb) 
10000010^error,msg="No symbol table is loaded.  Use the \"file\" command."
(gdb) 
10000011^error,msg="No executable file specified.\nUse the \"file\" or \"exec-file\" command."
(gdb) 
```

I know that the paths are right because I've been building and testing and that works fine. Even debugging of code is broken. The directory /usr/lib/go/src/pkg/runtime does not exist because runtime is located at /usr/lib/go/src/runtime (default Go install in Arch Linux with no modifications). However, even when I add a simlink, the other errors still persist.

**Comment by davyzhang** [comment]
mac? The debug function was broken on my mac for a loooooooooooooong time, nice to have it back.
error is the same

gdb using brew installed dupe one ,and self signed as this url:http://joubin.me/post.php?post=gdb.txt

**Comment by ishbir** [comment]
Nope, I'm using Linux.

**Comment by visualfc** [comment]
please download x35.1 and check. use delve debug.
