### ISSUE TITLE
`Jump to declaration` not working 

### ISSUE THREAD

**Issue by octopepper** [visualfc/liteide#393]
I'm running LiteIde on a Mac with Yosemite 10.10.1 (14B25) and go 1.3.3
and none of these features are working : 
- Jump to declaration
- View Express Information
- Find Usages

LiteIde version : X27

**Comment by octopepper** [comment]
This is fixed for me with version X27.1. Thks

**Comment by wadelee1986** [comment]
how to fixed this issues, could you please help me .
