### ISSUE TITLE
Feature Request: Donate Button / gratipay ;)

### ISSUE THREAD

**Issue by colorsocean** [visualfc/liteide#398]
Add "Donate" button visible on the main window of liteide. On click lead to donation system with English frontend (maybe gratipay). LiteIDE helps with everyday work to many people and helps them to gain money, I think many of them be glad to share a bit :)

**Comment by mauleyzaola** [comment]
:+1:

**Comment by visualfc** [comment]
fixit add PayPal

**Comment by fadiasamara** [comment]
@colorsocean long-awaited

**Comment by mauleyzaola** [comment]
@visualfc Any other options besides PayPal?

![image](https://cloud.githubusercontent.com/assets/1648558/26227105/f27facee-3bf5-11e7-9035-b00d4b544235.png)

**Comment by visualfc** [comment]
Sorry, PayPal does not support creating a "Donation" button in China. So I can only created the "Buy Now" button to accept the donation.
