### ISSUE TITLE
功能建议:增加书签功能及合理快捷键，bookmarks

### ISSUE THREAD

**Issue by devcodewak** [visualfc/liteide#399]
LiteIDE很好用，非常感谢作者您

建议增加书签功能，bookmarks多为ide标配，阅读修改程序多处上下文时很常用，很重要。

请看下本issue里老外关于bookmarks的肺腑之言:
https://github.com/visualfc/liteide/issues/124

**Comment by visualfc** [comment]
fixed, please download x33 and test

**Comment by devcodewak** [comment]
打开33，发现了，测了下，现虽简单，亦好用，thanks

后续小建议：
 1 打开目录时，该目录下所有书签均显示出来。双击书签则打开源码及定位。
2 书签可添加简要说明
