### ISSUE TITLE
Feature Request: Command line option to set ENV

### ISSUE THREAD

**Issue by rvjcallanan** [visualfc/liteide#40]
Currently, LiteIde allows a file or folder to be included as a command-line option.

i.e. liteide.exe myproject

will start up LiteIde at the specified project directory.

This is very convenient when LiteIde is invoked from a batch file (or script) within a custom project environment.

It would be even more convenient if I could also set the active LiteIde environment via the command-line using, say, an "-e" option

e.g. liteide.exe -e custom.env myproject

**Comment by bep** [comment]
I currently use the environment "switcher" to change between `go` and `gopherjs` builder (not perfect, but it works: https://github.com/bep/go-or-gopherjs)

It would be great if I would somehow load environments automatic per project / package.

**Comment by visualfc** [comment]
please download latest version

liteide --select-env [system|win32|cross-linux64|...]
