### ISSUE TITLE
执行 编译－》 Run ，然后点“停止执行” 按钮时，发的信号是什么？ 

### ISSUE THREAD

**Issue by ablegao** [visualfc/liteide#401]
执行 编译－》 Run ，然后点“停止执行” 按钮时，发的信号是什么？ 

在给程序加信号捕捉的功能， 让程序退出时， 保持一个有效的退出。发现无法直接捕获 停止运行 按钮的终止操作， 从命令行执行kill 有些费劲。所以， 咨询一下。

**Comment by visualfc** [comment]
Windows 下使用 TerminateProcess, 
Linix 和 Mac OS X, 发送 SIGKILL signal

**Comment by ablegao** [comment]
Mac  下会提示 错误: 进程崩溃或运行终止. 


接收不到  SIGKILL信号

**Comment by visualfc** [comment]
x32 
SIGTERM wait 100ms SIGKILL
