### ISSUE TITLE
匿名对象不能给出代码提示

### ISSUE THREAD

**Issue by wdsgyj** [visualfc/liteide#408]
系统环境：Win8.1 x64 
软件版本：27.1

问题描述：类似于下面的代码：
        MainWindow{
        ……
    }.Run()
MainWindow  匿名对象后面输入 . 符后并不会出现代码提示。而改为
        win := MainWindow{
        ……
    }
        win.Run()
是可以出现代码提示的。

**Comment by visualfc** [comment]
gocode 目前不支持匿名对象的代码提示。
https://github.com/nsf/gocode

**Comment by visualfc** [comment]
geocode 已经支持匿名对象后面输入，请下载最新的liteide.
