### ISSUE TITLE
Any plans to support Delve debugger?

### ISSUE THREAD

**Issue by jamiefoster** [visualfc/liteide#412]
Hi there,

Are there any plans to support the Delve debugger -> https://github.com/derekparker/delve/ ?

Here is a related discussion:

https://github.com/derekparker/delve/issues/22

**Comment by visualfc** [comment]
add delve support
https://github.com/visualfc/liteide/commit/3094d8c4251a666e29c86c79350747a6ba4b0322

**Comment by ycj** [comment]
what's the time?
