### ISSUE TITLE
Install fail Ubuntu 14.10

### ISSUE THREAD

**Issue by jasonrichardsmith** [visualfc/liteide#415]
the update_pkg.sh script fails on go tools

I run the go get for gotools alone and I get this:
``` 
go get -v -u -ldflags "-s" "github.com/visualfc/gotools"
github.com/visualfc/gotools (download)
golang.org/x/tools (download)
github.com/visualfc/gotools/pkgs
# github.com/visualfc/gotools/pkgs
../../go/src/github.com/visualfc/gotools/pkgs/pkgs.go:193: pp.MFiles undefined (type *build.Package has no field or method MFiles)
```

**Comment by clintonmasters** [comment]
Had  same issue with *gotools* not building on Ubuntu 14.10.
Downloaded the binary package from http://sourceforge.net/projects/liteide/.
Copied *gotools* from that package into the *build/liteide/bin* directory.

Then followed procedure https://github.com/visualfc/liteide/blob/master/liteidex/deploy/welcome/en/guide.md
on removing the "-i" from BUILDARGS to use go 1.2.
