### ISSUE TITLE
Feature request: QML plugin

### ISSUE THREAD

**Issue by neclepsio** [visualfc/liteide#417]
I'd like very much a plugin for QML files, with syntax highlighting, code folding and auto indentation on save (to be coherent with go).
I think I'm not the only one: go-qml repository has >1200 stars.

Thank you

**Comment by emicklei** [comment]
As part of the KDE project, there is a [Kate file](https://projects.kde.org/projects/kde/applications/kate/repository/revisions/fca6931028a445522338ec954c35536cd61e36ed/entry/part/syntax/data/qml.xml) which you can put in your Resources folder (mine is at /Users/ernest/go/liteidex23.1.macosx/LiteIDE.app/Contents/Resources/liteeditor/kate ). This is how I got support for protobuf.

**Comment by neclepsio** [comment]
Works great! Thank you!

Auto indentation is still missing, but syntax highlight and code folding is here.
