### ISSUE TITLE
Problem with Unicode 0x2B1F

### ISSUE THREAD

**Issue by neclepsio** [visualfc/liteide#418]
I have a problem with a file containing several Unicode symbols. In particular, it seems fairly repetitive that the symbol 0x2B1F (UTF-8: 0xE2 0xAC 0x9F) gets replaced by a dot and subsequent save fail with message:

`13:39:28 Editor: Failed to save /path/to/file.go`

The only solution I found right now is to delete the file and paste its content into a new file, using another editor. Changing the position of this symbol into the string seems to not help.

After escaping it, I had no problem.

**Comment by visualfc** [comment]
fix it

**Comment by neclepsio** [comment]
Thanks
