### ISSUE TITLE
Replace doesn't work as expected when "Match Case" isn't selected.

### ISSUE THREAD

**Issue by Zilog8** [visualfc/liteide#419]
What happens:
When doing Replace (Ctrl-H), if "Match Case" is NOT selected, Find works as expected but Replace only works if the item DOES match case.

What should happen:
When doing Replace (Ctrl-H), if "Match Case" is NOT selected, Replace should work ( as long as the item selected matches, ignoring case).
![clipboard02](https://cloud.githubusercontent.com/assets/218071/6840033/2560c1fc-d348-11e4-8638-25872d40283b.png)

**Comment by visualfc** [comment]
fix it

**Comment by Zilog8** [comment]
Thank you :-)
