### ISSUE TITLE
invalid use of incomplete type ‘class QTextDocument’

### ISSUE THREAD

**Issue by pierrre** [visualfc/liteide#433]
I'm trying to build LiteIDE from source:

./../../../liteidex/src/3rdparty/qtc_texteditor/basetextblockselection.cpp: In member function ‘void TextEditor::BaseTextBlockSelection::moveAnchor(int, int)’:
../../../../liteidex/src/3rdparty/qtc_texteditor/basetextblockselection.cpp:57:64: erreur: invalid use of incomplete type ‘class QTextDocument’
     if (blockNumber >= 0 && blockNumber < firstBlock.document()->blockCount()) {
                                                                ^
In file included from /usr/include/qt/QtGui/qtextobject.h:38:0,
                 from /usr/include/qt/QtGui/QTextBlock:1,
                 from ../../../../liteidex/src/3rdparty/qtc_texteditor/tabsettings.h:40,
                 from ../../../../liteidex/src/3rdparty/qtc_texteditor/basetextblockselection.h:33,
                 from ../../../../liteidex/src/3rdparty/qtc_texteditor/basetextblockselection.cpp:30:
/usr/include/qt/QtGui/qtextformat.h:65:7: erreur: forward declaration of ‘class QTextDocument’
 class QTextDocument;
       ^
../../../../liteidex/src/3rdparty/qtc_texteditor/basetextblockselection.cpp:59:57: erreur: invalid use of incomplete type ‘class QTextDocument’
             firstBlock.setPosition(firstBlock.document()->findBlockByNumber(blockNumber).position());
                                                         ^
In file included from /usr/include/qt/QtGui/qtextobject.h:38:0,
                 from /usr/include/qt/QtGui/QTextBlock:1,
                 from ../../../../liteidex/src/3rdparty/qtc_texteditor/tabsettings.h:40,
                 from ../../../../liteidex/src/3rdparty/qtc_texteditor/basetextblockselection.h:33,
                 from ../../../../liteidex/src/3rdparty/qtc_texteditor/basetextblockselection.cpp:30:
/usr/include/qt/QtGui/qtextformat.h:65:7: erreur: forward declaration of ‘class QTextDocument’
 class QTextDocument;
       ^
../../../../liteidex/src/3rdparty/qtc_texteditor/basetextblockselection.cpp:65:56: erreur: invalid use of incomplete type ‘class QTextDocument’
             lastBlock.setPosition(firstBlock.document()->findBlockByNumber(blockNumber).position());
                                                        ^
In file included from /usr/include/qt/QtGui/qtextobject.h:38:0,
                 from /usr/include/qt/QtGui/QTextBlock:1,
                 from ../../../../liteidex/src/3rdparty/qtc_texteditor/tabsettings.h:40,
                 from ../../../../liteidex/src/3rdparty/qtc_texteditor/basetextblockselection.h:33,
                 from ../../../../liteidex/src/3rdparty/qtc_texteditor/basetextblockselection.cpp:30:
/usr/include/qt/QtGui/qtextformat.h:65:7: erreur: forward declaration of ‘class QTextDocument’
 class QTextDocument;

**Comment by NHOrus** [comment]
Same  error, confirming.

**Comment by visualfc** [comment]
fix it
