### ISSUE TITLE
Mouse navigation on TABS cannot be disabled

### ISSUE THREAD

**Issue by composer22** [visualfc/liteide#434]
OSX:

Disabling mouse navigation doesn't stop the pesky tab navigation.
1) goto preferences/liteeditor/
2)) disable scroll wheel zooming and apply.
3) goto preferences/golangedit/
4) uncheck enable mouse navigation and apply.
5) save again.
6) restart LiteIDE
4) open some files in a project.
5) hover your mouse over an inactive tab of a file (actually using mouse sideways finger swipe does this).

Expected behavior:

Hovered file should not be brought to focus.

Observed behavior:

Hovered file is brought to focus.

NOTE:

This is driving me absolutely batty as a developer.  I've disabled navigation in OS X preference/mouse as well as LITEIDE and it is still flickering all over the place.  Trying to edit a file is almost impossible.

**Comment by visualfc** [comment]
fix it, golangedit init option.

**Comment by composer22** [comment]
Wonderful!

When you get an OSX build for **v27.2** I'll check it out.

**Comment by composer22** [comment]
Checked out build v27.2 OSX.  Issue is still there. Mouse wheel is disabled on OSX Preferences and LiteIDE but tabs navigation is still enabled.

**Comment by visualfc** [comment]
liteidex27.2.1 add new option editor tabbar mouse whell navagition tabs

**Comment by composer22** [comment]
Option was under Preferences/**LiteApp**/

and it works under 27.2.1 QT4.  

Thank you very much for this feature.

There is a spelling english issue but I will file this under another bug:

The text reads:
"Enable mouse whell navigation on tabs"

Proper spelling and phrase should read:
"Enable mouse **while navigating** on tabs"
