### ISSUE TITLE
kate syntax file go.xml no effect after x23.2

### ISSUE THREAD

**Issue by xiofen** [visualfc/liteide#437]
(follow on to issue436)

the file in \liteide\share\liteide\liteeditor\kate\go.xml doesn't seem to have effect after liteide x23.2

Simple example - deleting file causes all highlighting to dissappear in X23.2 .. but in X24.3 deleting the file has no effect

This seems to have stopped working between X23.2 and X24.3 (Win 32bit)

Must have been hardwired/compiled in?

**Comment by visualfc** [comment]
liteide golangedit plugin not use kate.

**Comment by xiofen** [comment]
\liteide\share\liteide\liteeditor\kate\go.xml is no longer in use then.

\liteide\share\liteide\liteeditor\color\colorhelp.md needs updating

BaseN, Float, and Symbol not working in current build

Is there a way to edit/modify syntax matching for .go files?
