### ISSUE TITLE
gofmt on save is broken

### ISSUE THREAD

**Issue by pierrre** [visualfc/liteide#439]
In LiteIDE 27.2, gofmt on save is broken.
There is an error message: gofmt: Timed out after 500ms when starting go code format.
It was working in 27.1.

If I use gofmt from the menu, it works.

If I increase the timeout in the settings, the error message is displayed instantly (without timeout).

If I use goimport instead of gofmt, it works.

**Comment by visualfc** [comment]
please check selected env and env setup

**Comment by silviucm** [comment]
hi, I can confirm I also have this bug
"gofmt: Timed out after 500ms when starting go code format" - every time a go file is saved. it doesn't get formatted
(windows 7, latest 27.2 after you fixed the windows explorer shell bug)

**Comment by pierrre** [comment]
My env config in LiteIDE:
```
GOROOT=$HOME/.gimme/versions/go1.4.2.src
GOPATH=$HOME/Go
PATH=$PATH:$GOROOT/bin:$GOPATH/bin
```

Result of `go env`:
```
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pierre/Go"
GORACE=""
GOROOT="/home/pierre/.gimme/versions/go1.4.2.src"
GOTOOLDIR="/home/pierre/.gimme/versions/go1.4.2.src/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

```
➜  ~  which go   
/home/pierre/.gimme/versions/go1.4.2.src/bin/go
➜  ~  which gofmt
/home/pierre/.gimme/versions/go1.4.2.src/bin/gofmt
```

**Comment by YouROK** [comment]
I also have this bug and change timeout to 500000000 ms, timeout not working
16:41:20 gofmt: Timed out after 500000000ms when starting go code format
16:41:21 gofmt: Timed out after 500000000ms when starting go code format

**Comment by oliverjanik** [comment]
Quick workaround until the new build is out:

Simply change the compilation target to something else and then back to your platform. The environment vars get reset and go fmt on save works ;-)

**Comment by Inflatablewoman** [comment]
This work around is inconsistent.  Anyone know of a better fix?

**Comment by geosoft1** [comment]
the solution is to set proper GOARCH in system.env or other selected env file.

**Comment by gosharplite** [comment]
Building liteide from source default system.env to "native compiler linux 386".
@visualfc has provided correct solution - "please check selected env and env setup".

**Comment by gitdlam** [comment]
Hi sorry having trouble understanding which environment variable i need to fix.  Some pointers appreciated.
My "go env" looks like this:
```go
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\git\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

**Comment by gosharplite** [comment]
Liteide menu -> view -> edit current environment
Check if there is difference between the open file match your go env.
Mine are shown below.
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tony/go/gopath"
GORACE=""
GOROOT="/home/tony/go/go"
GOTOOLDIR="/home/tony/go/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

system.env
```
# native compiler linux 386

#GOROOT=$HOME/go
#GOBIN=
#GOARCH=386
#GOOS=linux
#CGO_ENABLED=1

#PATH=$GOROOT/bin:$PATH

LITEIDE_GDB=gdb
LITEIDE_MAKE=make
LITEIDE_TERM=/usr/bin/gnome-terminal
LITEIDE_TERMARGS=
LITEIDE_EXEC=/usr/bin/xterm
LITEIDE_EXECOPT=-e

LITEIDE_SHELL=gnome-terminal;lxterminal;kconsole;xfce4-terminal;xterm
```

**Comment by gitdlam** [comment]
Thanks heaps @gosharplite that's perfect.

**Comment by cabinathor** [comment]
GOARCH="amd64"

**Comment by mpgerlek** [comment]
+1 @gosharplite

**Comment by Zamicol** [comment]
+1 @cabinathor Thanks, I just needed to add my GOARCH 

>16:45:12 gofmt: Timed out after 30000ms when starting go code format

**Comment by eniangwoe** [comment]
If you can't find a configuration problem or is not sure why,  try reinstalling the compiler
