### ISSUE TITLE
x27.2 crashes after right click on project folder and "Open Explorer Here"

### ISSUE THREAD

**Issue by silviucm** [visualfc/liteide#440]
Hello - I am on Windows 7

Just upgraded to X27.2 and whenever I right click on a project folder in the left tab (Folders tab) and choose "Open Explorer Here" - the Explorer window correctly opens to the destination folder, but LiteIDE crashes with the windows "debug or close the program" modal

The previous version was working perfectly

regards
silviu

**Comment by silviucm** [comment]
Additional note: qt4.8.7 appears functional. The problem appears to be with the qt5.4.7 version

**Comment by visualfc** [comment]
please download http://sourceforge.net/projects/liteide/files/X27.2/liteidex27.2.windows-qt5.4-patch.zip/download
or http://sourceforge.net/projects/liteide/files/X27.2/liteidex27.2.windows-qt5.4-1.7z/download
