### ISSUE TITLE
V27.2 OSX Build - Tab still shows close file name

### ISSUE THREAD

**Issue by composer22** [visualfc/liteide#441]
Launch app
Open a document.
Close it.
Tab still shows with a document name.

**Comment by visualfc** [comment]
fix it, please download liteidex27.2.1

**Comment by composer22** [comment]
Fixed in 27.2.1 QT4

closing.

**Comment by composer22** [comment]
Still broken under 27.2.1 **QT 5**  

QT 4 works.  Not sure if QT 5 should be official release as it appears unstable in a lot of areas.
