### ISSUE TITLE
liteide增加云配置

### ISSUE THREAD

**Issue by jiangyubao** [visualfc/liteide#445]
首先，需要liteide的开发者到https://mongolab.com/这个网站注册一个登录帐户，注册后它会免费赠送500MB的容量，然后就可以把liteide.ini存放在这个网站了。

按照每个用户liteide.ini文件压缩后3KB来计算，可以存储17万个用户的信息，差不多足够了。

这是一个mongodb的网站，所有操作都是基于http的mongodb的操作。

在上面可以建立一个名字User的表，包括如下字段：
{
   _id: "自增长id",
   usr: "帐户名字",
   pwd: "密码",
   int: "base64格式的liteide.ini",
   v: "版本信息，例如：liteidex27.2.windows-qt5.4-1"
}

**Comment by missdeer** [comment]
一个用户有多台不同系统不同配置的机器，这样就不行了

**Comment by visualfc** [comment]
暂时不会考虑
