### ISSUE TITLE
MacBookPro 双指点击问题

### ISSUE THREAD

**Issue by xxxcat** [visualfc/liteide#451]
在编辑器、侧拦和底部输出窗，双指点击触摸板的弹出菜单会马上关闭，如果猛烈短促点击可能会保持打开状态，虽然鼠标右击有相同的效果，但移动办公时颇为不便。
版本是X27.2.1-qt5

**Comment by vovkasm** [comment]
If google translate correct. And issue is "right click popup menu close immediately on MacOS X with touchpad". I can confirm the issue. But the issue disappeared after build liteide from sources with fresh Qt5.4.1
My environment:
* OS X 10.10.3 (MacBook Pro)
* Xcode 6.3.1
* Qt 5.4.1
* lightide from branch master on commit f5de5dcc0b77c184397e49d4e6d1c44044ee28a5

**Comment by xxxcat** [comment]
thank vovkasm. I solved it according to your method.
closing
