### ISSUE TITLE
Sidebar style becomes confused when same selection in different sidebar

### ISSUE THREAD

**Issue by xiofen** [visualfc/liteide#458]
(Occurring in Qt4 version Win8.1 32 bit, X27.2.1)

With style set to "side bar style" I select the same view (eg "folders") for multiple views - the app attempts to compensate by switching outputs - but the dropdown text does not match the display - see image for example - note all left sidebars show "folder" in dropdown text box, but each shows different contents.

![sidebar bug](https://cloud.githubusercontent.com/assets/11979606/7447081/80bdc066-f1e5-11e4-8e94-c8941307290c.png)

Dropdown text needs update, or other fix. Thanks.

**Comment by visualfc** [comment]
please download x35.1 and check.
