### ISSUE TITLE
Mac OSX 10.10.3版本中，liteide 27.2.1版本全屏下切换窗口会崩溃

### ISSUE THREAD

**Issue by LYY** [visualfc/liteide#463]
打开ide后，点击全屏，然后切换到其他窗口中，liteide就会崩溃，崩溃log可以看这个[gist](https://gist.github.com/LYY/7b93368f224a5171b6fd)。

**Comment by jamiefoster** [comment]
Another crash on OSX 10.10.3 here: https://gist.github.com/jamiefoster/d15dcd4e81143c6bfceb#file-liteide-crash-osx-10-10-3

**Comment by 5dao** [comment]
我的window也遇到这个问题了，看你的go版本是那一个，1.4.2版本应该可以，旧版本的go和liteedit27好像搭配不好

**Comment by LYY** [comment]
刚试了下，在go 1.4.2版本上没问题

**Comment by DSpeichert** [comment]
Same here, crashes frequently on random occasions.
