### ISSUE TITLE
The  "Jump to declaration" function only works for Go built-in packages

### ISSUE THREAD

**Issue by NanXiao** [visualfc/liteide#464]
I have downloaded the newest `X27.2.1` version of windows. I find the "`Jump to declaration`" function only works OK on `Go` built-in packages(such as `OS`, `strings`, etc), but not for other packages from project.   

Could you comment on this issue? Thanks in advance!

**Comment by visualfc** [comment]
please setup GOPATH and project in GOPATH/src/proj
