### ISSUE TITLE
代码跳转返回时,位置不准确

### ISSUE THREAD

**Issue by meilihao** [visualfc/liteide#467]
代码跳转返回时,发现返回后的位置不准确,有时返回到起跳点所在函数的定义附近,有时返回到了上上次的起跳点.

建议:

起跳前,liteide记录起跳点A(文件路径,所在行数),返回时,liteide返回到起跳点A.

version : x27.2.1

**Comment by visualfc** [comment]
please check latest version

**Comment by shenyan008** [comment]
我也有这样的问题，版本已经是32.2了
