### ISSUE TITLE
import cycle时使用"跳转到声明"会导致电脑卡死

### ISSUE THREAD

**Issue by meilihao** [visualfc/liteide#470]
今天项目中偶然出现import cycle,再使用"跳转到声明"时,发现系统中出现了两个gotools进程,其CPU占用率在100左右,导致电脑无响应.

ps:
ubuntu 15.04,x64
liteide 27.2.1

**Comment by visualfc** [comment]
please download liteide x28

**Comment by visualfc** [comment]
x28 fixed it
