### ISSUE TITLE
Brackets on german keyboard

### ISSUE THREAD

**Issue by repetier** [visualfc/liteide#478]
I really liked the IDE until I had to enter brackets on my german keyboard. On german keyboards (other maybe as well) it makes a difference if the left or right (we call it alt gr) is used. The right one creates special chars like brackets [] {} You switch some windows with alt+1-8 but there the german keyboard also has the brackets. They are on 5,6,7, 8,9,0 depending on os.

Would it be possible to put the shortcuts only on left alt or use a different key like ctrl? Without being able to enter these, I can not program and have to use other IDE also I liked this more.

**Comment by drathier** [comment]
Same on mac. I cannot write anything that requires the alt key, such as `@`. Please only use the left alt key for this feature to let non-english keyboard layouts use alt gr + number for typing. 

This applies to many european keyboard layouts, including German qwertz and Swedish qwerty.

Kinda same as #161.

**Comment by t-simply** [comment]
Hi, 

Same problem on azerty french layout. In fact "alt gr" is a shortcut for "ctrl + alt" and since version 27 (not in version 26) of liteide, ctrl + alt + [1,2,3,4,5] display or hide left panel. In azerty french mapping like probably german keyboard or other european ones, to type "{}[]", we must use "alt gr" + [4,5] so it's impossible to use this version for the moment.

Workaround : use version 26.

**Comment by t-simply** [comment]
Hi, 

I confirm that's it is impossible to use version 27 (french layout) but, for workaround, the problem is not present in version 26.

**Comment by shyrobbiani** [comment]
While I have no issues with the brackets on a Swiss German keyboard I can confirm this for the @ sign which is on alt gr + 2. However it's easy to change that in the View->Options->LiteApp->Keyboard settings.

**Comment by SR-G** [comment]
Same problem with LiteIDE version 28 (french layout), i can't anymore enter [ or { with ALT-GR 4 or 5 (while this was working on LiteiDE v24).

**Comment by visualfc** [comment]
please download x35.1 and check.
