### ISSUE TITLE
font size 为什么没有13px这样的奇数大小呢？

### ISSUE THREAD

**Issue by yx91490** [visualfc/liteide#479]
liteIDE很好用，但是我用12px字体太小，14px又有点大，为什么没有13px这样的奇数大小呢？希望能添加一下谢谢

**Comment by visualfc** [comment]
option - liteeditor - font
调整zoom

**Comment by visualfc** [comment]
字体的大小列表是通过 QFontDatabase::pointSizes(familyName) 获取的，跟系统和字体相关，可以通过Zoom再调整。
