### ISSUE TITLE
同时编辑go和rs源文件程序闪退

### ISSUE THREAD

**Issue by dalater** [visualfc/liteide#484]
现象：启动程序后，首先打开任意go源文件，然后关闭源文件；之后在[File System]视图中，通过点击[向上目录选择]按钮找到rust项目目录，打开其中任意一个rust源文件，程序闪退，

版本：x27.2.1
环境：Debian Linux 8.1
通过命令行启动，提示[Segmentation fault]，

**Comment by visualfc** [comment]
please download x35.1 and check.
