### ISSUE TITLE
Close project folder bug

### ISSUE THREAD

**Issue by matwachich** [visualfc/liteide#489]
On version X27.2.1, when there are many open projects folders (say 3 folders), if you close the 2nd folder, then the 3rd (that becomes the 2nd) won't close.

**Comment by mauleyzaola** [comment]
I have the same problem. It happens randomly. Version X27.2.1 ubuntu 14.04.3

**Comment by visualfc** [comment]
fix it https://github.com/visualfc/liteide/commit/7204e5d1013efb83f41438c7335a0c8c7af797e8
