### ISSUE TITLE
需求：代码窗口与目录窗口同步

### ISSUE THREAD

**Issue by ljf10000** [visualfc/liteide#490]
平台：windows
版本：X27.2.1
需求：目录窗口中，双击一个文件A，会在代码窗口中打开这个文件A；此时目录窗口文件A为选中状态，代码窗口中文件A为激活状态，这种行为是符合用户预期的。
但是，如果在代码窗口选择文件B，此时代码窗口中文件B变为激活状态，而目录窗口中文件A仍然为选中状态，这种行为是不符合用户习惯的（目录窗口中应该文件B变为选中状态），两个窗口应该同步。

**Comment by visualfc** [comment]
please download liteide x28

**Comment by ljf10000** [comment]
现在是X30.3，还是有这个问题
