### ISSUE TITLE
liteide win7调试 变量值错误

### ISSUE THREAD

**Issue by cyflhn** [visualfc/liteide#493]
我使用liteide27.2 go1.3.3版本 win7 64位环境，调试go语言程序，查看局部变量值，变量值显示不正确，如int型数值显示乱七八糟的数字，字符串显示乱七八糟的字符串。但是，程序直接运行是正常的，通过日志打印方式能正常打印变量值。请问怎么回事，谢谢。

**Comment by visualfc** [comment]
x29改进了调试器，支持delve，请下载并测试。
