### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by pm-kartik-sura** [visualfc/liteide#496]
There has not been any noise since sometime.

Looking forward for the next release :)

**Comment by flike** [comment]
+1

**Comment by CuriousCain** [comment]
+1

**Comment by ramigg** [comment]
+1

**Comment by 4ur3l13n** [comment]
seems the author does not git anything from month (on all github)

**Comment by dvirsky** [comment]
The project's author hasn't had any github activity in 4 months, I tried the project's google group as well but no response. To be honest I'm a bit worried and hope he/she is okay. An abandoned project usually fizzles out over a time period. Going from a fast development pace to total radio silence in every medium is something I've never seen.

**Comment by matrixik** [comment]
Don't forget that LiteIde is a side project of @visualfc and he is working on it when he have time **and** desire for it.

**Comment by dvirsky** [comment]
@matrixik it's odd for someone to completely disappear from the internet all of the sudden, not commit anything to any git repo, not answer personal emails or newsgroup threads, etc.

**Comment by flike** [comment]
I hope anyone can't continue this project.

**Comment by matrixik** [comment]
It's not odd for visualfc, he already did that few times before.

**Comment by dvirsky** [comment]
@matrixik I hope you're right, this is a great project and I'd hate to see it die

**Comment by CuriousCain** [comment]
I've tried to pick the project up but can't get it to run correctly on my system for some reason. For example, some dialogs just won't open but there will be no error and no debug log.
Possibly an issue with the version of QT I'm using, but not entirely sure. I'll be taking a further look into it, though, no doubt.

**Comment by pm-kartik-sura** [comment]
@CuriousCain As you are already at it, can you please document the steps to get it up? Maybe we all can start working on some fancy features (which made eclipse cool)

**Comment by dvirsky** [comment]
@CuriousCain @pm-kartik-sura I have no problem building it on my machine (ubuntu 14.04) and I even had a fork with some better icons. But I couldn't get QtCreator to properly build it, so hacking on it without an IDE just seems too much trouble and I gave up. I believe visualfc develops it with Visual Studio.

**Comment by CuriousCain** [comment]
@dvirsky Yes, that's exactly my issue. I can build it from the command line, but QtCreator doesn't quite do it correctly OOTB. I might attempt to get it going in Visual Studio. If not, I'll try and hack around with the QtCreator build settings to get it working.

**Comment by CuriousCain** [comment]
Alright, so the main problem is that when debugging; it looks for files in the liteidex's "share" directory, which just aren't there. If you copy them over from the deployable build or downloadable release: it will work (so far) just as the release will.

I'm not sure, however, if they're supposed to be created and put there on build and something is just going wrong. Maybe they should be in the user's AppData anyway, instead of local to the directory?

**Comment by Ho3ein-Boka** [comment]
actually I'm worry too . i sent email to visualfc but did not receive any response yet .

**Comment by CuriousCain** [comment]
Has any been able to make any progress on getting this to build and run correctly?

**Comment by dvirsky** [comment]
There's been a commit to another project by visualfc a few days ago, so at least we know he/she is okay, probably just busy with other stuff. https://github.com/visualfc/support/commit/4a78a773abc7b059a0d11c2c250ca06a484f49d6

**Comment by pm-kartik-sura** [comment]
Lol visualfc would be the most stalked GitHub user :v:

**Comment by vovkasm** [comment]
@CuriousCain, I just successfully configure QtCreator on Mac to debug LiteIDE (grrr... and seems to fix crash with autocomplete https://github.com/vovkasm/liteide/commit/9e0e1345c06e996bc548e63245df352bd7fd76b5)

So if anyone needs step-by-step guide to debug LiteIDE on Mac, there my steps:
 1. run `build/build_osx_clang.sh` (fail to build, but now I have `gocode` and `gotools` in `liteidex/bin` directory)
 1. Open `liteidex/liteidex.pro` in QtCreator (select Qt5.5, but I cherry picked fix from @missdeer  https://github.com/vovkasm/liteide/commit/6bfc93ce5aa957d175bcac211eaf847db9a7d35b )
 1. Build (not Run!) the project.
 1. Copy files to bundle (`$WC` = working copy)
 ```
cp -R $WC/liteidex/bin/* $WC/liteidex/liteide/bin/LiteIDE.app/Contents/MacOS/
cp -R $WC/liteidex/deploy/* $WC/liteidex/liteide/bin/LiteIDE.app/Contents/Resources/
cp -R $WC/liteidex/os_deploy/macosx/* $WC/liteidex/liteide/bin/LiteIDE.app/Contents/Resources/
 ```
 1. Go to `Projects` -> `Run` tab -> `Run environment` in QtCreator and set `GOPATH`
 1. Now I can run and debug LiteIDE ;-)

**Comment by CuriousCain** [comment]
@vovkasm That's awesome. It works part way on my windows machine.

The problem is that it doesn't detect gofmt, even with your fix, unless I put their binaries in the LiteIde bin folder.
It still says they're undetected, but they are actually run and the timeout jumps from 500ms (before copying) to 2000ms. This only happens if the file has errors in it; otherwise it  doesn't timeout.

I also get this (after copying go binaries):
 go code format error: computing diff: exit status -1073741515
