### ISSUE TITLE
关闭目录，每次只能关闭一个。

### ISSUE THREAD

**Issue by freshcn** [visualfc/liteide#499]
我是mac版的环境，我现在每次关闭目录的时候，只能关闭一个之后的就不能再关闭了。必须要重新启动后才能再一次的关闭。

**Comment by missdeer** [comment]
我也遇到了

**Comment by visualfc** [comment]
fix it https://github.com/visualfc/liteide/commit/7204e5d1013efb83f41438c7335a0c8c7af797e8
