### ISSUE TITLE
使用goimport代码格式化无效

### ISSUE THREAD

**Issue by defia** [visualfc/liteide#507]
找了半天也找不到什么原因,保存时格式化/手动点击菜单中的格式化(调整导入行也无效)
有什么可以解决,或者找到问题出在哪里的方法么?
我整个解压了一个liteide的副本也不行...不过gopath还是老的那个

**Comment by defia** [comment]
又莫名其妙有效了...简直诡异

**Comment by lutzhorn** [comment]
Translation to English:

> Looking for a long time could not find any reason, formatting / manually click menu format when you save (adjust the import line are invalid)
What can solve the problem or find a method where it?
I unpacked a whole nor liteide copy or old ... but that gopath

**Comment by defia** [comment]
@lutzhorn lol
basically i mean fmt code by goimport does not work at all，neither by format code on save nor by click format code and modify import in menu. 
even i extract a totally new copy of liteide folder anf run ,it does not work either.

and i want some advice to solve the issue.

but the issue disappeard now and i dont know why.

**Comment by lutzhorn** [comment]
If the issue dissapeared you can close this GitHub issue.

**Comment by defia** [comment]
@lutzhorn i think this is definitely a issue, cause it happened sometimes in the past (but usually it will work again if you restart liteide). and i dont think it will disappear forever in the future. i'm asking for some advice to help someone look into the issue when it comes again.

**Comment by visualfc** [comment]
please download liteide x28

**Comment by dalu** [comment]
archlinux
liteide x28
case 1:
go-tools package not installed, but goimports present:
ctrl alt i = works, no problems
saving with ctrl s does nothing

case 2:
go-tools package installed:
ctrl alt i = removes all but std packages from imports
same with ctrl s

**Comment by visualfc** [comment]
please update to latest version
