### ISSUE TITLE
I want to change the way liteide builds from a whole directory\project to a singe opnened file.

### ISSUE THREAD

**Issue by elico** [visualfc/liteide#508]
I understood that I need to change something in this line to make liteide build only a single file which I am working on, am I right? if so what argument?
        <action id="Build" img="blue/build.png" key="Ctrl+B;F7" cmd="$(GO)" args="build $(BUILDARGS)" save="all" output="true" codec="" regex="$(ERRREGEX)" navigate="true"/>

**Comment by syncore** [comment]
Build -> Build Configuration -> Custom -> then set BUILDARGS to: -i $(EDITOR_FILE_PATH)
