### ISSUE TITLE
调试部分是不是可以考虑用delv了？

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [visualfc/liteide#509]
如题，dlv在mac和linux的命令行下测试可用，不知道是不是可以考虑加到liteide里面？

**Comment by 88250** [comment]
Wide 也有这个[打算](https://github.com/b3log/wide/issues/8) :smile:

**Comment by visualfc** [comment]
fix it
https://github.com/visualfc/liteide/commit/db60805dfc68853bdc2e76635fc293480f69a3d1
