### ISSUE TITLE
Mac Build/Make Error

### ISSUE THREAD

**Issue by macjabeth** [visualfc/liteide#510]
During the build process, I ran into this error:

> In file included from ../../../../liteidex/src/utils/colorstyle/colorstyle.cpp:24:
> ../../../../liteidex/src/utils/colorstyle/colorstyle.h:84:15: error: unknown type name 'QIODevice'
>     bool load(QIODevice _dev, const QString &fileName);
>               ^
> ../../../../liteidex/src/utils/colorstyle/colorstyle.cpp:66:12: error: no matching member function
>       for call to 'load'
>     return load(&file,fileName);
>            ^~~~
> ../../../../liteidex/src/utils/colorstyle/colorstyle.h:84:10: note: candidate function not viable: no
>       known conversion from 'QFile *' to 'int *' for 1st argument
>     bool load(QIODevice *dev, const QString &fileName);
>          ^
> ../../../../liteidex/src/utils/colorstyle/colorstyle.cpp:59:24: note: candidate function not viable:
>       requires single argument 'fileName', but 2 arguments were provided
> bool ColorStyleScheme::load(const QString &fileName)
>                        ^
> ../../../../liteidex/src/utils/colorstyle/colorstyle.cpp:69:24: error: out-of-line definition of
>       'load' does not match any declaration in 'ColorStyleScheme'
> bool ColorStyleScheme::load(QIODevice *dev, const QString &/_fileName_/)
>                        ^~~~
> 3 errors generated.
> make[3]: *_\* [.obj/release-shared/colorstyle.o] Error 1
> make[2]: **\* [sub-colorstyle-make_first-ordered] Error 2
> make[1]: **\* [sub-utils-make_first-ordered] Error 2
> make: **\* [sub-src-make_first-ordered] Error 2
> error, make fail

**Comment by vovkasm** [comment]
This was fixed in these forks:
1. By @missdeer : https://github.com/missdeer/liteide/commit/08e7592540fe9afbb3d1d56a88f7aa347b7dc613
2. By @embroker : https://github.com/embroker/liteide/commit/1eff2b9ba1da6a3227ff8e493ab17ea7df23b621
3. I'am also incorporate fix from 1. https://github.com/vovkasm/liteide/commit/6bfc93ce5aa957d175bcac211eaf847db9a7d35b
