### ISSUE TITLE
是否考虑增加如下功能

### ISSUE THREAD

**Issue by ccvcd** [visualfc/liteide#512]
首先感谢visualfc提供的强大易用的liteid编辑器
再使用过程中发现有几点还可以再加强
1.代码重构功能，现在提供的重构功能比较简单
   代码重构应用情况
  1)修改文件夹名字，目前没有自动修改go源文件中的package名称
  2)go源文件无法进行夸目录拖拽，希望支持拖拽移动目录，同时自动完成重构操作
2.由其他go源文件导航进入其他go源文件，希望增加右键功能显示当前go源文件在导航目录中自动选中（多级目录情况下，自动展开），这样方便查看当前go源文件所在包的情况，
3.目录导航刷新目前只能在跟目录选中重新加载，希望在其他子节点也可以进行刷新
4.断点设置目前只能通过F9快捷键进行设置或取消，希望能够双击所在行的左侧行号区域也能操作
再次对visualfc表示感谢。

**Comment by shawnye** [comment]
咨询一下，有没有自动完成的模版可以设置，比如说： 输入fori可以自动完成 ：
<code>
for i := 0; i < 10; i++ {
    
} </code>

forr可以自动完成:<code>
for _, value := range array {
     
} </code>

**Comment by visualfc** [comment]
目前只实现了一些非常简单的snippet功能，参考下面
liteide\share\liteide\packages\go\*.snippet.json

2016-01-08 10:33 GMT+08:00 Shawn Ye <notifications@github.com>:

**Comment by shawnye** [comment]
这些对我就够用了,谢谢!

2016-01-12 8:35 GMT+08:00 visualfc <notifications@github.com>:
