### ISSUE TITLE
在mac下，jump back的快捷键是什么？

### ISSUE THREAD

**Issue by wangxiangyu** [visualfc/liteide#518]
hi，
跳到定义的地方后，如果想跳回去，在mac下的快捷键是什么呢？谢谢

**Comment by chang290** [comment]
我也想问这个问题，没有跳到前一个鼠标位置的快捷键？

**Comment by chang290** [comment]
我已经找到了，LiteIDE菜单 -> Preferences -> LiteApp -> 键盘
就在App那个地方有两个快捷键分别是：Backward返回  与  Forward前进  默认是Ctrl + Alt + Left/Right
不好使，我将其修改成了 Ctrl [/] 这样就和Eclipse一致了。
但是Ctrl[/]这两个已经被 Editor中的，移动光标到上一段与下一段使用，由于这两个快捷键没啥用，我就将其设置成Ctrl + Alt + Left/Right，相当于互换。
