### ISSUE TITLE
OSX 10.11.1 LiteIDE go playground 进程无法启动

### ISSUE THREAD

**Issue by yibin001** [visualfc/liteide#522]
![Image of Yaktocat](http://i.imgur.com/AVjdGv6.jpg)

go version 1.4.2

liteide X27.2.1

是哪里有问题么？

**Comment by choleraehyq** [comment]
你看一下你的env设置，可能有问题。

**Comment by yibin001** [comment]
@choleraehyq 

这是system.env的内容
 
 GOROOT=/usr/local/go
#GOBIN=
#GOARCH=amd64
#GOOS=darwin
#CGO_ENABLED=1
#GO15VENDOREXPERIMENT=1
#PATH=$GOROOT/bin:$PATH
LITEIDE_GDB=/usr/local/bin/gdb
LITEIDE_MAKE=make
LITEIDE_TERM=/usr/bin/open
LITEIDE_TERMARGS=-a Terminal
LITEIDE_EXEC=/usr/X11R6/bin/xterm
LITEIDE_EXECOPT=-e


go env也正确设置了gopath。

但playground还是无法启动。
