### ISSUE TITLE
Cross-compiling OS X binaries from Windows

### ISSUE THREAD

**Issue by amazedevil** [visualfc/liteide#525]
I've tried to use "cross-darwin64" configuration on windows, and it gave me binary file, which I can't run on OS X (El Capitan), because it says: "You can't open the application "my_app_name" because powerpc applications are no longer supported".

Command:

C:/go/bin/go.exe env [c:\go]
set GOARCH=amd64
set GOBIN=
set GOEXE=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=darwin
set GOPATH=C:\Users\User\go\;C:\LiteIDE\bin\
set GORACE=
set GOROOT=c:\go
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=
set CC=gcc
set GOGCCFLAGS=-fPIC -m64 -fmessage-length=0 -fno-common
set CXX=g++
set CGO_ENABLED=0

**Comment by visualfc** [comment]
https://github.com/visualfc/liteide/blob/master/liteidex/deploy/welcome/en/guide.md
