### ISSUE TITLE
终于又更新了，还以为作者放弃这个IDE啦。

### ISSUE THREAD

**Issue by shesuyo** [visualfc/liteide#527]
给力。

**Comment by vovkasm** [comment]
How to translate this to english? ;-)

**Comment by shesuyo** [comment]
Waitting a long time for update.
I thought author throw this away before this update.
Tanks God.He comes back whih new version.
I love this IDE very much.
Hope the IDE will be better.

**Comment by vovkasm** [comment]
Thank you, very much! Google Translate wasn't able to translate this adequately.
