### ISSUE TITLE
GO15VENDOREXPERIMENT

### ISSUE THREAD

**Issue by donseba** [visualfc/liteide#531]
While enabling the option GO15VENDOREXPERIMENT I've noticed that 
some basic functionality was not working correctly anymore. Like code completion and jump to declaration.

I have made an fork of https://github.com/visualfc/gotools here : https://github.com/donseba/gotools . 

Simply download and build the tool. and place them in the `liteide/bin` folder.

**Comment by donseba** [comment]
worth nothing is that LiteIDE is bundled with an outdated version of [gocode](https://github.com/nsf/gocode). 

I'd advise everyone to remove gocode from the liteide/bin folder and build it from source. 
It has some important updates regarding GO15VENDOREXPERIMENT . 

So : `go get -u  github.com/nsf/gocode` . 
There is no need to place it back into the liteIDE bin folder as long as the GOBIN flag is set correctly

**Comment by visualfc** [comment]
gotools now support go1.5 vendor 
https://github.com/visualfc/gotools
