### ISSUE TITLE
Cannot change font size in source editor

### ISSUE THREAD

**Issue by slinky66** [visualfc/liteide#532]
On my Mac running 10.10.5, the font size in the editor got really small, so small it cannot be read.
Using Control -> + does not have any effect on this. I restarted as well. No effect.

<img width="571" alt="liteide" src="https://cloud.githubusercontent.com/assets/1904465/11470992/13a3b3fa-9730-11e5-8ccd-9b0881183ca2.png">

**Comment by visualfc** [comment]
option -> liteedit -> font setup.

**Comment by zrml** [comment]
I must be blind (X27.2.1) but I cannot see the "option" :-(
I'm on OSX 10.11.6

Missing a std [Ctrl +] [Ctrl -] option shouldn't we have an option in the VIEW menu? It seems to scream for this option right there to me :-)

Thank you guys for the awesome work!

**Comment by zrml** [comment]
OK, found it :)
For posteroty:
on OSX, hit LiteIDE Menu, the Preferences,
then select LiteEditor option from left hand pane list,
then Fonts & Colors tab (the first one) -> Adjust the size and Apply.
--
