### ISSUE TITLE
KDE terminal doesn't open; is 'konsole', env refers to 'kconsole'

### ISSUE THREAD

**Issue by smileytom** [visualfc/liteide#541]
On KDE systems the default terminal application is called 'konsole' but the .env files include this line:

LITEIDE_SHELL=gnome-terminal;lxterminal;kconsole;xfce4-terminal;xterm

As a result the terminal that opens is xterm.

Changing the name in the variable above to 'konsole' opens the correct terminal and resolves this issue.

**Comment by smileytom** [comment]
See PR #542

**Comment by visualfc** [comment]
thnaks

**Comment by visualfc** [comment]
thanks

**Comment by b-s-a** [comment]
Please add x-terminal-emulator and xdg-terminal at front of list. They are commonly used wrappers for terminal emulators preffered by user. For example, I'm using Ubuntu MATE and I have no any of listed terminals installed, so try to launch terminal silently causes nothing. My native terminal is called mate-terminal. But it can be lauched directly or via x-terminal-emulator wrapper (it is common for Debian based distributions).
