### ISSUE TITLE
LiteIDE not usable on south-east/central European keyboards

### ISSUE THREAD

**Issue by matadin** [visualfc/liteide#544]
I am having problems with using LiteIDE on Croatian (South Slavic Latin) keyboard (I have installed liteidex28.windows-qt4 files on Windows XP). I can not write opening brace (curly bracket, "{") in the editor, because on South Slavic Latin keyboard in order to write opening brace, you press AltGr - B keys (same as Crtl - Alt - B). Unfortunately this is key shortcut for ForceBuild command (in menu Build - ForceBuild) .  So it happens that it is impossible to write code on keyboards in Bosnia, Croatia, Serbia, Slovenia, and as I found in [QWERTZ](https://en.wikipedia.org/wiki/QWERTZ) article on Wikipedia also in Hungary, Slovakia and Czech Republic.

Since keyboard shortcuts are not customizable, as far as I know, I would recommend to remove assigning of  Crtl - Alt - B to ForceBuild command, so that LiteIDE could be used also on South Slavic Latin keyboards.

If proposed change is accepted, it would be nice if somebody could build new binaries and post it on [sourceforge](http://sourceforge.net/projects/liteide/files/) , since I do not have much skill in compiling c++ programms.

**Comment by visualfc** [comment]
modify build config key.
liteide - option - litebuild - gosrc.xml edit and restart liteide.
```
<action id="Build" img="blue/build.png" key="Ctrl+B;F7" cmd="$(GO)" args="build $(BUILDARGS)" save="all" output="true" codec="utf-8" regex="$(ERRREGEX)" navigate="true"/>
```

**Comment by matadin** [comment]
Thank you, this solved my problem.
On windows it is file  `\liteide\share\liteide\litebuild\gosrc.xml `.
I changed the line:
`<action id="ForceBuild" img="blue/rebuild.png" menu="Build" key="Ctrl+Alt+B" cmd="$(GO)" args="build $(FORCEBUILDARGS)" save="all" output="true" codec="utf-8" regex="$(ERRREGEX)" navigate="true"/>`
so that I deleted `key="Ctrl+Alt+B"` part from it.
