### ISSUE TITLE
编译输出窗口定位问题

### ISSUE THREAD

**Issue by linlexing** [visualfc/liteide#547]
当编译窗口中结果很多时，用滚动条定位信息后，想用鼠标点击，结果一点击，光标就跳到末尾，又得重新定位。

而且即使用键盘对光标进行移动，只要鼠标点其他窗口后再点回来，又是末尾，顿时让整个人都不好了。

**Comment by visualfc** [comment]
请提供操作系统和liteide的版本

编译输出窗口上的设置按下后有自动清除选项可以使用.

**Comment by linlexing** [comment]
win7 64bit ,liteide X28

**Comment by visualfc** [comment]
不是太理解，能否截图加以说明，附加一个简单的例子代码。

**Comment by linlexing** [comment]
如图：
![-1](https://cloud.githubusercontent.com/assets/834303/14447602/dec6fa02-0093-11e6-8692-7e056f99c96b.png)
就是在1处点击鼠标后，光标在nil后面跳到，这时再点击2处，把焦点移到代码编辑窗口，然后再在1处点击，结果光标却在末行的末尾跳动，如果是很长的编译输出，好不容易定位了错误信息，结果一弄就最后，太难受了。

我感觉是编译输出小窗口的focus事件中是不是做了什么操作

**Comment by visualfc** [comment]
明白了，这不是编译输出。
而是编译后应用程序运行时，输出窗口会自动定位到最后以接受人工输入，所以会自动定位到最后以接受输入，应该可以看到最后的光标位置，类似于cmd窗口的设置。

**Comment by visualfc** [comment]
默认已关闭这一行为
https://github.com/visualfc/liteide/commit/01e63fc254f6c85893707d2f747b3faf45e0e4c8

**Comment by visualfc** [comment]
x29 的编译输出窗口上有选项可以控制这一行为，默认为自动定位。

**Comment by linlexing** [comment]
@visualfc 
新功能我试过了，还是有问题，我把 **自动定位光标** 选项去除，如果输出结果很多，向上翻页了，再切换回来，自动会滚屏到最后一页，光标倒是不会跳到最后了
