### ISSUE TITLE
The tooltip layer blink when it’s too long to display in screen

### ISSUE THREAD

**Issue by applee** [visualfc/liteide#548]
ENV: OS X 10.11, version X28
The tooltip layer blinks when I press the command key ⌘ for it’s too long to display in screen.It's always re-rendering so that I can't click the left mouse button to jump to the definition.

**Comment by visualfc** [comment]
fix it 
https://github.com/visualfc/liteide/commit/f9b544242fd762bc4d43e72dbe738e842f996b12
