### ISSUE TITLE
x28版本跳转到声明功能异常

### ISSUE THREAD

**Issue by 1175498437** [visualfc/liteide#551]
错误日志（ 08:44:50 find def error: 进程退出代码 1）

**Comment by zoumi** [comment]
我的情况是:
当GO源文件的文件名包含空格的时候出现该异常.

**Comment by zoumi** [comment]
同一个文件gg.go
当目录里还有一个b.go的空白文件(大小为0KB)时也不能跳转到声明

**Comment by visualfc** [comment]
1.文件名包含空格已修复
https://github.com/visualfc/liteide/commit/8fe6f435bda82a8de6f7d11f656f875738ca2ab2

2.空白.go文件存在情况下go语法不通过,也无法编译.
