### ISSUE TITLE
Stepping into Google source with debugger doesn't sync with source

### ISSUE THREAD

**Issue by asampal** [visualfc/liteide#553]
I'm using Windows 10- 64 bit, LiteIDE X28

I'm trying to step through `net/rpc/server.go` and the call stack and variables seem to update as I step, but the editor doesn't reflect the line of execution. The line number reported by the debugger looks correct wrt the source, so I'm not sure what's stopping the editor from following the stepping.

I noticed the LiteIDE is using gdb version 7.7 - would a more up-to-date version fix this problem?

**Comment by visualfc** [comment]
please download x29
