### ISSUE TITLE
process failed to start.

### ISSUE THREAD

**Issue by zallwu** [visualfc/liteide#561]
When there are spaces in the folder name, click "Run", prompted "Error: process failed to start."

os x 10.11
liteide x28

**Comment by stonest** [comment]
I'm also experiencing this issue. Attempted to escape the spaces but didn't work.

**Comment by visualfc** [comment]
fix it
https://github.com/visualfc/liteide/commit/f328b48cb51bac78950b767e28e6b5576c6b50bf
change share/liteide/litebuild/gosrc.xml BUILD_DIR_GONAME to BUILD_DIR_NAME

**Comment by shageeth** [comment]
Hi @visualfc , i am also struggling with the same issue in windows ,could you help me on that ???

**Comment by visualfc** [comment]
space name don't include space
