### ISSUE TITLE
package name with dot "." is not working as expected in auto-completion

### ISSUE THREAD

**Issue by davyzhang** [visualfc/liteide#562]
I am not sure this is the issue of liteide or gocode

package like    "gopkg.in/mgo.v2"

struct under this package will displayed as "v2.Database" but it actually should be mgo.Database

**Comment by visualfc** [comment]
auto completion please install mgo pkg or project go get to build mgo .a pkg,
display error is fixed.
https://github.com/visualfc/gotools/commit/22bf1ae0782723a4408e438bfbbd251e802b029f
