### ISSUE TITLE
Search files within the open directories in IDE in Sublime Text fashion

### ISSUE THREAD

**Issue by mauleyzaola** [visualfc/liteide#568]
Hi @visualfc, I was looking into the issues couldn't find anything related with this. Note that this is just a nice-to-have request and I would like to help although I am not into C++

I use LiteIDE for everyday working, I am so used to it that when you all of the sudden disappeared months ago began looking for alternatives in the fear that this project was abandoned. Vim was the best match I found and also Sublime Text works almost good (except for the speed of the go-sublime plugin). 

Anyway using those two text editors I found myself missing a file search in LiteIDE. Sublime works absolutely great, just `CTRL+P` and you can search really fast without leaving the keyboard. Vim has similar shortcuts.

I don't know how much effort would be to get this feature working and maybe we could have input from another users and vote for it, hell even donate. I wouldn't mind paying for this tool, it makes my work very productive.

Hope this makes sense to anybody else too. Thanks.

**Comment by Vektah** [comment]
I agree! This IDE has everything I need, except this. 

A quick open file by name search is probably the easiest. Other editors also let you do things like jump to symbol by name, eg intellij (I think its ctrl+shift+N) looks like this:
![2016-02-25_1178x208](https://cloud.githubusercontent.com/assets/2247982/13311021/37f1ebfc-dbdf-11e5-9f40-5932bc8ac25d.png)

Also note it is doing some fuzzy matching.

**Comment by mauleyzaola** [comment]
@Vektah It looks like there is not a crow crazy for this feature :smile: 
Its a shame, that would make LiteIDE a lot powerful. By the way, I've just installed your Webstorm plugin and it totally rules!

**Comment by mauleyzaola** [comment]
As of version `X30.1-1` this feature is supported. Just need to `ctrl`+`p` like Sublime does and voila! instant quick open file.
Although I am not sure this feature already was there in previous versions. I just discovered when looking into options the `QuickOpen` section made me wonder...
![image](https://cloud.githubusercontent.com/assets/1648558/16698884/4adce0d2-4516-11e6-8e5e-e13e2f3afcd9.png)
