### ISSUE TITLE
Cannot type [ on a Mac OS French keyboard

### ISSUE THREAD

**Issue by echarlus** [visualfc/liteide#572]
When trying to type [ (alt-shift-5) on Mac OS X's French keyboard, the debug output pane is shown/hidden it appears as if the shift key is not taken into account since the debug pane visibility toggle is alt-5. 
This  prevents from entering the [ character which is pretty annoying ...

**Comment by vernichon** [comment]
Same problem with Windows or Linux and French Azerty Keybord for  ALT + CTRL + 4 for {

it's possible to desactive Shortcut ?

**Comment by matadin** [comment]
On windows, this helped me:
[issue #544](https://github.com/visualfc/liteide/issues/544)
Probably, you should look for gosrc.xml somewhere else, and edit it to remove association of key combination to debug pane visibility toggle.

**Comment by echarlus** [comment]
Hi,
thanks for the tip, unfortunately it did not help since I could not find any reference to this shortcut in the gosrc.xml file or in any other configuration file ... These shortcut are probably hardcoded. The only solution would be to change the source and rebuild everything I guess.

**Comment by visualfc** [comment]
fix it https://github.com/visualfc/liteide/commit/7182ee61ece3169d5ec63169d998576285da1fc1
