### ISSUE TITLE
Build fails after commit #7d2dac5:

### ISSUE THREAD

**Issue by pylover** [visualfc/liteide#575]
Last night i installed the liteide at home, without any issue. but after the last commit , i cannot install the liteide in the same way i installed at home:

src/github.com/visualfc/gotools/goapi/goapi.go:12:2: cannot find package "bufio" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/bufio (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/bufio (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/bufio
src/github.com/visualfc/gotools/command/command.go:10:2: cannot find package "bytes" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/bytes (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/bytes (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/bytes
src/golang.org/x/tools/go/types/initorder.go:8:2: cannot find package "container/heap" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/container/heap (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/container/heap (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/container/heap
src/github.com/visualfc/gotools/jsonfmt/jsonfmt.go:9:2: cannot find package "encoding/json" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/encoding/json (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/encoding/json (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/encoding/json
src/golang.org/x/tools/present/args.go:8:2: cannot find package "errors" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/errors (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/errors (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/errors
src/github.com/visualfc/gotools/command/command.go:11:2: cannot find package "flag" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/flag (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/flag (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/flag
src/github.com/visualfc/gotools/astview/astview.go:8:2: cannot find package "fmt" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/fmt (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/fmt (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/fmt
src/github.com/visualfc/gotools/astview/astdoc.go:9:2: cannot find package "go/ast" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/go/ast (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/go/ast (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/go/ast
src/github.com/visualfc/gotools/pkgutil/pkgutil.go:4:2: cannot find package "go/build" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/go/build (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/go/build (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/go/build
src/github.com/visualfc/gotools/docview/dirtrees.go:11:2: cannot find package "go/doc" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/go/doc (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/go/doc (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/go/doc
src/github.com/visualfc/gotools/gofmt/imports.go:14:2: cannot find package "go/format" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/go/format (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/go/format (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/go/format
src/github.com/visualfc/gotools/types/types.go:12:2: cannot find package "go/importer" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/go/importer (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/go/importer (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/go/importer
src/github.com/visualfc/gotools/astview/astview.go:10:2: cannot find package "go/parser" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/go/parser (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/go/parser (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/go/parser
src/github.com/visualfc/gotools/finddoc/finddoc.go:36:2: cannot find package "go/printer" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/go/printer (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/go/printer (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/go/printer
src/github.com/visualfc/gotools/gofmt/gofmt.go:10:2: cannot find package "go/scanner" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/go/scanner (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/go/scanner (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/go/scanner
src/github.com/visualfc/gotools/astview/astdoc.go:10:2: cannot find package "go/token" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/go/token (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/go/token (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/go/token
src/github.com/visualfc/gotools/astview/astview.go:12:2: cannot find package "go/types" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/go/types (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/go/types (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/go/types
src/golang.org/x/tools/present/style.go:9:2: cannot find package "html" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/html (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/html (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/html
src/golang.org/x/tools/present/code.go:11:2: cannot find package "html/template" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/html/template (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/html/template (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/html/template
src/github.com/visualfc/gotools/command/command.go:13:2: cannot find package "io" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/io (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/io (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/io
src/github.com/visualfc/gotools/astview/astview.go:14:2: cannot find package "io/ioutil" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/io/ioutil (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/io/ioutil (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/io/ioutil
src/github.com/visualfc/gotools/command/command.go:14:2: cannot find package "log" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/log (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/log (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/log
src/golang.org/x/tools/go/exact/go13.go:10:2: cannot find package "math" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/math (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/math (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/math
src/golang.org/x/tools/go/exact/exact.go:19:2: cannot find package "math/big" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/math/big (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/math/big (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/math/big
src/golang.org/x/tools/present/link.go:10:2: cannot find package "net/url" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/net/url (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/net/url (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/net/url
src/github.com/visualfc/gotools/command/command.go:15:2: cannot find package "os" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/os (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/os (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/os
src/github.com/visualfc/gotools/goapi/goapi.go:25:2: cannot find package "os/exec" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/os/exec (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/os/exec (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/os/exec
src/github.com/visualfc/gotools/finddoc/finddoc.go:40:2: cannot find package "path" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/path (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/path (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/path
src/github.com/visualfc/gotools/pkgutil/pkgutil.go:7:2: cannot find package "path/filepath" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/path/filepath (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/path/filepath (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/path/filepath
src/golang.org/x/tools/go/types/typeutil/map14.go:14:2: cannot find package "reflect" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/reflect (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/reflect (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/reflect
src/github.com/visualfc/gotools/pkgutil/pkgutil.go:8:2: cannot find package "regexp" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/regexp (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/regexp (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/regexp
src/github.com/visualfc/gotools/command/version.go:9:2: cannot find package "runtime" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/runtime (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/runtime (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/runtime
src/golang.org/x/tools/go/pointer/analysis14.go:18:2: cannot find package "runtime/debug" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/runtime/debug (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/runtime/debug (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/runtime/debug
src/github.com/visualfc/gotools/astview/astdoc.go:12:2: cannot find package "sort" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/sort (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/sort (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/sort
src/github.com/visualfc/gotools/astview/astdoc.go:13:2: cannot find package "strconv" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/strconv (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/strconv (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/strconv
src/github.com/visualfc/gotools/command/command.go:16:2: cannot find package "strings" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/strings (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/strings (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/strings
src/github.com/visualfc/gotools/command/command.go:17:2: cannot find package "sync" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/sync (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/sync (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/sync
src/github.com/visualfc/gotools/command/command.go:18:2: cannot find package "text/template" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/text/template (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/text/template (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/text/template
src/github.com/visualfc/gotools/docview/docview.go:19:2: cannot find package "time" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/time (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/time (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/time
src/github.com/visualfc/gotools/command/command.go:19:2: cannot find package "unicode" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/unicode (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/unicode (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/unicode
src/github.com/visualfc/gotools/command/command.go:20:2: cannot find package "unicode/utf8" in any of:
	/home/vahid/.gvm/gos/go1.6/src/pkg/unicode/utf8 (from $GOROOT)
	/home/vahid/workspace/liteide/liteidex/src/unicode/utf8 (from $GOPATH)
	/home/vahid/.gvm/pkgsets/go1.6/global/src/unicode/utf8
error, go install fail

**Comment by nkts** [comment]
Hi @pylover, can you provide more information about your setup? eg which OS, version, which build script were you running?

**Comment by nkts** [comment]
Tried to reproduce error - tho looks good with update_pkg.sh and build_linux.sh.
There're few more scripts with broken bash if condition, like this one:

```
$ grep -R '$GOPATH]' *
build_freebsd.sh:if [ -z $GOPATH]; then
build_linux_debian72_x64.sh:if [ -z $GOPATH]; then
build_openbsd.sh:if [ -z $GOPATH]; then
```
For example running *bash -x build_freebsd.sh*:
```
$ GOPATH=/tmp/test bash -ex build_freebsd.sh
<...>
+ echo build liteide tools ...
build liteide tools ...
+ cd /home/nkts/code/recipes/liteide/tmp-build/liteide-HEAD/build/../liteidex
+ '[' -z '/tmp/test]'
build_freebsd.sh: line 50: [: missing `]'
+ export GOPATH=/home/nkts/code/recipes/liteide/tmp-build/liteide-HEAD/liteidex:/tmp/test
+ GOPATH=/home/nkts/code/recipes/liteide/tmp-build/liteide-HEAD/liteidex:/tmp/test
<...>
```
or
```
$ GOPATH= bash -ex build_freebsd.sh
<...>
+ echo build liteide tools ...
build liteide tools ...
+ cd /home/nkts/code/recipes/liteide/tmp-build/liteide-HEAD/build/../liteidex
+ '[' -z ']'
+ export GOPATH=/home/nkts/code/recipes/liteide/tmp-build/liteide-HEAD/liteidex
+ GOPATH=/home/nkts/code/recipes/liteide/tmp-build/liteide-HEAD/liteidex
<...>
```
Which makes script broken if $GOPATH is present.

] is separate test command and needs to have space before it otherwise it's just a variable.

I could fix those scripts, but can't validate if build works properly.

**Comment by visualfc** [comment]
I'm update script, but no env to test, please update to lastest and check.
https://github.com/visualfc/liteide/commit/17dbaeeb3e6ad3e384b0aee685dc679284c4319b
