### ISSUE TITLE
No rebuild if source directory is named go

### ISSUE THREAD

**Issue by stemd** [visualfc/liteide#583]
Sorry if this issue is already reported, but there are 12 pages of issues, I searched and listed issues manually, and did not find anything similar.

**Steps to reproduce the bug**
1. Name directory go (yes, go :), and in it create go source file named something.go
2. Build it
3. Make some changes to something.go
4. Run rebuild & run

**Description of bug**
On rebuild nothing happens (old binary named `go` is kept), so you need to manually delete old binary so LiteIDE would make new binary.

**Notes**
- although "go" is not to much descriptive name for a project written in go :), that should not cause behavior like above
- please reduce number of open issues, e.g. close issues which will not be fixed, because reporting new issue on top of pile of old issues does not seem useful.

**Comment by visualfc** [comment]
fix it
https://github.com/visualfc/liteide/commit/628992da0a71ad7f839bb5914b421e2b007b1861
