### ISSUE TITLE
希望Testing 时只测试某个Go文件而不是整个包

### ISSUE THREAD

**Issue by hzmnet** [visualfc/liteide#584]
希望Testing 时只测试某个Go文件而不是整个包

**Comment by flike** [comment]
+1

**Comment by visualfc** [comment]
印象中 go test 好象没有提供这样功能，不知道是否有相应的参数来实现？

**Comment by helphi** [comment]
- `go test xxx_test.go` 就是测试单个文件吧！？
- 另外我发现除了file run（即 `FR`）外其他功能都不支持单个文件，希望增加这些功能按钮并且最好在右键某个go文件的菜单中出现相应的选项
- 我还问一下 liteide 设置代理的选项怎么进入，找了半天找不到

**Comment by visualfc** [comment]
go test xxx_test.go 只有在没有函数依赖时才可用

**Comment by helphi** [comment]
- 由于我们很多时候还是要写单个的go文件的，它们也确实不需要依赖，所以很希望能提供单个文件的test build 等功能
- LiteIDE本身确实不需要连网，我们的场景是在LiteIDE点击 `go get` 等按钮时无法连接有些代码库，所以非常希望LiteIDE提供代理设置的功能（就像修改GOPATH一样的这种）能够让 `go get` 这种指令能够通过代理获取代码

**Comment by visualfc** [comment]
go get 的代理应该可以由系统来设置。

**Comment by helphi** [comment]
- 代理确实是可以通过系统来设置的，只是没那么方便，这个功能没那么重要。
- 单个go文件的 test build 其实也是可以直接敲指令的，只是也没有 `FR` 那么方便，这个功能倒是我们非常期待的了

**Comment by visualfc** [comment]
已修复，通过在gotools中增加gotest处理行为对xxx_test.go进行分析并调用go test进行测试。
https://github.com/visualfc/liteide/commit/0d9ebbe0219d3acfdeb97513efe82e389b0cef9e

**Comment by helphi** [comment]
build 按钮可以也增加 File Build 么

**Comment by visualfc** [comment]
选项-LiteBuild 双击修改 gosrc.xml 参照格式修改后重新启动liteide即可。

**Comment by visualfc** [comment]
x29 已发布
