### ISSUE TITLE
mac下，搜狗拼音输入法输入英文时无法切换大小写

### ISSUE THREAD

**Issue by AnotherGoogleFans** [visualfc/liteide#586]
如题。版本为X28

**Comment by visualfc** [comment]
可能是Qt4的问题。

**Comment by hqpko** [comment]
@AnotherGoogleFans mac的x28版本问题很多，我今天刚换回了x27-qt5，舒爽了不少

**Comment by AnotherGoogleFans** [comment]
那能否提供qt5的编译版本？自己编译实在是太麻烦

**Comment by hqpko** [comment]
[http://golangtc.com/download/liteide](url)
各个版本都有，推荐有27.2.1的

**Comment by visualfc** [comment]
x29 已发布，macosx下使用Qt5.6编译
