### ISSUE TITLE
Code template

### ISSUE THREAD

**Issue by vhBushi** [visualfc/liteide#588]
Lite ide have some tool for make code templates like netbeans?

**Comment by xiegeo** [comment]
The feature exit, but not well documented.
Go to your installation dir and look for <code>liteide\share\liteide\packages\go\go.snippet.json</code>. 
The snippets should appear as selections in autocomplete.
https://github.com/visualfc/liteide/issues/512#issuecomment-170743160

**Comment by vhBushi** [comment]
@xiegeo thx, I'll play with it
