### ISSUE TITLE
Automatically mark unused variables and imports

### ISSUE THREAD

**Issue by matrixik** [visualfc/liteide#59]
Would be nice to have option to automatically mark unused variables and imports with underline or different background colour.

Idea from:
https://groups.google.com/d/msg/golang-nuts/BWDmZFX9hRI/L3NeT6Zp4J8J

> More useful, I think, would be an IDE feature that could automatically mark unused variables and imports as one writes code.

Best regards,
Dobrosław Żybort

**Comment by visualfc** [comment]
now gotools integrated goimports for auto imports line check.
Ctrl+Alt+I
