### ISSUE TITLE
BUG: 同样代码,liteIDE下无打印语句输出,但在命令行里运行就有

### ISSUE THREAD

**Issue by AnotherGoogleFans** [visualfc/liteide#592]
代码如下：

`package main

// #include <stdio.h>
// #include <stdlib.h>
/*
void print(char *str) {
    printf("%s\n", str);
}
*/
import "C"
import (
	"unsafe"
)

func main() {
	s := "hello"
	cs := C.CString(s)
	defer C.free(unsafe.Pointer(cs))
	C.print(cs)
}`

liteIDE版本：x28 mac

**Comment by visualfc** [comment]
可能缓存了，可以使用liteide的运行在终端功能。
