### ISSUE TITLE
 find usage error: invalid vendoredImportPath: on x29

### ISSUE THREAD

**Issue by cnlangzi** [visualfc/liteide#593]
Refactor/Go to Definition do not work on x29.

It says:  find usage error: invalid vendoredImportPath: : dir="D:\\go\\src\\github.com\\xxx\xxx"  root="D:\\GO\\src" separator="\\"

But they work well on x28.

**Comment by visualfc** [comment]
The X29 env GO15VENDOREXPERIMENT=1 is default enable, please comment and check.
Please provide a simple test example for me.

**Comment by cnlangzi** [comment]
@visualfc it works after pc is restarted.  so strange. It maybe a cache issue.  thanks.
