### ISSUE TITLE
X29: 目录栏明显的卡顿与迟滞感

### ISSUE THREAD

**Issue by AnotherGoogleFans** [visualfc/liteide#594]
RT，左边的目录栏里有很多GO项目。无论是从这里打开文件夹，还是拖动上下滚动条，都感觉到明显的卡顿和迟滞感。而右边的代码栏就很流畅。

版本为X29  MAC QT5

**Comment by AnotherGoogleFans** [comment]
重新更新下上面的情况：
刚打开的时候很流畅，随着使用时间的增加，会越来越卡。
关闭后重新打开又恢复流畅。
怀疑是否有内存泄露或者其它。请查证。

**Comment by visualfc** [comment]
MacOS X29 Qt4版本测试过没有，有没有同样的问题？

**Comment by AnotherGoogleFans** [comment]
MacOS X29 Qt4版本用了几天，一切正常，没有卡顿现象。
