### ISSUE TITLE
X29 removes external imports on save

### ISSUE THREAD

**Issue by JamesDunne** [visualfc/liteide#595]
Saving `main.go` in X29 removes external imports, specifically "gopkg.in/yaml.v2"

`go fmt` from the command line does not remove the imports.

```
$ go version
go version go1.6 windows/amd64
```

**Comment by visualfc** [comment]
I tested, and there was no such problem.
please disable option GolangFmt/eanble update imports line and go build check is ok?

**Comment by JamesDunne** [comment]
Disabled GolangFmt/enable update imports lines setting and "gopkg.in/yaml.v2" is not removed.

Re-enabled option and the import is removed. The library is definitely referenced in my code as `yaml.Unmarshal`. Perhaps the "yaml.v2" import name causes a mismatch with the imported name of "yaml" and causes gofmt to remove it.

Is this a gofmt bug then? Not a LiteIDE bug?

**Comment by visualfc** [comment]
I' test the code is ok,  please check liteide/bin/gotools is new version, and go list ...  to check yaml.

`
package main

import (
	"fmt"
	"log"

	"gopkg.in/yaml.v2"
)

var data = `
a: Easy!
b:
  c: 2
  d: [3, 4]
`

type T struct {
	A string
	B struct {
		RenamedC int   `yaml:"c"`
		D        []int `yaml:",flow"`
	}
}

func main() {
	t := T{}
	err := yaml.Unmarshal([]byte(data), &t)
	if err != nil {
		log.Fatalf("error: %v", err)
	}
	fmt.Printf("--- t:\n%v\n\n", t)
}

`
