### ISSUE TITLE
Issue asking fro License

### ISSUE THREAD

**Issue by ifraixedes** [visualfc/liteide#596]
Please, consider to specify a license

First of all, thanks to release this work on a public repository.

Nonetheless, this repo doesn't have any concrete license (or it isn't easy to see), so I would like that you consider to choose one to avoid the confusion that it causes with its absence, the work has applied the default copyright laws which the most of the people we aren't sure the implications because we aren't lawyers.

[This page may help you to decide which one is more convenient for you and all the benefits that an open license has over a closed one](https://help.github.com/articles/open-source-licensing/), however, don't get me wrong, choose the one that fits better to your specific case, independently if it's open or not.

Thanks for considering.

**Comment by russel** [comment]
The C++ files are marked as being LGPL I believe.

**Comment by ifraixedes** [comment]
Ups, that's good!
I didn't take a look to the code.

Then could you add just a comment in the README or adding a LICENSE file in the root of the repo? It would be easy to see it

**Comment by russel** [comment]
I think it would be good for there to be a formal licence statement at the top level as @ifraixedes   suggests.

**Comment by visualfc** [comment]
add LICENCE.LGPL to root.
