### ISSUE TITLE
"函数调用"配色不起作用

### ISSUE THREAD

**Issue by Hyman-Lv** [visualfc/liteide#598]
比如:
fmt.Println("Hello world")
Println和fmt是一个颜色,不是style scheme中配的颜色

版本:windows x28

**Comment by 0qdk4o** [comment]
liteide/liteidex/src/plugins/syntaxeditor/golanghighlighter.cpp

61    //function
62    rule.pattern = QRegExp("\\b[a-zA-Z_][a-zA-Z0-9_]+\\s*(?=\\()");
63    rule.format = functionFormat;

这里的正则表达式看来只支持
func Abc()
不支持
fmt.Printf()

 rule.pattern = QRegExp("(\\b|\\.)[a-zA-Z_][a-zA-Z0-9_]+\\s*(?=\\()");
这样是否可行？

抱歉，我阅读代码能力有限，当前也不方便自己编译测试，麻烦作者指教

**Comment by gonboy** [comment]
最新的x32 ,也存在同样的问题。
```
  <style name="Function" foreground="#4cb8e3"/>
```
变更了，不起任何的作用.

**Comment by fastfading** [comment]
@0qdk4o  能否编译一个版本，如果可行提交一个pull request 。   goland开始收费了，  其实 liteide相比goland也就只差个这个了。   最重要的就是这个function 高亮，其他  const    struct 的高亮有没有影响不大。

**Comment by discoverfly** [comment]
Function 高亮本来就有，只是默认的配色方案没有高亮function. 
       ： Preferences-> LiteEditor -> 字体和颜色 -> 编辑器颜色方案 -> gist-github.xml 
就看得到function高亮了。
