### ISSUE TITLE
Show function arguments in popup helper

### ISSUE THREAD

**Issue by matrixik** [visualfc/liteide#6]
Now when we write code popup helper (don't know how to call it) showing us function with it's arguments only when we type it's name

![liteide_showFunction](http://i.imgur.com/lGNJR.png)

but when we are inside () it showing only variables

![liteide_showVariables](http://i.imgur.com/xmHiP.png)

Can you add option to show function arguments when we are in braces?

I like how PyCharm showing them:

![pycharm_showArguments](http://i.imgur.com/duLTY.png)

Actual argument we are editing is in bold.

How it could look like:
![liteide_showVariablesAndArguments](http://i.imgur.com/WYnZB.png)

Best regards

**Comment by visualfc** [comment]
please downlaod x27 and check.

**Comment by matrixik** [comment]
Thank you for working on this.
Unfortunately it works only partially:
![anim](https://cloud.githubusercontent.com/assets/201930/6050547/c99d2548-acc0-11e4-83de-06b7e898a5e9.gif)
As you can see when I started typing proper variable name it's hiding but when I typed `o` as third argument it stay visible (no variable exist with name starting with `o`).

**Comment by visualfc** [comment]
one tooltip stay for completer
