### ISSUE TITLE
F2查找出错

### ISSUE THREAD

**Issue by coolit** [visualfc/liteide#601]
个人库文件中有一句是：
return mahonia.NewEncoder("GB18030").ConvertString(utf8)
从该库文件中选中NewEncoder按F2提示：
17:15:12 find def error: 进程退出代码 1
如果这句是在主程序文件中，则按F2不会出错。

**Comment by visualfc** [comment]
测试是否都能正常编译？gotoos跟pkg/cmd无关。

**Comment by coolit** [comment]
可以正常编译。就是按F2查看时出现那个错误提示。目前就发现这个会这样，其他库文件没问题。

**Comment by gooid** [comment]
把 hasFilePathPrefix 按以下改：
// hasFilePathPrefix reports whether the filesystem path s begins with the
// elements in prefix.
func hasFilePathPrefix(s, prefix string) bool {
	rel, err := filepath.Rel(prefix, s)
	if err == nil && (rel == "." || rel[0] != '.') {
		return true
	}
	return false
}

**Comment by judwhite** [comment]
@coolit I was able to fix `find def error: process exited with code 1` by commenting `#GO15VENDOREXPERIMENT=1` from `win64` env. Make sure to switch your environment for the change to take effect.

This had no effect on the `system` env which shows in Build Out `set GO15VENDOREXPERIMENT=1` even though it is not in my system.env or in my machine environment settings. I'm running Go 1.6.0, LiteIDE X29.

Note about https://github.com/visualfc/gotools/blob/22bf1ae0782723a4408e438bfbbd251e802b029f/pkgutil/pkgutil.go#L12 for @visualfc Vendor is default in Go 1.6.x, it can only be turned off by setting the environment variable `=0`. In Go 1.7 the environment variable will have no effect.

Hopefully translation is able to get the message across, there is a workaround :smiley:

**Comment by nadoo** [comment]
确实，#GO15VENDOREXPERIMENT=1 之后，就可以查看函数定义了。

**Comment by visualfc** [comment]
@coolit @nadoo 
go version and example

**Comment by visualfc** [comment]
please download x35.1 and check.
