### ISSUE TITLE
liteidex29.windows-qt5.zip - packaging for x86 version of gocode.exe and gotools.exe

### ISSUE THREAD

**Issue by tejorupan** [visualfc/liteide#605]
Kindly bundle the x86 binaries for gocode.exe and gotools.exe in the liteidex29.windows-qt5.zip.
It contains the x64 binaries for the above mentioned executables.

On a 32-bit system,  these two above mentioned binaries do not run.

**Comment by visualfc** [comment]
sorry, fix it

**Comment by visualfc** [comment]
https://sourceforge.net/projects/liteide/files/X29/
liteidex29.windows-qt5-1.zip
https://sourceforge.net/projects/liteide/files/X29/liteidex29.windows-qt5-1.zip/download
