### ISSUE TITLE
执行 自动补全无效参数 go test -test.branch=.*

### ISSUE THREAD

**Issue by woniu369** [visualfc/liteide#607]
```flag provided but not defined: -test.branch```

```go test -test.branch=.*```
应该是
```go test -test.bench=.*```

同时建议自动补全添加
```go test -test.bench=.* -test.benchmem```

**Comment by visualfc** [comment]
fixed
这个文件位于  \liteide\share\liteide\litebuild\command\go.api文件中，可以自行修改
