### ISSUE TITLE
x29版本的树形控件看起来有点诡异啊

### ISSUE THREAD

**Issue by hdczsf** [visualfc/liteide#608]
![default](https://cloud.githubusercontent.com/assets/1089776/14851872/49ea6454-0cb5-11e6-8af1-c8338de5c196.png)

**Comment by visualfc** [comment]
Qt5.6 for windows 编译后会这样，还未找到原因。

**Comment by visualfc** [comment]
确认是Qt5.6的问题，我的QtCreator3.6.1也是如此。
