### ISSUE TITLE
build fails on RHEL7.1

### ISSUE THREAD

**Issue by rakesh-k** [visualfc/liteide#609]
Downloaded the repo but the the update_pkg is giving me errors that I don't seem to follow. 

[rakeshk@cd3labvdapp002 build]$ ./update_pkg.sh
GOROOT=/usr/bin/
BUILD_ROOT=/home/rakeshk/liteide/build
LITEIDE_ROOT=/home/rakeshk/liteide/build/../liteidex

go version go1.4.2 linux/amd64
update liteide tools ...
get gocode ...
github.com/nsf/gocode (download)
import "bytes": import path does not contain a slash
package github.com/nsf/gocode
        imports bytes: unrecognized import path "bytes"
import "encoding/json": import path does not begin with hostname
package github.com/nsf/gocode
        imports encoding/json: unrecognized import path "encoding/json"
import "errors": import path does not contain a slash
package github.com/nsf/gocode
        imports errors: unrecognized import path "errors"
import "flag": import path does not contain a slash
...

**Comment by visualfc** [comment]
GOROOT error setup

**Comment by visualfc** [comment]
gocode build request go version 1.4 or hight.
liteide gotools build request go version 1.5 or hight

**Comment by rakesh-k** [comment]
Thanks. I updated the go version to 1.6. Here are the variables and other lines from the update_pkg.sh during the run:

GOROOT=/usr/local/go/bin
BUILD_ROOT=/home/rakeshk/liteide/build
LITEIDE_ROOT=/home/rakeshk/liteide/build/../liteidex
.
go version go1.6.2 linux/amd64
update liteide tools ...
GOPATH=/home/rakeshk/liteide/liteidex
get gocode ...
github.com/nsf/gocode (download)
package bytes: unrecognized import path "bytes" (import path does not begin with hostname)
package encoding/json: unrecognized import path "encoding/json" (import path does not begin with hostname)
....more

**Comment by visualfc** [comment]
GOROOT=/usr/local/go
