### ISSUE TITLE
Some suggestions to make LiteIde more popular : )

### ISSUE THREAD

**Issue by james-tech** [visualfc/liteide#615]
dear liteide developers:

I have some suggestions about this ide.   : ) 
1. support `TODO list`:
   
   > we can do some mark in the code comment, and can use a TODO list to jump back to the line we do the mark. It will be very usefull.
2. support `vim editor's  control mode`:
   
   > as we could use h key to move cursor left and use L key to move cursor right, and so on.
   > then, we don't need the mouse : )

I hope this suggestions will be accept. thank you very much.

best wishes~

James

**Comment by visualfc** [comment]
fixed in x33
