### ISSUE TITLE
Qt5 (feature request)

### ISSUE THREAD

**Issue by xyproto** [visualfc/liteide#62]
Hi,

Please update the code to support Qt5. I can't compile LiteIDE X on Arch Linux any more.

If I try to compile with the old version of Qt, which has been moved to different locations, I get this error:

```
../../../../liteidex/src/plugins/webkithtmlwidget/webviewhtmlwidget.cpp:26:20: fatal error: QWebView: No such file or directory
 #include <QWebView>
                    ^
compilation terminated.
```

Best regards,
Alexander Rødseth

**Comment by Zamicol** [comment]
I'm having a similar issue.  I opened up a new issue https://github.com/visualfc/liteide/issues/514
