### ISSUE TITLE
[feature request] fast open .go file by file name

### ISSUE THREAD

**Issue by bruceauyeung** [visualfc/liteide#621]
there should be a mechanism to fast open golang source file.
suggested workflow:
1. user press a keyboard combination(`ctrl + shift + o`) or click a menu item (maybe `fast open` is a good name)
2. liteide show `fast open` window, which at least has a input box(input keyword to search) and result list window(display searched golang source file list) in it. please refer to `Open Type` in eclipse.
3. inputbox should support wildcard pattern,regex is optional.
4. user click a line in list window to open the specified file,  if user hit enter key directly, open the first one.

liteIDE version i am using : liteIDE:X29
windows: windows 7 32bit

**Comment by visualfc** [comment]
ctrl+p / command+p to QuickOpen 
input name to filter for liteide folders all file.
