### ISSUE TITLE
Keyboard shortcut "DeleteLine" not assign to Ctrl+X

### ISSUE THREAD

**Issue by Doaxan** [visualfc/liteide#623]
Keyboard shortcut "DeleteLine" not assign to Ctrl+X, but Ctrl+Shift+X works.

**Comment by Doaxan** [comment]
Also not assign CopyLine to Ctrl+C.

**Comment by Doaxan** [comment]
And please add Ctrl+Enter and Ctrl+Shift+Enter to Keyboard shortcuts list, so they can be reassigned. Thanks.

**Comment by visualfc** [comment]
editor internal key not assign
