### ISSUE TITLE
How can I custom TARGETNAME in build configuration?

### ISSUE THREAD

**Issue by applee** [visualfc/liteide#627]
I can not run the application When I changed `BUILDARGS` to add  `-o xxxx` in build configuration. How  can I custom `TARGETNAME`?

**Comment by visualfc** [comment]
liteide option - litebuild - gosrc.xml
```
<custom id="TargetName" name = "TARGETNAME" value="$(BUILD_DIR_NAME)"/>
<custom id="BuildArgsi" name="BUILDARGS" value="-i -o $(TARGETNAME)"/>
```
modify and restart liteide

**Comment by applee** [comment]
Thanks. I strongly recommend that it can be set in UI Window.
![default](https://cloud.githubusercontent.com/assets/1467773/15318959/1127d63c-1c5b-11e6-8ba7-aed7002d0342.png)
