### ISSUE TITLE
code completion/jump to declaration does not work/is very slow in LiteIDEx29 with Go1.7 beta 1 on Ubuntu amd64

### ISSUE THREAD

**Issue by leeview** [visualfc/liteide#633]
What version of LiteIDE and Go are you using (go version)?
LiteIDE x29 with go1.7beta1 linux/amd64

What operating system and processor architecture are you using (go env)?
Ubuntu amd64

What did you do?
While editing a (~larger) project using the LiteIDE editor, I noticed that the code completion does not work anymore and "jump to declaration" and "view expression information" functionality is very slow (5-10 seconds delay) right after I updated from Go 1.6.2 to Go 1.7 beta 1 and the slowdown didn't go away after reboot. After I changed back to Go 1.6.2 everything worked normal.

What did you expect to see?
code completion, "jump to declaration" and "view expression information" should be responsive (like when using Go 1.6.2)

What did you see instead?
code completion not working at all; "jump to declaration" and "view expression information" are very slow

**Comment by gaillard** [comment]
Would like this looked into too :)

**Comment by visualfc** [comment]
please build gotools and gocode in go1.7 and copy to liteide/bin
go get -u github.com/visulafc/gotools
go get -u github.com/nsf/gocode

**Comment by tux-eithel** [comment]
@visualfc  fix typo: `go get -u github.com/visualfc/gotools`

**Comment by leeview** [comment]
@visualfc Thank you very much. It works now.

**Comment by gaillard** [comment]
Seems slow again (8s), I'm trying go1.10beta1 and the latest liteide, 33.1.

**Comment by visualfc** [comment]
Update liteide tools for support new Golang Version

go get -u github.com/visualfc/gotools
go get -u github.com/nsf/gocode

Windows/Linux: copy GOPATH/bin gotools and gocode to liteide/bin
MacOS: copy GOPATH/bin gotools and gocode to LiteIDE.app/Contents/MacOS
