### ISSUE TITLE
go 1.7 语法提示消失了

### ISSUE THREAD

**Issue by Anehta** [visualfc/liteide#637]
下了go1.7 beta1版，在liteide里语法提示不见了。

**Comment by visualfc** [comment]
https://github.com/visualfc/liteide/issues/633

please update and build gotools gocode in go1.7 and copy to liteide/bin
go get -u github.com/visualfc/gotools
go get -u github.com/nsf/gocode

**Comment by qzyuanmu** [comment]
@visualfc 国内很悲剧啊，最近翻墙工具都不好使了，最好能提供一个编译好的
