### ISSUE TITLE
下一个版本建议，把键盘的上下左右快捷键和移动行尾行首，改成自定义快捷键，方便打码

### ISSUE THREAD

**Issue by iteny** [visualfc/liteide#638]
下一个版本建议，把键盘的上下左右快捷键和移动行尾行首，改成自定义快捷键，方便打码

**Comment by visualfc** [comment]
fixed
https://github.com/visualfc/liteide/commit/b6c002807ac115e17f478a787159e900c9ecbec0
https://github.com/visualfc/liteide/commit/d3cec6d576ec491a6f778348f343134c7288da88
