### ISSUE TITLE
大纲视图下显示空白

### ISSUE THREAD

**Issue by xiaojianwu** [visualfc/liteide#639]
go version go1.6.2 windows/386
liteidex29.windows-qt4
Microsoft Windows [版本 10.0.14342]

类视图也有同样问题

**Comment by visualfc** [comment]
看一下GOROOT和GOPATH是否正确设置

**Comment by xiaojianwu** [comment]
环境变量设置如下
GOBIN=d:\GOBIN
GOPATH=d:\gopath
GOROOT=C:\Go\

两台win10机器都有这个问题，win7没有这个问题。
看c:\go\src 可以正常显示大纲内容
d:\gopath\src下的就不行

**Comment by visualfc** [comment]
修复了gotools的vendor错误
go get github.com/visualfc/gotools 
复制 gotools到 liteide/bin中试一下。

**Comment by xiaojianwu** [comment]
ok了

**Comment by gonboy** [comment]
按照编译步骤，编译完后，
没有将 liteidex\liteidex\bin\windows_386\to*.exe 复制到 liteide\build\liteide\bin
目录下。
建议改下批处理。
liteide\build\deploy_* 的部署文件.
