### ISSUE TITLE
How do you pass command line arguments for run or debug?

### ISSUE THREAD

**Issue by mrichman** [visualfc/liteide#646]
How do you pass command line arguments for run or debug?

**Comment by visualfc** [comment]
build config TARGETARGS

**Comment by mrichman** [comment]
No, I mean how do you pass arguments to the executable you're debugging. I'm not asking about building liteide itself.

**Comment by visualfc** [comment]
liteide open go files, and build toolbar or build menu "Build Configuration..."  dialog => custom TARGETARGS ,The value is run or debug pass arguments.

**Comment by xgdgsc** [comment]
This can be closed.

**Comment by SkybuckFlying** [comment]
Thx !
