### ISSUE TITLE
LiteIDE 30 fails on Debian Sid

### ISSUE THREAD

**Issue by russel** [visualfc/liteide#648]
When trying to start LiteIDE on Debian Sid:

liteide: /usr/lib/x86_64-linux-gnu/libpng12.so.0: version `PNG12_0' not found (required by /home/users/russel/lib.Linux.x86_64/liteide-30.0.0/bin/../lib/liteide/libQtGui.so.4)

**Comment by visualfc** [comment]
linux install qt4 runtime and  download liteidex30.linux64-qt4-system or remove libQt*

**Comment by russel** [comment]
For myself I just compiled from source using the Linux Qt5 build.
