### ISSUE TITLE
菜单栏打开的文件与下拉按钮显示的文件不匹配

### ISSUE THREAD

**Issue by Hawken94** [visualfc/liteide#655]
版本：30.1
系统：win10 64位
一开始打开项目还是匹配的，但是过了一段时间后，就开始不匹配了

**Comment by Hawken94** [comment]
就是打开一个项目一段时间后，菜单栏显示的文件就会与下拉按钮的文件不一致。

**Comment by visualfc** [comment]
已修复。https://github.com/visualfc/liteide/commit/cb4f475b315b1354534a48335fbc9c66ba116b72
