### ISSUE TITLE
Mac OSX10.10.5下liteide30.0.2版本持续崩溃

### ISSUE THREAD

**Issue by qxhy123** [visualfc/liteide#663]
各种崩溃, 每次到最后一步loading session就会崩溃.

**Comment by qxhy123** [comment]
补充一下, 是qt5

**Comment by qxhy123** [comment]
qt4经测没有问题.

**Comment by visualfc** [comment]
看来只能根据系统实际情况自选选择用Qt4和Qt5版本，大多数情况下Qt4是可用的，但最新的系统可能Qt5的兼容性会更好一些。
