### ISSUE TITLE
结构体里面的字段显示不对齐

### ISSUE THREAD

**Issue by Hawken94** [visualfc/liteide#666]
也许是我自己设置的原因，因为周围的小伙伴结构体都是对齐的。现在只想问问如何重置所有设置。

**Comment by visualfc** [comment]
配置文件位于 C:\Users\当前用户\AppData\Roaming\liteide 中

**Comment by Hawken94** [comment]
我不敢动那个配置文件~

**Comment by Hawken94** [comment]
要不我删掉那个文件，然后重新解压

**Comment by visualfc** [comment]
将编辑器字体设置成等宽字体。

**Comment by Hawken94** [comment]
谢谢，您已经在qq上跟我说了，昨天已经解决了
