### ISSUE TITLE
Windows下静态链接Qt5和LiteIDE的库的情况下，share文件夹内的资源文件应该放在哪里？

### ISSUE THREAD

**Issue by meoow** [visualfc/liteide#670]
我编译LiteIDE X30，使用**msys2**的**mingw64**，静态连接Qt5和LiteIDE的库到**liteide.exe**文件，
运行时主界面一片空白，应该是找不到**share**文件夹下的资源文件，请问这种情况下，资源文件应该如何放置，才能被liteide找到？

**Comment by visualfc** [comment]
https://github.com/visualfc/liteide/tree/master/build 里有 build 和 deploy 脚本
