### ISSUE TITLE
escape $ in gosrc.xml

### ISSUE THREAD

**Issue by jdoklovic** [visualfc/liteide#672]
How do I escape a $ in the gosrc.xml?

I want to change the TestAll args to be:

args="test $(TESTARGS) $(glide nv)"
Iv'e tried:

args="test $(TESTARGS) $$(glide nv)"
args="test $(TESTARGS) \$(glide nv)"
args="test $(TESTARGS) \$(glide nv)"
args="test $(TESTARGS) &#36;(glide nv)"

All of those fail with parse errors.

**Comment by visualfc** [comment]
fixed, now can include any $
