### ISSUE TITLE
无法调试

### ISSUE THREAD

**Issue by chennqqi** [visualfc/liteide#676]
环境windows-368  go 1.6 
liteide软件版本 30.2

gdb  -v
GNU gdb (GDB) 7.7

编译时已经加上了
-gcflags "-N -l"

命令行调试OK

问题现象:
1. F5启动调试后，设置断点不生效，提示为
error,msg="No source file named XXX.go
1. F5 进一步运行之后可以设置断点，但是无法在指定断点断住。
2. 一开始在main.main没有断住。

4.调试时编辑窗口左侧栏显示当前运行位置的光标不显示！！！！！！！！

**Comment by wlgq2** [comment]
快2022年了，还有这个bug。
