### ISSUE TITLE
Is it possible to get the current function under cursor

### ISSUE THREAD

**Issue by scorredoira** [visualfc/liteide#678]
Hi,

I'm adding the ability to run just the single test under the cursor. I have it working with **LiteApi::wordUnderCursor** (https://github.com/scorredoira/liteide/commit/3715948764ba2e83506ed51247a70c6d6746ae64#diff-472b8c35fd05129ad163db7326b9d796R471) but to use it you have to place the cursor on the test name. 

Has the editor an easy way to get the name of the function under the cursor if it is inside it?

thank you!

**Comment by visualfc** [comment]
https://github.com/visualfc/gotools/blob/master/finddecl/finddecl.go

**Comment by scorredoira** [comment]
Hi visualfc, great idea to have it as a go tool, but how should I invoke this code so it gets the file and line params? 
Thank you!

**Comment by visualfc** [comment]
find cursor code type 
> gotools types -info -pos main.go:1485 .
find line in block
> gotools finddecl -file main.go -line 80

**Comment by scorredoira** [comment]
thank you!
