### ISSUE TITLE
Markdown导出PDF页面样式

### ISSUE THREAD

**Issue by yougg** [visualfc/liteide#681]
Markdown导出的PDF可以支持定制这些参数吗?  
- 设置页眉/页脚内容  
- 设置页边距的宽度/高度  
- 设置页面背景图片(水印)

**Comment by visualfc** [comment]
LiteIDE的导出PDF功能实际是通过打印WebKit(Qt4版本)页面到PDF文档来实现的，打印PDF只能控制页边距。内容显示可以通过css来控制WebView的显示效果，理论上可以通过css来实现一些显示控制功能。

**Comment by visualfc** [comment]
目前只有 Qt4版本支持WebKit
