### ISSUE TITLE
编译输出信息出现乱码

### ISSUE THREAD

**Issue by xjjrocker** [visualfc/liteide#682]
liteide里面编译运行的时候debug变异输出的信息里面的乱码如下对应：
日志里的深蓝色变成了[97;44m [0m
日志里的绿色背景的200变成了[97;42m 200 [0m

**Comment by xjjrocker** [comment]
明明没有乱码，上面的竟然还有问号

**Comment by visualfc** [comment]
目前没有做颜色控制码的解析

**Comment by xjjrocker** [comment]
那么下个版本可否增加这个解析呢，我看用beego框架的很多人都用liteide来开发呢。那个颜色输出乱码了挺可惜的。

**Comment by visualfc** [comment]
fixit 颜色控制码直接用正则式过滤掉
https://github.com/visualfc/liteide/commit/372567332a02d30e674aa6a6d4ef73cff8c1daf0
