### ISSUE TITLE
编译配置参数无法保存

### ISSUE THREAD

**Issue by davyxu** [visualfc/liteide#684]
重现方法: 修改任何go代码, 编译->编译配置->自定义 修改INSTALLARGS为-v
执行 编译->Install
关闭liteIDE重新打开重复前面的步骤, 配置消失

期望: 保存编译配置到ini

**Comment by visualfc** [comment]
LiteIDE如果无法保存配置，有可能是liteide的系统配置文件出错，windows中位于AppData\Roaming\liteide\liteide.ini，删除掉重开liteide即可。
另外一种方法是在LiteIDE选项LiteApp中设置存储到本地ini文件中，重启LiteiDE。

**Comment by davyxu** [comment]
并没有手动修改过配置文件， 其他都可以正常存盘， 就单是编译配置无法保存

**Comment by davyxu** [comment]
发现编译配置是跟随package... 好吧, 那没问题了
