### ISSUE TITLE
macOS Sierra has broken LiteIDE 30.2 and also 30.1-1

### ISSUE THREAD

**Issue by hapnermw** [visualfc/liteide#697]
I'm getting one crash after another. For example, Find/Replace is almost guaranteed to crash.

It's completely unusable.

**Comment by rtoma** [comment]
same here, cpu goes crazy and fan starts

**Comment by nkts** [comment]
I think #707 is related to this

**Comment by nkts** [comment]
Is there a way to reproduce this? I have latest mac os and LiteIDE installed with brew.

**Comment by rtoma** [comment]
I 'fixed' this issue by changing the GOROOT in the 'system' profile. For me the root cause was not Sierra but a GO upgrade which I did shortly after upgrading, because I heard Sierra + GO 1.7 was not compatible. Again YMMV.

**Comment by hapnermw** [comment]
I updated to Go 1.7.3 and things began working correctly. Previously I was on Go 1.6
