### ISSUE TITLE
Old variables in autocomplete

### ISSUE THREAD

**Issue by AxeLFFF** [visualfc/liteide#698]
When I remove variable from code it stay in autocomplete popup and dissapear just after restart. Is it issue?

**Comment by taobig** [comment]
It happened to me!

**Comment by nkts** [comment]
I noticed that too

**Comment by visualfc** [comment]
fix it, save time clear temp list
https://github.com/visualfc/liteide/commit/b71ca923fb49616b37c3ad083af075bf44c132fb
