### ISSUE TITLE
Integrate source code lint tool

### ISSUE THREAD

**Issue by matrixik** [visualfc/liteide#70]
Hello,

maybe can you can integrate code lint tool with IDE.

New one used inside Google:
https://github.com/golang/lint/
Announcement: https://groups.google.com/d/msg/golang-nuts/eu9BK4l4-00/qch1kk-fw30J
```
golint is a linter for Go source code.

Invoke golint with one or more filenames.
The output of this tool is a list of suggestions in Vim quickfix format,
which is accepted by lots of different editors.

golint differs from govet. govet is concerned with correctness, whereas
golint is concerned with coding style. golint is in use at Google, and it
seeks to match the accepted style of the open source Go project.

The suggestions made by golint are exactly that: suggestions.
golint is not perfect, and has both false positives and false negatives.
Do not treat its output as a gold standard. We will not be adding pragmas
or other knobs to suppress specific warnings, so do not expect or require
code to be completely "lint-free".
Unlimited effort will not be expended to make golint perfect.
It is considered an abuse of this tool to run it for machine consumption.
```
And old one:
http://www.stathat.com/src/splint 

I like how Spyder IDE (http://code.google.com/p/spyderlib/ ) display all info about checked code:
![spyder-ide-lint](https://f.cloud.github.com/assets/201930/598123/c9553356-cc1f-11e2-98cd-51365684cdb7.png)

Best regards,
Dobrosław Żybort

P.S. This issue is updated version of http://code.google.com/p/golangide/issues/detail?id=75

**Comment by visualfc** [comment]
the build menu include golint action.
please download x27 and check. (reqsuet install golint)

**Comment by matrixik** [comment]
Hi, 

Thank you for your work on it. It's working now.
I still think adding alert icon in the same place as breakpoint icon is showing now would be nice but this status bar is also nice.
