### ISSUE TITLE
high energy consumption mac OS X Sierra

### ISSUE THREAD

**Issue by SergeyParamoshkin** [visualfc/liteide#707]
on my laptop to the high power consumption. 
<img width="728" alt="2016-10-22 12 13 31" src="https://cloud.githubusercontent.com/assets/2777897/19618364/f95cb17c-9850-11e6-892c-27ec14e9ca89.png">

LiteIDE 30.2
macbook pro, OS X Sierra

if you stop gotool everything is fine
<img width="731" alt="2016-10-22 12 19 10" src="https://cloud.githubusercontent.com/assets/2777897/19618386/c303a350-9851-11e6-940b-74e4b75dc132.png">

**Comment by littlexiang** [comment]
+1

**Comment by morya** [comment]
from [golang.org offcitial](https://golang.org/doc/go1.7) , you will see this:

```
Go 1.7 adds support for macOS 10.12 Sierra. Binaries built with versions of Go before 1.7 will not work correctly on Sierra.
```

if your liteIDE is binary package downloaded from somewhere,
 `gocode` and `gotools` came with it. And these two is compiled with golang 1.6 I think..
You will need to re-compile them for Mac Sierra.

You could compile them yourself, then copy them into `/Applications/dev/LiteIDE.app/Contents/MacOS/` .

gotools depends on `oracle` which is renamed to `guru` and dropped maintenance from [golang tool](https://github.com/golang/tools) .
You will need to update golang tool to a special version ( I managed to compile `gotools` with  git commit version `26c35b4dcf6dfcb924e26828ed9f4d028c5ce05a`.
put this version into folder 
`~/gopath/src/github.com/visualfc/gotools/vendor/golang.org/x/tools`.

then, you could run `go build` in `~/gopath/src/github.com/visualfc/gotools`.


PS:
Or, if you could trust, you can use my pre-compiled one.
[pre-compiled gotools and gocode](https://github.com/morya/gotools/releases/tag/0.1)

**Comment by visualfc** [comment]
gotools add oracle vendor
https://github.com/visualfc/gotools/commit/f7b2fa1c952e5b67a492282d131ac1352a7ed226

**Comment by rtoma** [comment]
To improve the workaround:
- github.com/visualfc/gotools has been fixed, so just build from master without any manual changes
- gocode can be build from github.com/nsf/gocode
