### ISSUE TITLE
Jump to Declaration  F2  is not work 

### ISSUE THREAD

**Issue by klkucan** [visualfc/liteide#71]
my liteidex version is X18.2 and os is mac os 10.8.4
when i use it on windows8 it's effective.

**Comment by visualfc** [comment]
please download x27 and check.

**Comment by visualfc** [comment]
control+leftmouse or
liteide option liteapp-> keyboard -> JumpToDeclaration

**Comment by paboum** [comment]
Still happening in X38.3. Perhaps related to Qt6 update.

**Comment by paboum** [comment]
I rebuilt it from master myself and now it works fine. Not sure if using qt 6.8.3 while building helped or pull request including gopls was the culprit but perhaps the next release should be retested against this issue.
