### ISSUE TITLE
UPPERCASE lowercase on right mouse click popup

### ISSUE THREAD

**Issue by dkeza** [visualfc/liteide#715]
Can you please add UPPERCASE lowercase menu item in right mouse click popup, like in Notepad++?
![uppercase_lowercase](https://cloud.githubusercontent.com/assets/12168379/20256487/3a6e888e-aa44-11e6-984c-20acbdf27cca.png)

**Comment by visualfc** [comment]
fix it
https://github.com/visualfc/liteide/commit/10f67ff030d81d597b0cc790c7f7fe5cfd40f85e
