### ISSUE TITLE
./update_pkg.sh doesn't work due to missing golang.org/x/tools/oracle package, which has been replace by go guru.

### ISSUE THREAD

**Issue by chintootech** [visualfc/liteide#716]
go version go1.7.3 linux/amd64
update liteide tools ...
get gocode ...
github.com/nsf/gocode (download)
get gotools ...
github.com/visualfc/gotools (download)
Fetching https://golang.org/x/tools/oracle?go-get=1
Parsing meta tags from https://golang.org/x/tools/oracle?go-get=1 (status code 200)
get "golang.org/x/tools/oracle": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/oracle?go-get=1
get "golang.org/x/tools/oracle": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
package golang.org/x/tools/oracle: cannot find package "golang.org/x/tools/oracle" in any of:
	/usr/local/go/src/golang.org/x/tools/oracle (from $GOROOT)
	/home/user/Development/Tools/GoLang/liteide/liteidex/src/golang.org/x/tools/oracle (from $GOPATH)
	/home/user/Development/work/golang/src/golang.org/x/tools/oracle
error, go install fail

**Comment by visualfc** [comment]
add oracle vendor
https://github.com/visualfc/gotools/commit/f7b2fa1c952e5b67a492282d131ac1352a7ed226

**Comment by visualfc** [comment]
add guru support
https://github.com/visualfc/liteide/commit/f9dbb974af9be554a21301674a3747643534a29b
