### ISSUE TITLE
AltGr key problem

### ISSUE THREAD

**Issue by ffred60** [visualfc/liteide#719]
Hi, I'm working with a French keyboard and AltGr key is necessary to be able to type **~#{[|`\^@]}€** characters.
in LiteIDE, if I try most of these necessary keyboard combination (AltGr+6 for exemple), it's opening/closing a tool Window (File System Window for the exemple).
I search here in the posted issues or in the forum, but didn't find something to correct completely the problem.
isn't it possible for you to add support for the AltGr key in LiteIDE. there are several country using this key. all the Windows software should be able to support it. (it's the first time I have to deal with this...).

at least, there should be something documented about it and/or a secondary keyboard mapping available.

thanks..
ffred

some infos about AltGr key :
[https://en.wikipedia.org/wiki/AltGr_key](https://en.wikipedia.org/wiki/AltGr_key)
[https://blog.molecular-matters.com/2011/09/05/properly-handling-keyboard-input/](https://blog.molecular-matters.com/2011/09/05/properly-handling-keyboard-input/)

**Comment by visualfc** [comment]
liteide - option - LiteApp - keyboard 
App context
example Modify ToolWindows_HtmlPreview  Alt+4 and clear

**Comment by ffred60** [comment]
Hi, thanks for replying.
ok..  the ToolWindows with a problem are those with a **Ctrl+Alt**+number. I cleared them..
would be nice to be able to distinguish AltGr key from Alt key, but it's working for now.
thanks
ffred
