### ISSUE TITLE
dlv was not found on system PATH

### ISSUE THREAD

**Issue by Antergone** [visualfc/liteide#721]
mac 10.12.1
version x30.2(qt5)

```shell
~  echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin:/Users/antergone/apache-maven-3.3.9/bin:/Users/antergone/gradle-3.2/bin:/Users/antergone/codespace/gopath/bin
~  which dlv
/usr/local/bin/dlv
```

**Comment by visualfc** [comment]
Delve is a debugger for the Go programming language.
https://github.com/derekparker/delve

**Comment by Antergone** [comment]
dlv安装过了  是ide没有读到系统的path

**Comment by dspasibenko** [comment]
I have same issue. I have delve installed, but when I select in liteIDE Debug->debugger/delve, it cannot find it, but from Console I can run it and yes, it is in PATH. Here what LiteIDE tells me:

DlvDebugger: dlv was not found on system PATH (hint: is Delve installed?)

**Comment by dspasibenko** [comment]
If somebody looking for the solution: Eventually found a workaround after looking at the plugin code. It turned out that the plugin expects to have dlv in $GOPATH/bin, but not somewhere in $PATH. If you have dlv there be sure that 
`sudo pkill taskgated`
is run after signing the dlv. This makes dlv run in LiteIDE

**Comment by Antergone** [comment]
@visualfc 从终端启动是可以识别的 但是从Application启动ide没有读系统的path

**Comment by joeblew99** [comment]
@visualfc Can you add this to the main readme ?


For Linux and Windows, the install instructions fro DLV put DLV in the $GOPATH/bin, and so LiteIde finds it automatically.
For OSX, its different, and if using the recommended Brew install method you need to do something extra.
https://github.com/derekparker/delve/tree/master/Documentation/installation

On OSX; do the standard brew install as recommend by the DLV install page.
Test it works from your bash with 
````
dlv
````

Then just copy it from the where brew puts it, into your $GOPATH/bin
````
cp /usr/local/Cellar/delve/0.12.1/bin/dlv $GOPATH/bin
````

You might also have to run 
````
sudo pkill taskgated
````

**Comment by visualfc** [comment]
edit current liteide env example darwin64-local.env
modify 
`PATH=$GOROOT/bin:$PATH`
to
`PATH=$GOROOT/bin:$PATH:/usr/local/bin`
save to reload env

**Comment by joeblew99** [comment]
for OSX thats not correct. at least not for me.. Please let me know if you disagree.
Here is my lideIDE env config.

# Golang compiler
# Installed using: "brew install go""
GOROOT=/usr/local/opt/go/libexec
GOPATH=$HOME/workspace/go

PATH=$PATH:$GOROOT/bin
PATH=$PATH:$GOPATH/bin

**Comment by visualfc** [comment]
PATH=$PATH:$GOROOT/bin:/usr/local/bin
