### ISSUE TITLE
最新版的在mac下的GDB不能debug了30.3

### ISSUE THREAD

**Issue by wtsoftware** [visualfc/liteide#726]
最新版的在mac下的GDB不能debug了，10000015^error,msg="During startup program terminated with signal ?, Unknown signal."

**Comment by visualfc** [comment]
直接在Mac的终端下测试用gdb能否调试。

**Comment by wtsoftware** [comment]
现在可以 了，要在最新的mac pro下进入恢复模式，把SIP服务关掉就行了。谢谢，但我的delve调试老是找不到配置DlvDebugger: dlv was not found on system PATH (hint: is Delve installed?)，我在命令行是是没问题的，也做过签名了。在env中指定了位置，但还是不能有Delve调试

**Comment by visualfc** [comment]
fix it
https://github.com/visualfc/liteide/commit/2a0656a8b180ddab02232fd378dde6f7167cec4a
确认是macosx上liteide的bug，dlv exec 输入文件名时使用了""号,在windows下无问题，在macosx上识别错误，我在macosx上一直dlv没配置成功。

**Comment by visualfc** [comment]
在macosx10.8虚拟机里测试了一下，liteide x30.2 发布时 dlv 的版本在macosx上exec支持""参数，最新的版本在osx上不支持""参数，而windows下仍支持的。
liteide主要是在windows下开发，其他平台测试不够。

**Comment by visualfc** [comment]
fixit
