### ISSUE TITLE
change key Ctrl+A event SelectAll to GotoLineStart valid

### ISSUE THREAD

**Issue by haormj** [visualfc/liteide#730]
I delete` SelectAll` key and change `GotoLineStart` to `Ctrl+A`,but it doesn't work well, When I press `Ctrl+A`,the effect is `SelectAll`.
But I change key `Ctrl+F` in `GotoNextCharater`, it works.before the event is `Find`.

**Comment by visualfc** [comment]
The ctrl+a is QPlainTextEdit internal key.
