### ISSUE TITLE
Fails to start on Ubuntu Studio 16.10

### ISSUE THREAD

**Issue by techtonik** [visualfc/liteide#732]
Linux binary `liteidex30.3.linux64-qt4.tar.bz2` fails to run:
```
liteide/bin$ ./liteide 
Cannot mix incompatible Qt library (version 0x40807) with this library (version 0x40801)
Aborted (core dumped)
liteide/bin$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"
```

Maybe pack it with something like this - http://snapcraft.io/ ?

**Comment by visualfc** [comment]
#243 
https://github.com/visualfc/liteide/issues/243

**Comment by techtonik** [comment]
@visualfc is it a hack?

**Comment by visualfc** [comment]
@techtonik liteidex30.3.linux64-qt4-system.tar.bz2 not include libQt*, use system qt4 library.
