### ISSUE TITLE
目录文件树中选中文件，按回车不能在编辑窗中打开源文件

### ISSUE THREAD

**Issue by npchp110** [visualfc/liteide#741]
操作系统：OSX 10.11.5
LiteIDE版本：X30.3
编译： 基于Qt 5.6.2 (64位)

在左侧目录文件树中选中文件，然后按回车键，希望能在右侧编辑窗口中立即打开选中的源文件。
如果该文件已经打开，希望切换到该文件的tab页。

**Comment by visualfc** [comment]
fixed https://github.com/visualfc/liteide/commit/ce66559808e6bdf4ca06996b91e5352ba73e7779
