### ISSUE TITLE
Mnemonics for Main Menu items

### ISSUE THREAD

**Issue by dogancelik** [visualfc/liteide#743]
Is it possible to add mnemonics for menu items?
If we want to close Lite IDE, we can do Alt + F, then press X to quit the program.

**Examples:**

* File
  * &New... = Press N to open New project.
  * E&xit = Press X to quit Lite IDE
* Recent
  * &File
  * F&older
  * &Clear History

Also there is no shortcut for quitting app like Ctrl + Q which is unused.

**Comment by visualfc** [comment]
please Alt+F move cursor and enter
windows add ctrl+q for exit
