### ISSUE TITLE
Allow replace with blank

### ISSUE THREAD

**Issue by jdoklovic** [visualfc/liteide#744]
When doing a file search/replace (and possibly other replaces) it doesn not allow you to replace the matches with nothing.

e.g. I want to replace "somepackage." with "" to remove it.

**Comment by visualfc** [comment]
https://github.com/visualfc/liteide/issues/767

**Comment by visualfc** [comment]
fix it https://github.com/visualfc/liteide/commit/7e18e70b12470813635ad4f5f28770ef803056c1
