### ISSUE TITLE
X30.3在mac10.12.3下卡顿

### ISSUE THREAD

**Issue by frankzougc** [visualfc/liteide#745]
2016款15寸macbook pro，系统版本10.12.3， liteide版本 X30.3。滚动、键盘上下左右 卡顿明显。

**Comment by visualfc** [comment]
liteide 有 qt4/qt5版本，建议更新到 liteide 的最新版本，并尝试使用 Qt4/Qt5 版本。Qt5对新系统兼容性更好。
