### ISSUE TITLE
跳转到声明功能反应用一段时间后反应很慢

### ISSUE THREAD

**Issue by kekemuyu** [visualfc/liteide#747]
开始用的时候反应挺快，过一段时间，反应变得很慢

**Comment by Tom-Kail** [comment]
我也遇到过，删除，重新下载一个就又好了。。

**Comment by visualfc** [comment]
如果 gotools 编译时的go版本低于当前使用的go版本就会出现此类情况，所以请保持使用最新的liteide或者是自行编译gotools
github.com/visualfc/gotools
