### ISSUE TITLE
Delete folder bug in project folder list

### ISSUE THREAD

**Issue by visualfc** [visualfc/liteide#75]
However I do have one issue that has been causing me a lot of headaches.  The file manager in projects it very good at picking up folder changes which is really good.  However if I delete a folder from outside LiteIDE (for instance a Go program or in explorer) then the folder still stays in the tree in LiteIDE (even if it initially disappears in explorer but reappears after a refresh).  Not only is the folder still in the file system but access is now denied to this folder's contents and security as it has been fully locked out but LiteIDE X.  The only way to fix the issue is to kill the LiteIDE or in the project file manager delete the folder which will brings up a message box saying there was an error deleting the folder while removing it.

The reason this is an issue is that some Go applications create temporary folders and delete them when rebuilding data.  Since they have no access to a folder which should not be there they then crash meaning every time the application wants to do this I must manually delete it in the IDE or kill the IDE.  Neither of which are good solutions.

Hopefully there is a fix for this as it is really a blocking issue for development, especially with frameworks like Revel which hot compile.

**Comment by hirikarate** [comment]
The issue does annoyingly remain in LiteIDE X30.2.
Reproduce steps:
- Open a folder in LiteIDE
- Expand folder tree to a certain subfolder
- Switch to Windows Explorer and delete that subfolder.
- Switch back to LiteIDE, right click > Reload Folder at tree root, and there... that subfolder is still in the tree.
- Switch again to Windows Explorer, that subfolder has appeared again, but this time it is totally locked, unless LiteIDE is killed.
- It doesn't release the lock even when File > Close All Folders.
