### ISSUE TITLE
LiteIDE not 100% portable

### ISSUE THREAD

**Issue by kravlost** [visualfc/liteide#750]
LiteIDE isn't perfectly portable, because it created a LiteIDE folder inside my user's AppData\Local folder, containing a "Hello World" go program - could it be changed to keep all this on the portable drive?

**Comment by dogancelik** [comment]
I'm glad someone opened this, I didn't want to be the first one to request it (2 weeks ago). I have 2 suggestions for LiteIDE to figure out it's portable:

1. emtpy `Portable` file in app folder
or
2. Or start LiteIDE.exe with "--portable"

Then LiteIDE would store config files under application folder.

**Comment by visualfc** [comment]
liteide - option - liteapp - Store settings to local ini file

**Comment by steronydh** [comment]
Brilliant, thanks!

**Comment by josephspurrier** [comment]
It doesn't look like the GoPlay files are portable. Even if you are using local storage, it stays in the AppData folder in Windows.

The goplay path is retrieved from here:
https://github.com/visualfc/liteide/blob/eddb51b5fd2c43836003ca52ab8db9ae4e588b78/liteidex/src/plugins/golangplay/goplaybrowser.cpp#L63

storagePath() is retrieved from here:
https://github.com/visualfc/liteide/blob/7bfa0821eb02e0b1e8219dcb5fc735fb5e823770/liteidex/src/liteapp/liteapp.cpp#L120

QStandardPaths::DataLocation points to AppData.

**Comment by josephspurrier** [comment]
@steronydh Can you reopen this ticket please?

**Comment by dogancelik** [comment]
As a temporary solution: there is a way to make it 100% Portable using [yaP](http://rolandtoth.hu/yaP/) but it requires admin privileges due to required NTFS permissions to create symlinks. [Although that can be altered too](https://superuser.com/questions/104845/permission-to-make-symbolic-links-in-windows-7)

Using a configuration like this:

```ini
; App\ and Data\ folders in Root
; App\ folder contains LiteIDE files
; Data\ folder contains "Roaming" and "Local" folders
; Root folder has LiteIDEPortable.exe & LiteIDEPortable.ini

[GENERAL]
application = App\bin\liteide.exe

[BEFORE]
symlink = %LocalAppData%\LiteIDE\ :: Data\Local\
symlink = %AppData%\LiteIDE\ :: Data\Roaming\
```

**Comment by steronydh** [comment]
@josephspurrier As requested.

**Comment by visualfc** [comment]
fixit liteapp start not create storage, only open goplay windows create

**Comment by josephspurrier** [comment]
@visualfc I'm sorry, I don't understand the question.
