### ISSUE TITLE
Windows update_pkg.cmd fails 

### ISSUE THREAD

**Issue by VhatAmI** [visualfc/liteide#751]
C:\Users\myale\Desktop\Go Workspace\liteide\build>update_pkg.cmd
GOROOT=C:\Go\
BUILD_ROOT=C:\Users\myale\Desktop\Go Workspace\liteide\build
LITEIDE_ROOT=C:\Users\myale\Desktop\Go Workspace\liteide\build\..\liteidex
.
go version go1.8 windows/amd64
update liteide tools ...
GOPATH=C:\Users\myale\Desktop\Go Workspace\liteide\liteidex;C:\Users\myale\Desktop\Go Workspace
get gocode ...
github.com/nsf/gocode (download)
get gotools ...
github.com/visualfc/gotools (download)
github.com/visualfc/gotools/vendor/github.com/pmezard/go-difflib (download)
package github.com/visualfc/gotools/vendor/github.com/pmezard/go-difflib/difflib: C:\Users\myale\Desktop\Go Workspace\liteide\liteidex\src\github.com\visualfc\gotools\vendor\github.com\pmezard\go-difflib\.git exists but is not a directory
github.com/visualfc/gotools/vendor/golang.org/x/tools (download)
package github.com/visualfc/gotools/vendor/golang.org/x/tools/go/ast/astutil: C:\Users\myale\Desktop\Go Workspace\liteide\liteidex\src\github.com\visualfc\gotools\vendor\golang.org\x\tools\.git exists but is not a directory

**Comment by visualfc** [comment]
fix to use godep
