### ISSUE TITLE
Active tab color is misleading

### ISSUE THREAD

**Issue by ckakman** [visualfc/liteide#754]
In the default theme of Liteide, the active tab's color is darker than inactive ones. This is, IMO, the exact opposite of how it should be. Please consider changing the default theme's tab colors.

**Comment by Yousefjb** [comment]
it works right in windows 10 version X30.3  
the active tab is lighter than inactive ones

**Comment by ckakman** [comment]
This is a screenshot from OSX:
<img width="341" alt="osx" src="https://cloud.githubusercontent.com/assets/4465324/23827703/7eb84f10-06ca-11e7-93a9-d6d6e71c3149.png">

**Comment by elfgoh** [comment]
I also get confused many times as a new user

**Comment by elfgoh** [comment]
@ckakman you may now choose default_macos.qss theme as a fix in trunk.

**Comment by elfgoh** [comment]
@visualfc is there a way to select the default theme based on operating system?

**Comment by visualfc** [comment]
macos select default_macos.qss theme
