### ISSUE TITLE
change request: Keyboard binding on Germany keyboard prevents typing []

### ISSUE THREAD

**Issue by joeblew99** [visualfc/liteide#758]
In golang you need to type the array symbol as "[]"
On a german keyboard, the [] symbol is made with ALT 5 and ALT 6.
But this keyboard binding is taken over by the LiteIDE, and so i can actually type [] in LiteIDE.

In LiteIDE, ALT 5 takes me to the "Debug Output" 
Alt 6, takes me to the "Go Source Query".

Its highly likely this is messing things up also fro other uses in Sweden and other countries where the same special ALT keys are used for programming in golang.

**Comment by dogancelik** [comment]
A similar problem is that I had to disable Ctrl+Alt+3 for Class View because AltGr (Ctrl+Alt) + 3 is # on my keyboard.

**Comment by visualfc** [comment]
fix it https://github.com/visualfc/liteide/commit/7182ee61ece3169d5ec63169d998576285da1fc1
