### ISSUE TITLE
No keyboard shortcut for Exit?

### ISSUE THREAD

**Issue by dogancelik** [visualfc/liteide#760]
I looked for "Exit" command shortcut in Options > Keyboard Tab but couldn't find, did I miss or does it not exist?

Usually programs have mnemonics to exit: Press <kbd>Alt+F</kbd> → Press <kbd>X</kbd> but Exit doesn't have mnemonic like:

```
┌ F̲ile              (under F)
├─ N̲ew…             (under N)
├─ O̲pen File…       (under O)
└─ Ex̲it             (under X)
```

**Comment by visualfc** [comment]
fixed
