### ISSUE TITLE
liteide巨好用，如果能优化全局搜索的一个小细节就更好了

### ISSUE THREAD

**Issue by Tom-Kail** [visualfc/liteide#761]
每次按alt+3 出现全局搜索界面，

Directory那一栏显示的是当前文件所在的路径，
例如   D:/gopath/src/project_name/controllers
但是每次我使用全局搜索都希望搜索整个project，于是我又手动删去路径中的controllers
最后的路径是 D:/gopath/src/project_name
如果和能锁定编译一样，可以锁定全局搜索的目录就完美了

**Comment by taobig** [comment]
+1

**Comment by visualfc** [comment]
fix 加入自动切换当前目录复选框  https://github.com/visualfc/liteide/commit/a6af572f33684a613613395f41d592f0b08a1508
