### ISSUE TITLE
Awk

### ISSUE THREAD

**Issue by svnpenn** [visualfc/liteide#769]
Please add Awk language highlighting, thank you.

**Comment by visualfc** [comment]
fixit https://github.com/visualfc/liteide/commit/361652013b5b2d35103c2c0cb5dd8405a2eaab67

**Comment by svnpenn** [comment]
i cant get it to recognize the new file - i downloaded the release - downloaded awk.xml - put awk.xml in

    liteide\share\liteide\liteeditor\color

even selected awk with

    view - options - liteeditor - editor color scheme

but the file still has no highlighting

**Comment by visualfc** [comment]
liteide/liteeditor/kate/awk.xml

**Comment by svnpenn** [comment]
thanks
