### ISSUE TITLE
Open a go file crashes the app on OSX

### ISSUE THREAD

**Issue by ingorichter** [visualfc/liteide#770]
Steps to repro
- open project folder
- select todo.go from file tree on the left hand side

**Current result:** Crash
**Expected result:** open the selected file in Editor

This happens on my MacBokPro with 10.11.6

![image](https://cloud.githubusercontent.com/assets/86214/24830510/879ef3e0-1c3c-11e7-8b49-dee0b43ef6db.png)

[LiteIDE_2017-04-08-091355_irichter-MBPro-1564.crash.zip](https://github.com/visualfc/liteide/files/907603/LiteIDE_2017-04-08-091355_irichter-MBPro-1564.crash.zip)
[LiteIDE_2017-04-08-091416_irichter-MBPro-1564.crash.zip](https://github.com/visualfc/liteide/files/907602/LiteIDE_2017-04-08-091416_irichter-MBPro-1564.crash.zip)
[LiteIDE_2017-04-08-091441_irichter-MBPro-1564.crash.zip](https://github.com/visualfc/liteide/files/907605/LiteIDE_2017-04-08-091441_irichter-MBPro-1564.crash.zip)
[LiteIDE_2017-04-08-091607_irichter-MBPro-1564.crash.zip](https://github.com/visualfc/liteide/files/907604/LiteIDE_2017-04-08-091607_irichter-MBPro-1564.crash.zip)

**Comment by chespinoza** [comment]
Hi, I'm curious about if you tried to install godoc before?
Greetings.

**Comment by ingorichter** [comment]
I tried it again on my new machine with OSX 10.12.4 and it seems to work on that machine. I can try it on my older machine (I need to restore the machine from a backup image). On my new machine, I get the same warning for the missing `godoc`, although it's installed and I can run it from the command line.

**Comment by visualfc** [comment]
Please provide todo.go for test
