### ISSUE TITLE
The interface starts with the local language

### ISSUE THREAD

**Issue by rgritti** [visualfc/liteide#787]
The IDE starts in the local language of the country where you are. The result is that I could not understand anything. To make everything worse, "Options" is under "View" and finding it in German is not easy :)

**Comment by ingorichter** [comment]
What do you mean with `country where you are`? You say, that the current system language is not used when the app launches? What is your suggestion to solve this?

**Comment by rgritti** [comment]
I mean for example that I don't speak German, but I was in Germany when I installed it,and it started in German. 
Well, it could ask the language at startup. Or start with English.
