### ISSUE TITLE
GOPATH Values Per Workspace

### ISSUE THREAD

**Issue by ardan-bkennedy** [visualfc/liteide#79]
Is there a way you could implement GOPATH values per workspace?  Depending what Workspaces I am working in the value of GOPATH needs to change.

**Comment by heavenlyhash** [comment]
+1, I need this too, badly.  No sane project shares a single GOPATH with the rest of the system; it's a guaranteed way to break builds on a daily basis when unrelated projects are allowed to clobber each other's library sources.

**Comment by heavenlyhash** [comment]
I'm hacked this by wrapping liteide in a shell script that does `HOME=/projects/$projectName liteide` and templates out the gopath with sed hacks.  I feel terrible about this, but it works.  On the off chance it's useful to anyone else out there, here's a snippet:

```bash
fakeHome="$litespace/$projConf"
mkdir -p "$fakeHome/.config/liteide/"
iniFile="$fakeHome/.config/liteide/liteide.ini"
# if the file doesn't exist yet, try to start with the one in the homedir.
# if it does, we'll just rewrite it; don't want to through away open files and such state.
[ -f "$iniFile" ] || cp "$HOME/.config/liteide/liteide.ini" "$iniFile" || touch "$iniFile"
# this rewrite is a hair tricky since the line of interest may not exist yet
# first we get rid of the line of interest if it does
# then we append the section header if it doesn't exist yet
# then we put the desired value right after the section header
sed -i '/^gopath=/d' "$iniFile"
grep '^\[liteide\]$' "$iniFile" >/dev/null || echo -e "\n[liteide]" >> "$iniFile"
sed -i 's/^\[liteide\]$/\[liteide\]\n'"gopath=${projectDir//\//\\/}\/${gopath//\//\\/}/" "$iniFile"
# yes, yes I did just template inputs to sed with bash.  WHAT COULD GO RONG

HOME="$fakeHome" liteide
```

(There's some variables you'd need to set for the above to work; https://gist.github.com/heavenlyhash/27db671839a21f5e936c has the rest of my project workspace autodetection; YMMV on that part.)

**Comment by visualfc** [comment]
build config add custom GOPATH setup

https://github.com/visualfc/liteide/commit/16c83824e471388ae68a9f74262d070468aa750e
https://github.com/visualfc/liteide/commit/30309baa7b693d9da7569576176354f4fc3818a5
