### ISSUE TITLE
Error running Go Playground

### ISSUE THREAD

**Issue by chespinoza** [visualfc/liteide#790]
**Version:**
Version: 31.1-macosx-qt5

**Output:**
Running...
Error: process failed to start.

**Log:**
11:47:27 LiteApp: Initializing
11:47:27 Load Setting: /Users/cespinoza/.config/liteide/liteide.ini
11:47:27 LiteApp: Loaded MIME folderproject.xml
11:47:27 LiteApp: Loaded MIME gopackage.xml
11:47:27 LiteApp: Loaded MIME liteeditor.xml
11:47:27 LiteApp: Loaded MIME qsqleditor.xml
11:47:27 WordApiManager: Loading /Applications/LiteIDE.app/Contents/Resources/packages
11:47:27 load word api: /Applications/LiteIDE.app/Contents/Resources/packages/go/funcs.api,/Applications/LiteIDE.app/Contents/Resources/packages/go/keyword.api,/Applications/LiteIDE.app/Contents/Resources/packages/go/types.api
11:47:27 load snippet api: /Applications/LiteIDE.app/Contents/Resources/packages/go/go.snippet.json
11:47:27 load word api: /Applications/LiteIDE.app/Contents/Resources/packages/lua/luabase.api,/Applications/LiteIDE.app/Contents/Resources/packages/lua/lualib.api,/Applications/LiteIDE.app/Contents/Resources/packages/lua/lualib5_annot.api
11:47:27 LiteApp: Loaded plugin/liteeditor
11:47:27 LiteEnv: Loaded environment files from /Applications/LiteIDE.app/Contents/Resources/liteenv
11:47:27 LiteEnv: load environment system
11:47:27 LiteApp: Loaded plugin/liteenv
11:47:27 LiteApp: Loaded plugin/quickopen
11:47:27 LiteApp: Loaded plugin/litefind
11:47:27 BuildManager: Loading /Applications/LiteIDE.app/Contents/Resources/litebuild
11:47:27 Execute commands: Loading /Applications/LiteIDE.app/Contents/Resources/litebuild/command
11:47:27 LiteApp: Loaded plugin/litebuild
11:47:27 LiteApp: Loaded plugin/golangast
11:47:27 LiteApp: Loaded plugin/welcome
11:47:27 LiteApp: Loaded plugin/rustedit
11:47:27 LiteApp: Loaded plugin/markdown
11:47:27 LiteApp: Loaded plugin/litetty
11:47:28 LiteApp: Loaded plugin/litedebug
11:47:28 LiteApp: Loaded plugin/jsonedit
11:47:28 LiteApp: Loaded plugin/gopresent
11:47:28 LiteApp: Loaded plugin/golangplay
11:47:28 LiteApp: Loaded plugin/golangpackage
11:47:28 LiteApp: Loaded plugin/golangfmt
11:47:28 GolangEdit: Not found guru, back to oracle!
11:47:28 LiteApp: Loaded plugin/golangedit
11:47:28 LiteApp: Loaded plugin/golangdoc
11:47:28 LiteApp: Loaded plugin/golangcode
11:47:28 LiteApp: Loaded plugin/gdbdebugger
11:47:28 LiteApp: Loaded plugin/filebrowser
11:47:28 LiteApp: Loaded plugin/fakevimedit
11:47:28 LiteApp: Loaded plugin/dlvdebugger
11:47:28 LiteEnv: reset system environment for "go env"
11:47:28 EnvManager: init load environment
11:47:28 LiteBuild: go environment changed
11:47:28 GolangDoc: found godoc at /usr/local/go/bin/godoc
11:47:28 GolangCode: go environment changed
11:47:28 GolangCode: Found gocode at /Applications/LiteIDE.app/Contents/MacOS/gocode
11:47:28 HtmlWidgetFactory: QTextBrowser
11:47:28 DefaultHtmlWidgetFactory: QTextBrowser
11:47:28 LiteApp: Finished loading

**Comment by visualfc** [comment]
fix https://github.com/visualfc/liteide/commit/eec2247304b4e9f4cca72cada68d7a3985954b14
now can swith system.env to drawin64_local.env and modify GOROOT to go intall path
