### ISSUE TITLE
Synchronization with editor

### ISSUE THREAD

**Issue by fadiasamara** [visualfc/liteide#792]
The folder synchronization does not work.
I have reinstalled and installed, has not resolved the issue.
X31/Qt 5.6.2(32bit)

# native compiler windows 386

#GOROOT=c:\go
#GOBIN=
#GOARCH=386
#GOOS=windows
#CGO_ENABLED=1

#PATH=c:\mingw32\bin;%GOROOT%\bin;%PATH%

#LITEIDE_GDB=gdb
LITEIDE_MAKE=mingw32-make
LITEIDE_TERM=%COMSPEC%
LITEIDE_TERMARGS=
LITEIDE_EXEC=%COMSPEC%
LITEIDE_EXECOPT=/C

**Comment by fadiasamara** [comment]
tried with the qt4 same issue.

**Comment by fadiasamara** [comment]
@visualfc do you have an answer for this question?

**Comment by visualfc** [comment]
please provide a description of the picture

**Comment by fadiasamara** [comment]
its not an issue any more, thanks @visualfc
