### ISSUE TITLE
liteide能否支持系统gopath手动添加或清除

### ISSUE THREAD

**Issue by xkeyideal** [visualfc/liteide#793]
golang1.8会自动设置gopath为$HOME/go，windows下还无法删除这个默认配置，又不想在环境变量中设置一个去替换，但是看着这个默认的gopath很不爽

**Comment by vizee** [comment]
朋友, liteide 有自己的环境变量配置的

**Comment by visualfc** [comment]
已加入。https://github.com/visualfc/liteide/commit/d4e2b89805fe7c8743c3576434369bdc4e6b12e5

**Comment by xkeyideal** [comment]
@vizee 你应该是没理解我说的

**Comment by xkeyideal** [comment]
@visualfc 谢谢
