### ISSUE TITLE
How to deal with build tags?

### ISSUE THREAD

**Issue by jdoklovic** [visualfc/liteide#797]
I use build tags to separate my unit tests from my integration tests.
something like:
```go
// +build integration
```
at the top of my test file.
When I do this, liteide stops auto-compiling the file and most of the code features don't work. e.g. I can't jump to declarations, I can't get docs using F1, etc.
Is there a way to configure the editor to be aware of build tags?

**Comment by visualfc** [comment]
menu/toolbar build - build config 
BUILDARGS setup -i -tags "integration"
build pass, but gotools now not work.

**Comment by visualfc** [comment]
#453

**Comment by visualfc** [comment]
https://github.com/visualfc/liteide/commit/b9ae6fc23a9e811debe35876ccc14320eccb6fc5
build config add BUILDFLAGS for custom share-value

**Comment by visualfc** [comment]
fix it , build config add  share BUILDFLAGS for add -tags ...
golangedit find/jump use custom BUILDFLAGS or BUILDATRGS -tags
https://github.com/visualfc/liteide/commit/be2d7fdf5f4d794ddd9c19994068592bfaa1fde5
