### ISSUE TITLE
how to configure Real-time preview of the right sidebar

### ISSUE THREAD

**Issue by jsplyy** [visualfc/liteide#799]
The default style is :
![image](https://cloud.githubusercontent.com/assets/3600912/26281976/76395cde-3e39-11e7-8b7a-6e6885f31c5c.png)

I want to use this style：
![image](https://cloud.githubusercontent.com/assets/3600912/26281978/8d479788-3e39-11e7-8df4-6e0381f16321.png)

**Comment by visualfc** [comment]
liteide option -> liteapp -> style : SpliterStyle

**Comment by jsplyy** [comment]
@visualfc Thanks a lot.
It need to restart IDE after Switching.
Expect to see better.
