### ISSUE TITLE
希望支持代码的彩色高亮

### ISSUE THREAD

**Issue by jthmath** [visualfc/liteide#800]
目前的染色方案比较单一。希望 liteide 可以为关键字、类型、变量、函数（和方法）、字符串、注释染上不同的颜色，便于区分，提高阅读代码的效率。

**Comment by discoverfly** [comment]
可以调整为一个更适合的配色方案：
Preferences-> LiteEditor -> 字体和颜色 -> 编辑器颜色方案 -> gist-github.xml

或者自己修改配色方案。
