### ISSUE TITLE
Mac 10.12 系统 修改编译参数，保存失败

### ISSUE THREAD

**Issue by phoenix043030** [visualfc/liteide#801]
非/Users/用户名路径下，LiteIDE相关参数定位到/private下，修改编译参数，路径为只读，无法保存

**Comment by haoweishow** [comment]
在LiteIDE的软件包下可以直接修改，文件路径可能不是很准确：/Application/LiteIDE.app/Content/Resource/Liteenv/system.env

PS：不知道为什么，通过这种方式修改后，不能生效，需要重启OS。

**Comment by visualfc** [comment]
如果出现无法修改参数情况，可以将 LiteIDE 解压至  /Users/用户路径 下
