### ISSUE TITLE
X32.1 package浏览 显示错误号62097的问题

### ISSUE THREAD

**Issue by pathletboy** [visualfc/liteide#803]
启动liteide， package浏览框内显示Load Package Error 62097
有时候等待一段时间能加载出正确的GOPATH，有时候就一直这个界面。
![tim 20170614075937](https://user-images.githubusercontent.com/1545207/27109830-c24f8912-50d7-11e7-8961-2a63bafe9823.png)

**Comment by pobearm** [comment]
我的mac下, 也出现同样的问题,  是在我修改GOPATH设置的时候, 会触发重新加载文档, 然后提示这个错误.
我还有一个问题, 我的[系统GOPATH]里面, 显示的是一个错误的路径:
"/User/pobear/go"
这个路径是从哪里读取出来了的?  
我的bash里面, 没有设置过这个目录.
希望能让我找到修改的地方谢谢.

**Comment by visualfc** [comment]
/User/pobear/go 是 go1.8 新增的默认GOPATH路径

**Comment by visualfc** [comment]
package 浏览是调用 go list -e ...
可以在liteide 的执行命令中运行看有什么错误.

**Comment by pathletboy** [comment]
```go list -e ...```
是没有问题的，感觉好像go list -e ...的时候比较慢，显示的内容就是楼顶的那图。

**Comment by visualfc** [comment]
实际用的是 go list -e -json ...

**Comment by visualfc** [comment]
fixed
https://github.com/visualfc/liteide/commit/4f5d6de520008ffd85d9ac82d15627ff70b25dc2
