### ISSUE TITLE
X32.2 mac版跳转速度变得很慢

### ISSUE THREAD

**Issue by fugr** [visualfc/liteide#807]

**Comment by fugr** [comment]
代码查找使用也慢了

**Comment by fugr** [comment]
经常出现：
15:49:48 find def error: 进程崩溃或被终止

**Comment by visualfc** [comment]
go version
liteide qt version

**Comment by fugr** [comment]
go version devel +952ecbe Wed Jun 14 21:44:01 2017 +0000 darwin/amd64 
go1.9beta
更新gocode后解决了

**Comment by visualfc** [comment]
go get github.com/visualfc/gotools
cp gotools liteide/bin
如果是go1.9 将 gotools 也更新后下。
