### ISSUE TITLE
linux 的x32版本每个包进行编译的时候都会出现一个对象文件，

### ISSUE THREAD

**Issue by elvin-du** [visualfc/liteide#810]
linux 的x32版本每个包进行编译的时候都会出现一个对象文件，每次都是手工BUILDARGS 从-i -o $(TARGETNAME)改成-i才不会出现这个对象文件，有地方可以统一配置都不产生对象文件吗？

**Comment by visualfc** [comment]
please download x32-2 release version.
http://sourceforge.net/projects/liteide/files

**Comment by elvin-du** [comment]
谢谢
