### ISSUE TITLE
This link is dead

### ISSUE THREAD

**Issue by jmfgdev** [visualfc/liteide#812]
https://github.com/visualfc/liteide/blob/master/liteidex/deploy/welcome/cn/guide.md

It's listed in readme.md but it seems to have been deleted

**Comment by visualfc** [comment]
please
https://github.com/visualfc/liteide/blob/master/liteidex/deploy/welcome/zh_CN/guide.md

where is the link?

**Comment by visualfc** [comment]
fixed https://github.com/visualfc/liteide/blob/master/liteidex/deploy/welcome/en/guide.md
thanks
