### ISSUE TITLE
希望支持 git 版本管理

### ISSUE THREAD

**Issue by minicase** [visualfc/liteide#817]
希望支持 git 版本管理 这样就更方便了

**Comment by Schr0dingerCat** [comment]
@minicase 多开个terminal，使用git命令，不会觉得麻烦呀

**Comment by minicase** [comment]
我如果感觉命令行效率高的话，我还会用liteide吗？

**Comment by xgdgsc** [comment]
不会用那么多GUI的git软件吗

**Comment by minicase** [comment]
有命令行，为什么还要图像编辑器呢？
有图形编辑器为什么还要ide呢？
