### ISSUE TITLE
单独一个package无法自动提示

### ISSUE THREAD

**Issue by elvin-du** [visualfc/liteide#818]
一个项目中的别的package都可以自动提示，就一个package无法自动提示．liteide是最新的３２．２版本，os系统Ubuntu 14.04.5 LTS

**Comment by visualfc** [comment]
没理解什么意思，但可以试一下编译工具上的 go get 获取依赖pkg生成.a文件供gocode提示。

**Comment by elvin-du** [comment]
已经解决了，不是liteide的问题，是package引用的别的package里面．a文件中有异常的，所以gocode每次解析的时候都崩溃，所以无法提示，删除所有的pkg目录，重新编译就可以了．谢谢您的即时回复．
