### ISSUE TITLE
请教2个liteide使用遇到的的问题

### ISSUE THREAD

**Issue by widon1104** [visualfc/liteide#819]
1）怎么给编译出来的可以执行文件传递参数运行啊？

2）程序使用input.Scan获取输入，输入了一些字符以后，在liteide编译输出框里面按ctrl+d没有反应，无法终止输入，在终端里面就可以，请问如何终止输入啊？

**Comment by visualfc** [comment]
编译配置中的 TARGETARGS 可以指定运行参数

编译输出框中不支持Ctrl+D，可以先编译，然后使用编译工具栏上的运行在终端 RunTerm 进行
