### ISSUE TITLE
LiteIDE know TODO : , but do not know TODO:

### ISSUE THREAD

**Issue by AnotherGoogleFan** [visualfc/liteide#822]
In comment, if you use
// TODO : 
it can be bright. But if you use 
// TODO:
it doesn't.
See this picture.

![liteide](https://user-images.githubusercontent.com/6881899/28064412-24403014-6667-11e7-8830-971d4f131882.jpg)

**Comment by visualfc** [comment]
fixed 
https://github.com/visualfc/liteide/commit/2f716a02cc4380a2f6c7d7624d5467bb7a03ca93
