### ISSUE TITLE
Debug时的Working directory在X32.1版本中不起作用

### ISSUE THREAD

**Issue by polaris007** [visualfc/liteide#823]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
Version: X32.1
Build: Based on Qt 4.8.5 (64 bit)

### What version of Go are you using (`go version`)?
go version go1.8.1 linux/amd64

### What operating system and processor architecture are you using(`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GORACE=""
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build063131906=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
"Debug External Application"时设置了"Working directory"，但是发现不生效，下面代码:
cwd, err := os.Getwd()
"cwd"得到的值是liteide/bin的目录。同样的代码用X31版本就能得到正确路径。Debugger是delve

If possible, provide a recipe for reproducing the error.

### What did you expect to see?
os.Getwd()得到"Working directory"设置的路径

### What did you see instead?
os.Getwd()得到了liteide/bin目录位置

**Comment by visualfc** [comment]
fixed https://github.com/visualfc/liteide/commit/201a4ceba72418b8616f5b655ac0eea65f182092
