### ISSUE TITLE
Markdown 文本预览问题

### ISSUE THREAD

**Issue by wzhuzhu** [visualfc/liteide#824]
## 版本:
 * LiteIDE  x32.2
## 问题
  在编辑Markdown文件的时候，点击HTML预览，在页面样式选择中只有: 
 * 纯HTML
 * textbrowser.css
没有出现: GitHub2.css / GitHub_Style.css 等这样的页面样式。
在目录: `share/liteide/packages/markdown/css` 有这样的文件存在.

请问是什么地方的问题？

**Comment by visualfc** [comment]
LiteIDE的Qt4版本有QWebKit库支持，允许选择css样式。
LiteIDE的Qt5版本只使用内置的QHtmlBrower，比较简单，只支持基本样式。
