### ISSUE TITLE
copy/cut full line when nothing is selected in editor

### ISSUE THREAD

**Issue by rgl** [visualfc/liteide#83]
It would be great if we could copy (Ctrl+C) or cut (Ctrl+X) a full line (the current line that has the caret) when nothing is selected.

**Comment by visualfc** [comment]
fixed

**Comment by rgl** [comment]
was this really fixed? I'm trying it in X32, and neither of the shortcuts work when there is nothing selected.

**Comment by visualfc** [comment]
Sorry, Different but editor add copyLine and cutLine action.

**Comment by rgl** [comment]
Even if I set those actions to the same keyboard shortcuts as copy and cut, it does not seem to work.

Can the code be changed to also support this behavior? That is, Ctrl+C would copy the entire line when there is nothing selected. Ctrl+X would cut the entire line when there is nothing selected.
