### ISSUE TITLE
不支持 go的 vendor 目录

### ISSUE THREAD

**Issue by imkos** [visualfc/liteide#837]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
3.2.2

### What version of Go are you using (`go version`)?
1.9

### What did you do?

If possible, provide a recipe for reproducing the error.

### What did you see instead?

verdor 目录中有依赖库，但无法进行编译

**Comment by visualfc** [comment]
liteide 从 x28开始支持go1.5的GO15VENDOREXPERIMENT设置, 从x30开始默认开启vendor,取消GO15VENDOREXPERIMENT变量设置
请检查GOPATH设置和项目vendor目录，确保依赖库存在，根据编译提示进行操作。

**Comment by dongjiang1989** [comment]
@visualfc  现在使用的是X32.1  如何使工程可以link 到vendor中的库？
默认只是找了gopath/src下的库，没有找vendor中的库
