### ISSUE TITLE
It overwrote liteide\share\liteide\liteeditor\color\default.xml

### ISSUE THREAD

**Issue by wateverq** [visualfc/liteide#839]
### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
liteidex32.2.windows-qt5

### What version of Go are you using (`go version`)?
1.9

### What operating system and processor architecture are you using(`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\m\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?
I [changed liteide\share\liteide\liteeditor\color and restarted] 10 times and it was ok. The 11th time it overwrote default.xml with a fresh one and thus wasted like 20 minutes of my work.

### What did you expect to see?
It should ask before it overwrites my work.

### What did you see instead?
It overwrote a file worth 20 minutes of tweaking nice colors.

**Comment by visualfc** [comment]
liteide does not automatically reset the color/default.xml file
