### ISSUE TITLE
Possibly bug? syntax highlighting - "Function" keywords

### ISSUE THREAD

**Issue by sarbash** [visualfc/liteide#840]
>LiteIDE X32.2
>Qt 4.8.7 (64 bit)
>go version go1.7.4 linux/amd64
>Ubuntu 17.04
>GOARCH="amd64"

I don't know if that's what was implied but should not the option <style name="Function"> in `solarized.xml` highlight functions in a code?
ATM they all are the same color as a common text.

I don't see anything has colored like that:
```
<style name="Function" foreground="#859900"/>
```
except "Predeclared" and "BuiltinFunc".

Thank you.

**Comment by visualfc** [comment]
This "Function" parser has not been implemented yet
