### ISSUE TITLE
无法启动delve的问题

### ISSUE THREAD

**Issue by yanllllk** [visualfc/liteide#842]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?

32.2
### What version of Go are you using (`go version`)?

1.83
### What operating system and processor architecture are you using(`go env`)?

win7 x64
### What did you do?

If possible, provide a recipe for reproducing the error.
发现这个liteIDE不能放在长名字目录里.
比如C:\Program Files (x86)\liteide
这种长名字录下,就无法启动delve.

直接放在c:\liteide 下,就一切正常.

**Comment by visualfc** [comment]
delve 可以放在GOPATH/bin目录或者是PATH目录中。
