### ISSUE TITLE
LiteIDE编辑添加的行末尾有^M符号

### ISSUE THREAD

**Issue by widon1104** [visualfc/liteide#843]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
x32.1

### What version of Go are you using (`go version`)?
1.9

### What operating system and processor architecture are you using(`go env`)?
ubuntu16.04 mate

### What did you do?

If possible, provide a recipe for reproducing the error.

### What did you expect to see?
使用liteide添加的行，行尾有^M符号，请问如何去掉啊？

### What did you see instead?
widon@widon-desktop:~/uCloudChain$ git diff
diff --git a/src/peer/chat/chat.go b/src/peer/chat/chat.go
index 3f891fe..628a7a4 100755
--- a/src/peer/chat/chat.go
+++ b/src/peer/chat/chat.go
@@ -136,7 +136,10 @@ func MsgPrepare(msgType pb.Message_Type, arg interface{}, bizID string) (*pb.Mes
  **/
 func SendMsg(msg *pb.Message, address string) (*pb.Message, error) {
        // 消息发送
+       identifier, err := msp.GetIdentifier(address)^M
+       fmt.Println("identifier: ", identifier)^M
        address = fmt.Sprintf("%s:%s", address, chatPort)
+       fmt.Println("identifier: ", identifier)^M

**Comment by visualfc** [comment]
这是使用了 windows 上换行符\r\n的原因。 LiteIDE-编辑菜单 设置-使用Unix换行符\n 自动转换为unix换行符。
另：建议升级到 liteide x32.2 支持go1.9 (之前版本不支持go1.9)
