### ISSUE TITLE
按Ctrl+鼠标左键无法跳转到函数定义处

### ISSUE THREAD

**Issue by widon1104** [visualfc/liteide#846]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X32.2

### What version of Go are you using (`go version`)?
go1.9

### What operating system and processor architecture are you using(`go env`)?
ubuntu16.04 64bit

### What did you do?

If possible, provide a recipe for reproducing the error.
很奇怪，不是所有地方都无法跳转，无法跳转的函数，我把他删除，然后重写，函数补全都是正常的，所以可以判断gopath是正确设置了，包是能够找到的

**Comment by widon1104** [comment]
我知道怎么重现这个问题了，在代码的同级目录里面新建一个文件，只写一行代码：package 另一个包名
然后在这个目录下找代码定义的功能就失效了
vim下使用vim-go没有这个问题

**Comment by visualfc** [comment]
目前 liteide 的 gotools 只支持同一目录在同一包名称或者是pkg_test的形式。

**Comment by Ainimomoda** [comment]
1.在工程代码中不要任意的修改代码目录结构否则会无法跳转。
2.是否不小心破坏了代码，如：不小心删改了代码也会导致无法跳转，建议重新clone.
