### ISSUE TITLE
liteide 双击大纲空白处导致crash（必现）

### ISSUE THREAD

**Issue by widon1104** [visualfc/liteide#848]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X32.2

### What version of Go are you using (`go version`)?
go1.9

### What operating system and processor architecture are you using(`go env`)?
ubuntu16.04 mate

### What did you do?

If possible, provide a recipe for reproducing the error.
打开一个稍微（复杂一点的）go源文件，然后展开一个实现了方法的类型，这时候双击大纲窗口的空白处liteide就会crash，必现
Thread 1 "liteide" received signal SIGSEGV, Segmentation fault.
0x00007fffcb6b6cee in AstWidget::doubleClicked(QModelIndex) () ...

**Comment by visualfc** [comment]
thanks
