### ISSUE TITLE
Liteide Trojan

### ISSUE THREAD

**Issue by fadiasamara** [visualfc/liteide#850]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
x32.2 windows qt5

### What version of Go are you using (`go version`)?
go 1.9 windows/amd64

### What operating system and processor architecture are you using(`go env`)?
Windows 7 Enterprise

### What did you do?
Jut opening the  Liteide by click on liteide.exe

### What did you expect to see?
the Liteide editor

### What did you see instead?
Message from security center:

Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items: 
file:C:\liteide\lib\liteide\plugins\litebuild.dll

Get more information about this item online.

**Comment by visualfc** [comment]
Download from:
    http://sourceforge.net/projects/liteide/files
    https://github.com/visualfc/liteide/releases/latest
Replace antivirus software or build liteide from source.

**Comment by jingniao** [comment]
is also reported by windows 10 64bit by all most new version(qt4 and qt5) download from github.com releases(I can be sure the package is official version).
sha256 info:
![sha256](https://user-images.githubusercontent.com/2255761/31050332-d84e1218-a679-11e7-9714-c699f6a31ffe.PNG)

after unpack the zip file, windows MSE report the Trojan:Win32/Azden.A!cl .
![screenshot](https://user-images.githubusercontent.com/2255761/31050312-6788779e-a679-11e7-81ef-f47123ed0cb2.PNG)

**Comment by fadiasamara** [comment]
@visualfc I have rebuilt the package, installed a different packages and the issue still there.

I can't turn off the Windows security system as this a builtin for the Windows distribution mages...

**Comment by visualfc** [comment]
http://liteide.org/cn/doc/install/ 可以从源码编译试一下。
