### ISSUE TITLE
源码查找接口实现类

### ISSUE THREAD

**Issue by wtsoftware** [visualfc/liteide#853]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?

32.2
### What version of Go are you using (`go version`)?

1.8
### What operating system and processor architecture are you using(`go env`)?

mac
### What did you do?
dev
If possible, provide a recipe for reproducing the error.

**Comment by wtsoftware** [comment]
什么时候能实现，在GOPATH中查找接口的实现类呢，现在工程大了查找接口实现类。只能通过搜索方式 ，太复杂了!

**Comment by widon1104** [comment]
vim-go 的:GoCallees用guru实现了类似的功能啊，我觉得可以做啊

**Comment by visualfc** [comment]
fixed
https://github.com/visualfc/liteide/commit/e90ef92caa19f3a9816ff5b0a0d2832886d1a707

**Comment by visualfc** [comment]
liteide 的 SourceQuery 使用 guru(如未安装，使用oracle） 实现 implement 查找, 在 https://github.com/visualfc/liteide/commit/e90ef92caa19f3a9816ff5b0a0d2832886d1a707 中加入了 GOPATH全局查找功能。
