### ISSUE TITLE
MAC下终端安装错误

### ISSUE THREAD

**Issue by RPGLiker** [visualfc/liteide#854]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
Qt 5 brew安装

### What version of Go are you using (`go version`)?
1.9.1

### What operating system and processor architecture are you using(`go env`)?
macOS

### What did you do?
./build_macos_qt5.sh 报错

If possible, provide a recipe for reproducing the error.
SkyHarutedeMacBook-Pro:build skyharute$ ./build_macos_qt5.sh
build liteide
GOROOT=
BUILD_ROOT=/Users/skyharute/.Trash/liteide/build/liteide/build
LITEIDE_ROOT=/Users/skyharute/.Trash/liteide/build/liteide/build/../liteidex
.
qmake liteide ...
.
./build_macos_qt5.sh: line 24: qmake: command not found
error, qmake fail

**Comment by visualfc** [comment]
export QTDIR= ...
