### ISSUE TITLE
建议：增强delve调试时值的显示

### ISSUE THREAD

**Issue by ismlsmile** [visualfc/liteide#863]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
32.2

### What version of Go are you using (`go version`)?
1.8.3

### What operating system and processor architecture are you using(`go env`)?
Win10

### What did you do?

If possible, provide a recipe for reproducing the error.

### What did you see instead?

 使用delve调试时，对于普通字符串、数字的字段，变量那边显示的没问题，但对于list、map之类的数据结构，只能显示类型，无法显示内部的值

**Comment by visualfc** [comment]
fixed, now dlvdebugger plugin use roc mode
