### ISSUE TITLE
linux下源码编译出的liteide中文全部无法显示

### ISSUE THREAD

**Issue by widon1104** [visualfc/liteide#864]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
x32.2

### What version of Go are you using (`go version`)?
go1.9

### What operating system and processor architecture are you using(`go env`)?
ubuntu17.10

### What did you do?

If possible, provide a recipe for reproducing the error.
qt 4.8.6是这样编的，好像没有编webkit不知道有什么影响
qt-everywhere-opensource-src-4.8.6$ ./configure -openssl -nomake examples -nomake docs -nomake demos
然后liteide的编法是完全按照 http://liteide.org/cn/doc/install/ 下的linux项来编的，
**但是编出来的可执行文件运行起来，中文都无法显示**
注：自己编译是因为现在liteide fakevim插件有很多bug，我是想尝试一下自己改一下看下好改不。

请问一下你的qt和liteide是如何编译的啊？

**Comment by visualfc** [comment]
ubuntu 可以用 apt-get 安装 Qt 试试

**Comment by widon1104** [comment]
sudo apt-get install libfreetype6-dev
sudo apt-get install libfontconfig1-dev
./configure -openssl -nomake examples -nomake docs -nomake demos -webkit -fontconfig
加上fontconfig这样编译qt就没问题了
