### ISSUE TITLE
liteide有时候自动补全出不来，有没有快捷键调出自动补全啊

### ISSUE THREAD

**Issue by widon1104** [visualfc/liteide#865]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
x33

### What version of Go are you using (`go version`)?
go1.9

### What operating system and processor architecture are you using(`go env`)?
ubuntu17.10

### What did you do?

If possible, provide a recipe for reproducing the error.
liteide有时候自动补全出不来，有没有快捷键调出自动补全啊
vim下可以使用ctrl+n调出自动补全，请问liteide有没有这样的快捷键啊
如果没有的话可否添加啊

**Comment by visualfc** [comment]
可以更改，设置－LiteApp-键盘 Editor/CodeComplete 默认是Ctrl+空格
