### ISSUE TITLE
Linux x64 build with Go1.9.1 and Qt5.9.1 yields "libpng warning" when ran as ./liteide

### ISSUE THREAD

**Issue by CraigAD** [visualfc/liteide#867]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X33 -- Based on Qt5.9.1 (64 bit)
LD_LIBRARY_PATH=/opt/Qt/5.9.1/gcc_64/lib/:
QTDIR=/opt/Qt/5.9.1/gcc_64
QT_PLUGIN_PATH=/opt/Qt/5.9.1/gcc_64/lib/plugins/
PATH=/opt/Qt/5.9.1/gcc_64/bin/:$PATH
PKG_CONFIG_PATH=/opt/Qt/5.9.1/gcc_64/lib/pkgconfig/:

### What version of Go are you using (`go version`)?
go version go1.9.1 linux/amd64

### What operating system and processor architecture are you using(`go env`)?
Linux Ubuntu 17.10 (Kubuntu)
x86_64
4.13.0-17-generic
KDE Plasma 5.11.2

### What did you do?
$ cd liteide/build
$ ./update_pkg.sh
$ ./build_linux_qt5.sh

## Run it: ##
$ cd ~/liteide/build/liteide/bin
$ ./liteide
If possible, provide a recipe for reproducing the error.
$ cd ~/liteide/build/liteide/bin
$ ./liteide

### What did you expect to see?
cad@cad-VN7:~/workspace/liteide/build/liteide/bin⟫ ./liteide

### What did you see instead?
cad@cad-VN7:~/workspace/liteide/build/liteide/bin⟫ ./liteide
libpng warning: iCCP: profile 'ICC profile': 'GRAY': Gray color space not permitted on RGB PNG
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: profile 'ICC profile': 'GRAY': Gray color space not permitted on RGB PNG
libpng warning: iCCP: profile 'ICC profile': 'GRAY': Gray color space not permitted on RGB PNG
libpng warning: iCCP: profile 'ICC profile': 'GRAY': Gray color space not permitted on RGB PNG
libpng warning: iCCP: profile 'ICC profile': 'GRAY': Gray color space not permitted on RGB PNG

### Troubleshooting info and other thoughts
Current installed: 
libpng12-0 1.2.54-1ubuntu1
libpng-tools 1.6.34-1
libpng-dev 1.6.34-1
libpng16-16 1.6.34-1
libpng16-16:i386 1.6.34-1

Status of the LiteIDE GUI -- seems to run fine with out further errors.

**Comment by CraigAD** [comment]
cad@cad-VN7:~/workspace/liteide/build⟫ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/cad/Golang"
GORACE=""
GOROOT="/usr/lib/go-1.9"
GOTOOLDIR="/usr/lib/go-1.9/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build791846561=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

**Comment by CraigAD** [comment]
I found this description of the problem that suggests a possible solution:
https://stackoverflow.com/questions/43374187/qt-open-a-jpg-file-with-warning-image-format-not-supported

**Comment by visualfc** [comment]
thanks
