### ISSUE TITLE
希望可以增加ctrl+x 剪行 以及 ctrl+d 複選取同字

### ISSUE THREAD

**Issue by learnmove** [visualfc/liteide#868]
liteIDE學習golang很快速又方便
如果加上這兩個功能會變得更加強大

**Comment by visualfc** [comment]
有剪切行的操作，快捷键可以自行定义
ctrl+d复选同字是什么意思？

**Comment by shenqisoft** [comment]
同求，CTRL+X用的还是很频繁的。不知道怎么设置，设置了也没生效。而且默认设置好的SHIFT+DEL也不起作用。

**Comment by visualfc** [comment]
加入 ctrl+x剪切行支持. please download x35.3 and check.
