### ISSUE TITLE
Program crash when replacing

### ISSUE THREAD

**Issue by DennisMao** [visualfc/liteide#869]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
LiteIDE X33 , Qt 5.6.3 32bit

### What version of Go are you using (`go version`)?
go 1.9.2

### What operating system and processor architecture are you using(`go env`)?
Win 10 / 64bit

`
set GOARCH=amd64
set GOBIN=F:\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=F:\Go\
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build338011747=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
`

### What did you do?
The program crashed when i chose a word and click the single replace button normally.
Otherwise,the replace all function has the same problem which i has submitted
If possible, provide a recipe for reproducing the error.

### What did you expect to see?
Replace words normally when click the button.

### What did you see instead?
The program crashed and a warnning dialog poped up.

**Comment by visualfc** [comment]
Please provide pictures and test code

**Comment by visualfc** [comment]
liteide x33.2 fix some find bug. please update to latest version x33.2 and test.

**Comment by DennisMao** [comment]
fixed
