### ISSUE TITLE
find usage error: error import path <nil>

### ISSUE THREAD

**Issue by martin-flaregames** [visualfc/liteide#870]
Since my last update the "Find Usage" feature is failing and cannot figure out what is wrong with it.

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
`LiteIDE X / X32`

### What version of Go are you using (`go version`)?

Go : `go version go1.9.2 linux/amd64`
Qt : `Qt 5.9.2`

### What operating system and processor architecture are you using(`go env`)?

Running Arch Linux, `uname -a` is reporting:

```
Linux xxx 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux
```
`go env` is reporting:

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xxx/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build260199104=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

Some weeks ago a new liteIDE version and a new Go version where installed, since then the issue appeared.

When right clicking on an element in the text editor and then selecting "Find Usages" an error message is written into the "Event Log" panel.

```
11:10:41 find usage error: error import path <nil>
```

### What did you expect to see?

The Panel with the usage of the selected element (with the option to replace / refactor them)

### What did you see instead?

an error message is written into the "Event Log" panel.

```
11:10:41 find usage error: error import path <nil>
```

**Comment by martin-flaregames** [comment]
May be it is worth noting that at after the update, the LiteIDE is shown but takes some seconds to load the project. In the meantime only the bare IDE is displayed.

**Comment by visualfc** [comment]
please update x33 and test

**Comment by maj-o** [comment]
I had the same issue.
Updating to current git version X33 solved this.
(It also solved broken (only local) code completion.)

**Comment by xgdgsc** [comment]
I get this error on X33.3 with manjaro.
