### ISSUE TITLE
Add test with TESTARGS shortcut/dialog

### ISSUE THREAD

**Issue by bep** [visualfc/liteide#875]
When I'm working on a bug fix/part of a bigger project, I almost always filter my tests -- and I switch a lot (run 1, run all ...).

So I set the custom `TESTARGS`, which works fine, but is a 5 step operation to get to `-run TestSomeSpecificTest`.

It would be cool if I could do `cmd + shift + T` or something and get a dialogue where I could change that property before test execution.

**Comment by visualfc** [comment]
ctrl + `/cmd+` to show execute toolbar, input go test ...  and enter to run .
the execute toolbar combox command list -> litebuild/command/go.api
you can write some go command to this file.

**Comment by bep** [comment]
So much I don't know... Thanks!
