### ISSUE TITLE
feature request：add syntax highlight like goland

### ISSUE THREAD

**Issue by fastfading** [visualfc/liteide#876]
the biggest disadvantage of liteide compare to goland is syntax highlight
liteide only have a simple highlight system

I know it is not easy , however if liteide can add 
function  ,  const , struct   highlight , 
 it could handle most cases.

![image](https://user-images.githubusercontent.com/8351732/33591742-3c92e2e6-d9c2-11e7-9bf3-eb1c95d52c64.png)

**Comment by fastfading** [comment]
relate to  #800 #598 
according to 598 ,  maybe we can add function caller highlight first
teide/liteidex/src/plugins/syntaxeditor/golanghighlighter.cpp

61 //function
62 rule.pattern = QRegExp("\b[a-zA-Z_][a-zA-Z0-9_]+\s*(?=()");
63 rule.format = functionFormat;

这里的正则表达式看来只支持
func Abc()
不支持
fmt.Printf()

rule.pattern = QRegExp("(?=\b|.)[a-zA-Z_][a-zA-Z0-9_]+\s*(?=()");
这样是否可行？

**Comment by discoverfly** [comment]
Function 高亮本来就有，只是默认的配色方案没有高亮function.
： Preferences-> LiteEditor -> 字体和颜色 -> 编辑器颜色方案 -> gist-github.xml
就看得到function高亮了。

 另外，你找错地方了。 应该是 liteidex/src/plugins/liteeditor/highlightermanager.cpp 文件。
 我看的情况是 syntaxeditor好像并没有被enable.

**Comment by fastfading** [comment]
Preferences-> LiteEditor -> 字体和颜色 -> 编辑器颜色方案 -> gist-github.xml
也不行
看我的图说明，   func 后面的 ProcessIdx function  是高亮的
我说的是  ioutil.ReadFile 中的 Readfile function 没高亮

**Comment by discoverfly** [comment]
那你可以自己弄一个配色方案啊。
https://github.com/visualfc/liteide/blob/master/liteidex/deploy/liteeditor/color/gist-github.xml#L25:37

把Function 的foreground 改成和 FuncDecl  的foreground 一样。

**Comment by discoverfly** [comment]
我试试了，
make(), x.len() 这些函数可以。
fmt.Printf() 好像不行。

**Comment by fastfading** [comment]
make   len   are keywords , not function

2018-01-24 13:57 GMT+08:00 JianliuHu <notifications@github.com>:
