### ISSUE TITLE
突然变得很卡

### ISSUE THREAD

**Issue by sekone1** [visualfc/liteide#881]
版本： liteide x33.windows-qt5 
不知道为什么输入的时候 突然变得卡了 重启电脑也没用
把插件 GolangCode 的勾去掉  重启 liteide 就不卡了   
一勾起来 就又卡了

试了 前几个版本也一样  不知道是什么问题？

**Comment by visualfc** [comment]
liteide --reset-setting 重置设置看一下

**Comment by vizee** [comment]
@visualfc 估计是 gotool/gocode 和 go 编译器器版本差异的问题，能否直接在菜单中增加更新 liteide gotool/gocode 的快捷命令。
类似可以通过设置 GOBIN 指定 go install 的目标目录为 liteide/bin，然后 go get -u gocode/gotool。

**Comment by sekone1** [comment]
@visualfc  还是一样的 没效果    输入 或者 退格 都很卡

**Comment by visualfc** [comment]
建议下载最新的 liteide x33.1 试一下。
另外也可以重新安装gocode。
go get -u github.com/nsf/gocode
将编译好的 gocode 放到 liteide/bin 目录中

**Comment by golwei** [comment]
重装gocode也解决了卡顿.
