### ISSUE TITLE
Windows 64-bit

### ISSUE THREAD

**Issue by svnpenn** [visualfc/liteide#883]
Please add Windows 64-bit release - thank you

**Comment by svnpenn** [comment]
https://github.com/malensek/3RVX/issues/73

**Comment by svnpenn** [comment]
https://github.com/frostwire/frostwire/issues/199

**Comment by svnpenn** [comment]
https://github.com/hadouken/hadouken/issues/228

**Comment by svnpenn** [comment]
https://github.com/irzyxa/Volume2/issues/3

**Comment by visualfc** [comment]
I'm installed windows-xp and build liteide on virtual box in my macbook air(2015) and no enoth  space and resource to install win7 or highter.

**Comment by cup** [comment]
https://github.com/psemiletov/tea-qt/issues/29

**Comment by RavHilton** [comment]
Please add an x64 build of this.  I've been using EarTrumpet (which I quite like) but am looking for an x64 alternative, especially an Open Source one as I'm trying, since it is **2021** to eliminate all x86 code from my systems.
