### ISSUE TITLE
调试部分功能错误

### ISSUE THREAD

**Issue by cuizx** [visualfc/liteide#887]
LiteIDE version : 33.1

Go version: 1.9.2 与go版本无关。 降级到LiteIDE 33 可以使用

当调试时， 变量、监视 （同步记录、变量、监视、调用堆栈那个面板）不起作用，不论用GDB还是Dlv
其他lite版本是能用的。

你忘了把这一块编译了吧？

**Comment by visualfc** [comment]
system and liteide qt version

**Comment by cuizx** [comment]
System: Windows Server 2012 R2 
LiteIDE : amd64-33.1-qt5

**Comment by visualfc** [comment]
please download x35.1 and check.
