### ISSUE TITLE
gdb and debugging broken on OS x

### ISSUE THREAD

**Issue by securityicon** [visualfc/liteide#890]
Hi!

Hope someone can help me through this. Appreciate that this might be related to gdb on os x rather than liteide but here goes:

Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X33.1

### What version of Go are you using (`go version`)?
go version go1.9.2 darwin/amd64

### What operating system and processor architecture are you using(`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/gerthorne/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pq/kqdxx_wj72dgysm09568ss8r0000gn/T/go-build588177723=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?

If possible, provide a recipe for reproducing the error.
Basic Mac OS X High Sierra install. 
Installed gbd with brew.

Fired up LiteIDE and created an emty hello world project. 
Compiles and runs fine.

When trying to "Start Debugging" I get an error message:
error,msg="Unable to find Mach task port for process-id 77065: (os/kern) failure (0x5).\n (please check gdb is codesigned - see taskgated(8))"

I can see from the output that gdb is executing and I have code signed gdb however it keeps produceing the above error.

GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin17.0.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".

### What did you expect to see?
Some debugging at least.

### What did you see instead?
error,msg="Unable to find Mach task port for process-id 77065: (os/kern) failure (0x5).\n (please check gdb is codesigned - see taskgated(8))"

Any ideas or help is greatly appreciated.

Cheers,
G

**Comment by visualfc** [comment]
please install Delve and liteide select debugger/delve to debug
https://github.com/derekparker/delve
