### ISSUE TITLE
Release size

### ISSUE THREAD

**Issue by svnpenn** [visualfc/liteide#891]
the release size could be dramatically reduced. as an extreme example,
Exhibit A - those files can be removed and LiteIde will still open. right off
the top that takes the zip size from 24 MB to 9 MB.

further, you can use a command like this:

~~~
find | grep -i -e exe -e dll | xargs -L1 -P5 upx --brute
~~~

to the remaining EXE and DLL and it gets you down to 7 MB after zipping - see
Exhibit B.

## Exhibit A

~~~
bin/diff.exe
bin/gdb.exe
bin/gdb64.exe
bin/gocode.exe
bin/gomodifytags.exe
bin/gotools.exe
bin/iconengines/*
bin/imageformats/*
bin/liteide_ctrlc_stub.exe
bin/liteshell.dll
bin/mingwm10.dll
bin/msys-1.0.dll
bin/printsupport/*
bin/Qt5Svg.dll
bin/translations/*
CONTRIBUTORS
LGPL_EXCEPTION.TXT
lib/liteide/plugins/bookmarks.dll
lib/liteide/plugins/dlvdebugger.dll
lib/liteide/plugins/fakevimedit.dll
lib/liteide/plugins/filebrowser.dll
lib/liteide/plugins/gdbdebugger.dll
lib/liteide/plugins/golangast.dll
lib/liteide/plugins/golangcode.dll
lib/liteide/plugins/golangdoc.dll
lib/liteide/plugins/golangedit.dll
lib/liteide/plugins/golangfmt.dll
lib/liteide/plugins/golangpackage.dll
lib/liteide/plugins/golangplay.dll
lib/liteide/plugins/golangpresent.dll
lib/liteide/plugins/jsonedit.dll
lib/liteide/plugins/litebuild.dll
lib/liteide/plugins/litedebug.dll
lib/liteide/plugins/liteenv.dll
lib/liteide/plugins/litefind.dll
lib/liteide/plugins/litetty.dll
lib/liteide/plugins/markdown.dll
lib/liteide/plugins/quickopen.dll
lib/liteide/plugins/rustedit.dll
lib/liteide/plugins/webkithtmlwidget.dll
lib/liteide/plugins/welcome.dll
LICENSE.LGPL
README.md
share/liteide/liteapp/*
share/liteide/litebuild/*
share/liteide/liteenv/*
share/liteide/packages/*
share/liteide/qt.conf
share/liteide/translations/*
share/liteide/welcome/*
~~~

## Exhibit B

~~~
        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
    119822 ->     47630   39.75%    win32/pe     bin/libgcc_s_dw2-1.dll
   1026062 ->    412174   40.17%    win32/pe     bin/libstdc++-6.dll
     49152 ->     26112   53.13%    win32/pe     bin/libwinpthread-1.dll
   1310208 ->    467456   35.68%    win32/pe     bin/liteapp.dll
    120832 ->    113152   93.64%    win32/pe     bin/liteide.exe
   1489408 ->    513024   34.44%    win32/pe     bin/platforms/qwindows.dll
   5393408 ->   2061312   38.22%    win32/pe     bin/Qt5Core.dll
   5676544 ->   1896960   33.42%    win32/pe     bin/Qt5Gui.dll
    357888 ->    141312   39.48%    win32/pe     bin/Qt5PrintSupport.dll
   6537216 ->   2371584   36.28%    win32/pe     bin/Qt5Widgets.dll
    226304 ->     88576   39.14%    win32/pe     bin/Qt5Xml.dll
   1211904 ->    360960   29.78%    win32/pe     lib/liteide/plugins/liteeditor.dll
   --------------------   ------   -----------   -----------
  23518748 ->   8500252   36.14%                 [ 12 files ]
~~~

**Comment by svnpenn** [comment]
https://github.com/atom/atom/issues/5012

**Comment by svnpenn** [comment]
https://github.com/adobe/brackets/issues/14071

**Comment by svnpenn** [comment]
https://github.com/Komodo/KomodoEdit/issues/3438

**Comment by mpictor** [comment]
@svnpenn 
>... files can be removed and LiteIde will still open

I can drain the oil out of my car, and it'll still start and drive for a bit. Should I?

While I can't speak for any of the people actually contributing to LiteIDE (I've yet to do so myself), if you want to be taken seriously, then put more effort in.

We're in an age where I can buy a laptop with 1.5TB of ssd, or get a 1Gb internet connection. Sure, there are far cheaper options, but one need not be a millionaire to purchase them. At the other end of the spectrum, a raspberry pi with keyboard, mouse, display, etc can be had for $100 (probably $50) if you look around a bit) and will have no trouble with that 24MB zip either.

Sure, _bloat_ is bad, but if you think the files listed are bloat, you clearly don't understand the purpose of any of them - or the functionality LiteIDE provides.

**Comment by svnpenn** [comment]
@mpictor your comment is a bunch of fluff. granted my presentation is not perfect - the "extraneous" files i have presented might have some good and valid reason to remain - and i am open to discussing that

but you have provided nothing - no germane examples - no hard data - not a single point of first hand experience why my suggestion would be a bad idea

giving some random metaphors does not a good argument make - i will give your comment the respect it deserves - none.

**Comment by visualfc** [comment]
thanks, but keep the dynamic library original build to best.
