### ISSUE TITLE
Feature Request: Allow vertical scrolling beyond the last line

### ISSUE THREAD

**Issue by scorredoira** [visualfc/liteide#895]
Currently, you can only scroll the document so far that the last line of the document is displayed at the bottom of the window. I would be very nice to let you scroll so far that the last line of the document is displayed at the top of the window.

**Comment by vendelin8** [comment]
I think this has been added to liteide 35.3 . But for me, it's really annoying. Could be this optional?

**Comment by scorredoira** [comment]
I see that it's very difficult to please everybody because I can't live
without it :)

>

**Comment by visualfc** [comment]
https://github.com/visualfc/liteide/commit/d7141a82488a7cfbe82950180c5ed3b2a19ef6bf

**Comment by vendelin8** [comment]
I built it on my Arch linux with `makepkg -sri`, About LiteIDE says
Version: X35.4
But the option is not visible under `Add copied text into the clipboard as HTML`.
Can you please check it one more time? Or please let me know if I did something wrong.

**Comment by vendelin8** [comment]
Works fine now. You should close this.

**Comment by vendelin8** [comment]
This is somehow wrong again. I have the setting set to false, and it scrolls after the last line. If I enable it, "OK" settings, come back, set it to false, "OK", then close the file, and reopen, it works. But it returns like this when closing LiteIDE and open it again.
