### ISSUE TITLE
gofmt plugin add gofmt option args

### ISSUE THREAD

**Issue by visualfc** [visualfc/liteide#90]
When I save the go file, it will run gofmt automatically. But I want
gofmt with tabs=false, there is no gofmt options for this, so I hope you
could add the input entry for othe gofmt args so people could gofmt with
their option.

**Comment by mbenkmann** [comment]
If you are still interested in this issue, you may want to look at https://github.com/mbenkmann/goformat. It's a gofmt fork that (among other formatting options) brings back the option to use spaces instead of tabs.
