### ISSUE TITLE
Double click the left directory will collapse

### ISSUE THREAD

**Issue by wzshiming** [visualfc/liteide#901]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
33.1 qt5

### What version of Go are you using (`go version`)?
1.9

### What operating system and processor architecture are you using(`go env`)?
mac inter x86_64

### What did you do?
Double click on the left directory

### What did you expect to see?
Expand the directory

### What did you see instead?
Exit

**Comment by visualfc** [comment]
please download latest version x33.2 and test
