### ISSUE TITLE
关联函数跳转慢

### ISSUE THREAD

**Issue by liuhuanqiang** [visualfc/liteide#902]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X32.1

### What version of Go are you using (`go version`)?
version go1.9.2 

### What operating system and processor architecture are you using(`go env`)?
darwin/amd64

### What did you do?

If possible, provide a recipe for reproducing the error.
点关联函数时，跳转非常慢

**Comment by visualfc** [comment]
1. Update liteide to latest version x33.1 to support go1.9
2. Update liteide tools for support new Golang Version
go get -u github.com/visualfc/gotools
go get -u github.com/nsf/gocode

Windows/Linux: copy GOPATH/bin gotools and gocode to liteide/bin
MacOS: copy GOPATH/bin gotools and gocode to LiteIDE.app/Contents/MacOS
