### ISSUE TITLE
crashed when the replace all button clicked

### ISSUE THREAD

**Issue by runsys** [visualfc/liteide#904]
find text:
math.Min(float64(btn.percentwidth), float64(btn.maxpercentwidth)), btn.float, math.Min(float64(btn.percentheight), float64(btn.maxpercentheight))
replace with:
math.Min(percentv(btn.percentwidth), percentv(btn.maxpercentwidth)), btn.float, math.Min(percentv(btn.percentheight), percentv(btn.maxpercentheight))

what's wrong with this replace?

all most lost all of my work. please be careful.

**Comment by visualfc** [comment]
liteide version?

**Comment by visualfc** [comment]
latest version liteide x33.1 
fix find editor replace all wrap around

git version 
litefind: fix editor regexp replace
https://github.com/visualfc/liteide/commit/d4f8b4e9916687c159613c969eaf698e5f187106

**Comment by runsys** [comment]
Few day ago, I use the lastest version 33. have this problem. Now, new version have not the problem. thanks!
