### ISSUE TITLE
custom TARGETBASENAME fails BuildandRun and Run

### ISSUE THREAD

**Issue by TudorHulban** [visualfc/liteide#908]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
x33.1
qt4.8.1

### What version of Go are you using (`go version`)?
go1.9.3 linux/amd64

### What operating system and processor architecture are you using(`go env`)?
GOOS="linux"
GOARCH="amd64"

### What did you do?
update TARGETBASENAME  in BuildConfiguration/Custom to string value (ex. 'xxx')

If possible, provide a recipe for reproducing the error.

### What did you expect to see?
expected build and run to succeed but it failed.

### What did you see instead?
when pressing Ctrl + R the compilation fails to run. 
my expectation is that even if i change target base name the ctrl + R to run the compilation.

thank you

**Comment by visualfc** [comment]
please custom BUILDFLAGS to -o $(TARGETNAME)

**Comment by TudorHulban** [comment]
thank you!
it worked.

it would be nice to have BUILDFLAGS populated automatically for this kind of case.

**Comment by master8282** [comment]
After 3 years, nobody hasn't populated BUILDFLAGS to -o $(TARGETNAME) yet and I spent an hour until found this issue.
