### ISSUE TITLE
Feature Request: Support for remote gdb debugging

### ISSUE THREAD

**Issue by aletheia7** [visualfc/liteide#91]
1. Is is possible to run the Windows Liteide and debug a Linux go process on another machine using gdb?
2. Is is possible to run the Linux Liteide and debug a Linux go process on another machine using gdb?

Could you please add these features? gdb can support remote debugging: http://sourceware.org/gdb/current/onlinedocs/gdb/Remote-Debugging.html#Remote-Debugging

**Comment by chennqqi** [comment]
+1

**Comment by senluowx** [comment]
+1
