### ISSUE TITLE
x33.2 windows no qt5 version in releases

### ISSUE THREAD

**Issue by xgdgsc** [visualfc/liteide#912]
In release version x33.2, there is no qt5 version for windows, any reason?

**Comment by visualfc** [comment]
Sorry, I'm lost job and now only have mac book air 2015.
The liteide-macOS version build on my air. 
The liteide-linux version build on VirtualBox Ubuntu 16.04 64bit and  VirtualBox Ubuntu 16.04 32bit.
The liteide-windows version build on VirtualBox XP-SP3 Qt4 version, no enough space and resource install Win7 and Qt5.

**Comment by xgdgsc** [comment]
Which version of qt does it support? I tried to build with qt5.9 msvc and there are some error.

**Comment by visualfc** [comment]
What is wrong?
liteide build test macOS qt5.6.3

**Comment by visualfc** [comment]
any build  error please report new issues
