### ISSUE TITLE
 Variable QMAKE_CXX.COMPILER_MACROS is not defined error when running build_windows_msvc.cmd

### ISSUE THREAD

**Issue by xgdgsc** [visualfc/liteide#913]
### What did you do?

follow the instructions at http://liteide.org/cn/doc/install/  on Windows with qt5.9 at step of running  `build_windows_msvc.cmd` . It shows error.

### What did you expect to see?

build fine.

### What did you see instead?

```
D:\Documents\Apps\code\liteide\build>build_windows_msvc.cmd
build liteide
QTDIR=D:\Qt\5.9\msvc2017_64
GOROOT=C:\Go\
BUILD_ROOT=D:\Documents\Apps\code\liteide\build
LITEIDE_ROOT=D:\Documents\Apps\code\liteide\build\..\liteidex
.
qmake liteide ...
.
D:/Qt/5.9/msvc2017_64/mkspecs/features/toolchain.prf:129: Variable QMAKE_CXX.COMPILER_MACROS is not defined.
Project ERROR: msvc-version.conf loaded but QMAKE_MSC_VER isn't set
error, qmake fail
```

From my search it seems to be [[QTBUG-60059] "QMAKE_CXX.COMPILER_MACROS is not defined" with -tp vc - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-60059) .  Running `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64 ` before `build_windows_msvc.cmd` would work.

**Comment by xgdgsc** [comment]
[liteidex33.2.windows-qt5.zip](https://github.com/visualfc/liteide/files/1777588/liteidex33.2.windows-qt5.zip)
After that and the issue https://github.com/visualfc/liteide/issues/886 , it builds fine. I uploaded the file in case you want to publish it to releases.

**Comment by xgdgsc** [comment]
https://pan.baidu.com/s/1eTxcfAi is the build compiled with latest qt5.10.1.

**Comment by visualfc** [comment]
Thanks, i'm test qt5 install version for window xp,  the qt5.6.2 install windows xp success.
So i'm build liteide for qt5.6.2 on windows and publish, thanks.

**Comment by visualfc** [comment]
WindowXP 能安装的 Qt5 官方安装版本测试最高就到 Qt5.6.2 了。
