### ISSUE TITLE
官方包无法每次都出现自动完成提示

### ISSUE THREAD

**Issue by Oguangpan** [visualfc/liteide#915]
## LiteIde版本
linux64 QT4 arch 源中的最新版本

## go版本:
go 1.10

## 系统: 
arch linux - gnome

## 期待
编写代码中出现完整代码提示。

## 问题
go内置库的所有包代码都无法出现代码提示。   
但是非官方的包通过 import 导入都能看到完整有效的代码提示.

该问题只在archlinux系统下通过pacman安装的版本中出现, windows10环境下正常, lubuntu16.10系统下载最新的安装包正常.

**Comment by visualfc** [comment]
archlinux 源安装版本有问题，可以下载 liteide 提供 liteidex33.2.archlinux-pkgbuild 自行编译。
下载 liteidex33.2.archlinux-pkgbuild 并解压，运行下列命令自选编译即可。
$ makepkg -sri 

https://github.com/visualfc/liteide/releases/download/x33.2/liteidex33.2.archlinux-pkgbuild.zip

**Comment by Oguangpan** [comment]
好的,非常感谢您的帮助和解答.
