### ISSUE TITLE
搜索字符串最后一个字母自动变成小写，导致搜索失败

### ISSUE THREAD

**Issue by widon1104** [visualfc/liteide#916]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
x33.1

### What version of Go are you using (`go version`)?
go1.9

### What operating system and processor architecture are you using(`go env`)?
ubuntu17.10

### What did you do?

If possible, provide a recipe for reproducing the error.
搜索时候我勾选了区分大小写
搜索内容：InvokeSC，最后一个字母大写C，会自动变成小写c，导致搜索失败

### What did you expect to see?
大写C不变成小写c

### What did you see instead?
大写C变成了小写c

**Comment by visualfc** [comment]
不太理解你说的问题，可以先下载和测试 x33.2 能否解决你的问题。

**Comment by widon1104** [comment]
liteide33.2已经没有这个问题了

但是liteide33.2，我显示文件系统，每次都要点击“重新读取目录”键才能把文件目录显示出来。。
