### ISSUE TITLE
liteide treat "AltGr" as "CTRL + ALT"

### ISSUE THREAD

**Issue by ernest33** [visualfc/liteide#923]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X33.2

### What version of Go are you using (`go version`)?
1.10

### What operating system and processor architecture are you using(`go env`)?
Windows 10 (Intel i5)

### What did you do?
I'm using French keyboard layout ^^
Want to insert "{" using "AltGr" + "4" but all i got is show/hide of "Go Outline" panel which have a shorcut "CTRL" + "ALT" + "4"
If possible, provide a recipe for reproducing the error.
Set keyboard layout to "french".
Open liteide
In the editor use "AltGr" + "4" and the "Go Outline" panel show/hide

### What did you expect to see?
A "{" <= opening curly brace

### What did you see instead?
"Go Outline" panel show/hide

### Temporary solution
In Options ==> LiteApp ==> "Keyboard" tab : Remove shortcut definition of "ToolWindow_GoOutline"...or change it ^^
One more temporary solution : Options ==> LiteApp ==> Generic ==> "Interface [*]"...uncheck "Use tool window shortcuts"

**Comment by visualfc** [comment]
options -> liteapp -> uncheck "Use tool window shortcuts"

**Comment by ernest33** [comment]
Thanks but i've already said that in my message ;-)
It should be good to allow liteide to make the difference between ALT+GR and CTRL+ALT. That's will let people with keyboard layout different than US/UK use both shortcuts To show/hide "Go Outline" and just type an opening curly brace ;-)
As it's an open source program i'll take a look. It seems that's a problem under Windows.

**Comment by visualfc** [comment]
change atl+number to ctrl+number
https://github.com/visualfc/liteide/commit/33e547ffda04fff215eb438e877473e97f7df677

**Comment by visualfc** [comment]
please download x35.1 and check.

**Comment by nieware** [comment]
Unfortunately this doesn't seem to be fixed in v35.1 - this is pretty annoying with a German keyboard, because with default keymappings you are unable to type an opening curly brace (AltGr + 7) in LiteIDE.

**Comment by AMArostegui** [comment]
Same here.

LiteIDE x36, Windows 10, x64, spanish keyboard layout

**Comment by QuickOrBeDead** [comment]
Uncheck Bookmarks plugin and restart the ide. Then it works.

**Comment by ernest33** [comment]
Hi,
Maybe i'm a bit late, but i can confirm that in version X38.1, the problem doesn't exist anymore 😄 👍🏻 .
I close this issue.
Thank you 💯
