### ISSUE TITLE
deepin下启动报错error while loading shared libraries: libicui18n.so.55

### ISSUE THREAD

**Issue by FearS98** [visualfc/liteide#924]
### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
下的编译好的 liteidex33.2.linux64-qt5

### What version of Go are you using (`go version`)?
go-1.10

### What operating system and processor architecture are you using(`go env`)?
deepin 15.5

### What did you do?
终端运行/liteide/bin/liteide

### What did you see instead?
报错 /liteide/bin/liteide: error while loading shared libraries: libicui18n.so.55: cannot open shared object file: No such file or directory

**Comment by visualfc** [comment]
我重新打包上传了 liteide x33.2 for linux

liteidex33.2.linux64-qt5.5.tar.gz              内置打包了Qt5.5.1运行库
liteidex33.2.linux64-qt5.5-system.tar.gz 如果系统包含 Qt5.5.1 则可以下载这个.
liteidex33.2.linux32-qt5.5.tar.gz
liteidex33.2.linux32-qt5.5-system.tar.gz

**Comment by FearS98** [comment]
报错
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
已放弃

我尝试sudo apt-get install xcb 居然能安装，不过装完了还是报错。估计不是一个东西=。
或许我应该下qt库？

**Comment by visualfc** [comment]
我是在 ubuntu-16.04 下编译的，使用 apt-get 安装的 Qt5
sudo apt-get install qt5-default

**Comment by visualfc** [comment]
如果自行编译 LiteIDE 参考 http://liteide.org/cn/doc/install/

**Comment by FearS98** [comment]
好的，编译完成可以正常运行。
不过……整体UI变的特别大QAQ
![image](https://user-images.githubusercontent.com/28773175/37503423-48cd542e-2913-11e8-919a-9fad50a4f869.png)
但是深度商店的33.1是正常的。

**Comment by visualfc** [comment]
我上传了一个 x33.2的 AppImage 版本，可以试试。

**Comment by FearS98** [comment]
好的~感谢。
