### ISSUE TITLE
liteide debug wait timeout

### ISSUE THREAD

**Issue by saka2god** [visualfc/liteide#930]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
33.2

### What version of Go are you using (`go version`)?
1.9.4

### What operating system and processor architecture are you using(`go env`)?
windows10

### What did you do?
debug a app with C code

If possible, provide a recipe for reproducing the error.
debug a app with C code

### What did you expect to see?
debug started

### What did you see instead?
timeout

I see the code,liteide-x33.2/liteidex/src/plugins/litedebug/litedebug.cpp:518
args << "build" << "-a" << "-gcflags" << "\"-N -l\"" ;
the -a flag means:build all
when my code contains C codes,the build time longer than 30s
and litedebug wait timeout.

Can you modify the litedebug code to make the flag & wait time can be set by user.

**Comment by visualfc** [comment]
fixed, https://github.com/visualfc/liteide/commit/178890a65f34f6a81056eabf4bf0aeb5e1419831
