### ISSUE TITLE
新版的mac pro上面，运行一段时间后拉动目录反应很慢

### ISSUE THREAD

**Issue by elvin-du** [visualfc/liteide#932]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
33.2

### What version of Go are you using (`go version`)?
golang 1.10

### What did you do?

If possible, provide a recipe for reproducing the error.

**Comment by visualfc** [comment]
这是使用 Qt5.6.3 在 macOS 上编译的原因，使用 Qt5.9 编译可以解决问题，但因为 Qt5.9 本身的 QTabBar 显示存在问题，所以 x33.2 仍使用 Qt5.6.3 编译。
在最新的源码中我已通过修改样式表 hack 的方式来解决 Qt5.9 中 TabBar 的问题，所以现在可以使用 Qt5.9 编译，确保在 macOS 上可以正常使用。

**Comment by elvin-du** [comment]
非常感谢，下载了最新版本就好了。
