### ISSUE TITLE
xcb problem

### ISSUE THREAD

**Issue by Fruchtgummi** [visualfc/liteide#933]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
liteidex33.2-linux-x86_64.AppImage 

### What version of Go are you using (`go version`)?
1.10.1

### What operating system and processor architecture are you using(`go env`)?
Arch 64

### What did you do?
click open

### What did you expect to see?
 Is running

### What did you see instead?

> This application failed to start because it could not find or load the Qt platform plugin "xcb".
> 
> Available platform plugins are: xcb.
>

**Comment by visualfc** [comment]
arch please download https://github.com/visualfc/liteide/releases/download/x33.3/liteidex33.3.archlinux-pkgbuild.zip
