### ISSUE TITLE
Ctrl 键跳转代码经常不能使用

### ISSUE THREAD

**Issue by hzmnet** [visualfc/liteide#938]
Ctrl 键跳转代码经常不能使用

最新版本

**Comment by zskylark** [comment]
不是不能用，而是效率太低。按了ctrl后会起一个gotools进程在后台查找跳转位置。由于没有像其他大型IDE预先对代码和依赖建立索引，所以你会发现gotools都会占用很多CPU和时间，以至于假死。

**Comment by hzmnet** [comment]
同意确实是这样 需要等很久很久

**Comment by zskylark** [comment]
33.3这个版本好很多，可以试试，后面的版本包括最新的，都慢得一逼。

**Comment by visualfc** [comment]
please download x35.1 and check.

**Comment by piconew** [comment]
35.2 也慢啊
