### ISSUE TITLE
Feature Request: option to toggle Show / Hide whitespaces in code

### ISSUE THREAD

**Issue by rphlrmblt** [visualfc/liteide#94]
Please, can you add an option to toggle whitspace (tabs, spaces) like Scintilla based editors.

Example :

![go-scite](https://f.cloud.github.com/assets/4006281/968346/cd6276ae-059d-11e3-8f43-8d0ec956135f.png)

I've heard that Qt editor object have this option.

Thanks in advance.

**Comment by visualfc** [comment]
fix it
please download x27 and check.

**Comment by rphlrmblt** [comment]
Yes, it works like intended !
Thanks a lot !
