### ISSUE TITLE
rename symbol under cursor (GOPATH)

### ISSUE THREAD

**Issue by tvcl** [visualfc/liteide#944]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
source 33.3 compiled against Qt 5.10.1

### What version of Go are you using (`go version`)?
10.2

### What operating system and processor architecture are you using(`go env`)?
Windows 10 1803 x64

### What did you do?

In edit menu select "rename symbol under cursor (GOPATH)"

If possible, provide a recipe for reproducing the error.

In edit menu select "rename symbol under cursor (GOPATH)"

### What did you expect to see?

Renaming in GOPATH

### What did you see instead?

Renaming in GOPATH and in GOROOT
How to do renaming only in GOPATH?

**Comment by visualfc** [comment]
please download x34.2 and test
