### ISSUE TITLE
Permission denied for runtime/cgo when importing "net/http" package

### ISSUE THREAD

**Issue by tms320** [visualfc/liteide#946]
LiteIDE version: X33.3
Go version: 1.10.2
OS: Raspbian, version April 2018 (my device is Raspberry Pi 3 model B)
Architecture: ARM v7
When I imported "net/http" package I got build error:
go build runtime/cgo: open /usr/local/go/pkg/linux_arm/runtime/cgo.a: permission denied
As far as I understood the problem is related to the Go version 1.10:
https://github.com/golang/go/issues/25138
There is no problem if we use 'go build' without '-i' option. So as a workaround I had to modify the following configuration file:
~/liteide/build/liteide/share/liteide/litebuild/gosrc.xml
I remove '-i' option in the following lines:
`<custom id="BuildArgsi" name="BUILDARGS" value="-i" shared-value="$(BUILDFLAGS)"/>`
`<custom id="ForceBuildArgsi" name="FORCEBUILDARGS" value="-i -a -v" shared-value="$(BUILDFLAGS)"/>`

**Comment by visualfc** [comment]
please build and install std on terminal, example
$ sudo GOOS=linux GOARCH=arm go install std

**Comment by tms320** [comment]
I did:
sudo GOOS=linux GOARCH=arm GOARM=7 go install std
Now I get a lot of errors:
go build internal/race: open /usr/local/go/pkg/linux_arm/internal/race.a: permission denied
go build errors: open /usr/local/go/pkg/linux_arm/errors.a: permission denied
go build runtime/internal/sys: open /usr/local/go/pkg/linux_arm/runtime/internal/sys.a: permission denied
go build sync/atomic: open /usr/local/go/pkg/linux_arm/sync/atomic.a: permission denied
go build unicode/utf8: open /usr/local/go/pkg/linux_arm/unicode/utf8.a: permission denied
go build encoding: open /usr/local/go/pkg/linux_arm/encoding.a: permission denied
go build unicode/utf16: open /usr/local/go/pkg/linux_arm/unicode/utf16.a: permission denied
go build math/bits: open /usr/local/go/pkg/linux_arm/math/bits.a: permission denied
go build crypto/subtle: open /usr/local/go/pkg/linux_arm/crypto/subtle.a: permission denied
go build crypto/internal/cipherhw: open /usr/local/go/pkg/linux_arm/crypto/internal/cipherhw.a: permission denied
go build container/list: open /usr/local/go/pkg/linux_arm/container/list.a: permission denied
go build vendor/golang_org/x/crypto/cryptobyte/asn1: open /usr/local/go/pkg/linux_arm/vendor/golang_org/x/crypto/cryptobyte/asn1.a: permission denied
go build internal/nettrace: open /usr/local/go/pkg/linux_arm/internal/nettrace.a: permission denied
go build runtime/cgo: open /usr/local/go/pkg/linux_arm/runtime/cgo.a: permission denied
go build math: open /usr/local/go/pkg/linux_arm/math.a: permission denied
go build unicode: open /usr/local/go/pkg/linux_arm/unicode.a: permission denied

**Comment by tms320** [comment]
Sorry, it was my fault. For Raspberry Pi I should use GOARM=6 (not 7). Now everything works fine. Thanks.
