### ISSUE TITLE
I don't know how to open the actual IDE on my windows desktop

### ISSUE THREAD

**Issue by Fern135** [visualfc/liteide#947]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
I don't know

### What version of Go are you using (`go version`)?
the most latest ones

### What operating system and processor architecture are you using(`go env`)?
Windows 10

### What did you do?

If possible, provide a recipe for reproducing the error.
I simply tried to open the IDE but it did not let me open it or install it in any way shape or form.

**Comment by xiegeo** [comment]
Follow this link https://github.com/visualfc/liteide/releases/latest and download the windows version, which is liteidex33.3.windows-qt5.6.3.zip right now.

Unzip it to any directory, then go into the bin directory and find liteide.exe. That is the program you want to run. You can also create a desktop short cut to it for faster access.
