### ISSUE TITLE
Autocompletion is not working

### ISSUE THREAD

**Issue by abhishekbarua** [visualfc/liteide#952]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X33.3

### What version of Go are you using (`go version`)?
1.10.3

### What operating system and processor architecture are you using(`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gmat/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gmat/Workspace/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build812797537=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
Simple hello world program.
Presseing f inisde main() gives popup for fmt.
Then I press . (dot)
Then when I press P, no popup
Then when I press r, no popup
Then when I press i, no popup
Then when I press n, no popup

### What did you expect to see?
After "fmt." when I press P, it should open popup.

### What did you see instead?
Nothing. Autocompletion does not work. I need to type by hand.

**Comment by visualfc** [comment]
please download x33.4 and test. change gocode to 
https://github.com/mdempsky/gocode

**Comment by AnimusPEXUS** [comment]
have same here with both x33.3 and x33.4. I've already installed mdempsky/gocode, but looks like liteide uses it's own gocode and avoiding using mdempsky/gocode

**Comment by AnimusPEXUS** [comment]
I've killed gocode and started it manually in debug mode.. looks like it bails out with parsing error in place where it should provide completion.

**Comment by AnimusPEXUS** [comment]
created issue https://github.com/mdempsky/gocode/issues/37 with -debug dump

**Comment by AnimusPEXUS** [comment]
sorry, I've had a different problem..

**Comment by lrita** [comment]
Hi @visualfc,

the autocompletion doesn't work with builtin type, such as `error`. This may be cause by `gocode`. x33.4 in macOS.

**Comment by hzmnet** [comment]
it is work but showing very very very slow.

**Comment by rsarov** [comment]
x33.4 for windows all work fine, but x34 not

**Comment by visualfc** [comment]
please update to liteide x34.1

**Comment by lrita** [comment]
I am using x34.1 a few days, it works fine. But the autocompletion does not work today suddenly.

@visualfc

**Comment by DennisMao** [comment]
the autocompletion is not work on the "testing" package.
I have tried `go install` at the path `$GOROOT/src/testing`,it does not work
@visualfc

**Comment by lrita** [comment]
@visualfc 

There is a odd problem. When I launch `LiteIDE.app/Contents/MacOS/gocode -s -sock unix -addr 127.0.0.1:37373` manually before that I launch `LiteIDE`, the `Autocompletion` works fine.

When I launch `LiteIDE` and `LiteIDE` launch `LiteIDE.app/Contents/MacOS/gocode -s -sock unix -addr 127.0.0.1:37373` secondly, the `Autocompletion` does not work.

@DennisMao you can have a try.

**Comment by DennisMao** [comment]
@lrita  Thanks ,

**Comment by visualfc** [comment]
please download x35.1 and check.

**Comment by AnimusPEXUS** [comment]
no autocompletion problems on My side.

**Comment by visualfc** [comment]
@mpetrs PKG 
Are you mean automatic import prompt ?
please check liteide options-GolangCode : PKG automatic import hints for all packages (GOPATH)

**Comment by mpetrs** [comment]
Yeah, that's what I mean. Automatic import for all packages is activated.

**Comment by asaqib27** [comment]
Hey, I set everything as suggested, GOPATH, GOROOT, and also checked liteide options-GolangCode : PKG automatic import hints for all packages (GOPATH) but still automatic import prompt is not working.
