### ISSUE TITLE
新建文件向导会导致gnome-shell卡死

### ISSUE THREAD

**Issue by rocket049** [visualfc/liteide#957]
无论是自带QT的版本还是system版本都有此问题，其中自带QT的版本尤其严重，而且QT4、5两个版本都有此问题。
描述：
新建文件向导点击“浏览”，随机导致gnome-shell卡死，整个gui失去响应，只能到字符界面杀死gnome-shell才能恢复。

**Comment by visualfc** [comment]
Linux 版本？
liteide 的发行版是在 ubuntu16.04 (x64) and ubutntu 16.04 (i386)下编译的。

**Comment by rocket049** [comment]
我的是ubuntu18.04，桌面是gnome-shell。发生时机一般都是点击“浏览”按钮后。

**Comment by visualfc** [comment]
在虚拟机中安装 ubuntu 18.04 默认桌面测试 下载 LiteIDE Qt4.8.7 和 Qt5.5.1 版本, 没发现这个问题。
ubuntu 18.04 可以安装 qt5.9.5 。你可以尝试自行编译 liteide 看能否解决遇到的问题。

**Comment by rocket049** [comment]
我的是amd64版，不知道你测试的版本是否和我一样？

**Comment by rocket049** [comment]
升级到33.4版后没有遇到过，不过最近我避免使用该功能了，偶尔用到，没有再卡死。
