### ISSUE TITLE
代码主界面菜单文字及对应的功能在哪里

### ISSUE THREAD

**Issue by hakwolf** [visualfc/liteide#964]
我用windows(QT craetor) ＱＴ5.8 用你说的几个步数可以构建成功。但是不知道在哪里看主窗体的菜单项代码在哪里，我ＱＴ也只是入门水平。希望能否有个单要的开发说明，界面项在哪，对应哪些代码及DLL，多谢。

**Comment by visualfc** [comment]
LiteIDE 使用插件方式进行扩展，核心程序为 LiteApp 负责主界面建立和插件管理。

**Comment by hakwolf** [comment]
如果把liteapp部分功能以dll形调用 其它的插件也以dll调用  打造自已的go ide 这样可以不 符合Lgpl只当类库调用  主程序不需要开源.需要注意哪些 避免侵权

**Comment by hakwolf** [comment]
如果把liteapp部分功能以dll形调用 其它的插件也以dll调用  打造自已的go ide 这样可以不 符合Lgpl只当类库调用  主程序不需要开源.需要注意哪些 避免侵权

**Comment by visualfc** [comment]
不知道这样做的意义何在，如果有能力可以为 LiteIDE 开发插件，完善功能。

**Comment by hakwolf** [comment]
web程序启动时运行要加一个参数，请问下你这个加参数运行的功能有吗，在哪里？就是相当于命令行启动带参数的程序需要加参数选项才能启动。

**Comment by visualfc** [comment]
当前项目的编译设置 自定义-TARGETARGS
