### ISSUE TITLE
为什么不支持鼠标侧键Mouse4、Mouse5的前进后退设置？

### ISSUE THREAD

**Issue by xdeng** [visualfc/liteide#967]
为什么不支持鼠标侧键Mouse4、Mouse5的前进后退设置？我手动编辑配置文件都不行，这对阅读代码来说很不方便。
还提个建议， 光标放到函数调用那要等很久才显示出来函数原型，也很不利于阅读要等很久。希望改进啊

**Comment by xdeng** [comment]
这些习惯都是VS的习惯啊。。。

**Comment by visualfc** [comment]
加入了鼠标前进后退导航支持。但我没有这种鼠标测试，无法确认是否有效。
https://github.com/visualfc/liteide/commit/a7b5dd5ff1ab42a9f83fcd7ca6fc8b406fd4c0b9

**Comment by xdeng** [comment]
@visualfc  需要我自己编译测试吗？ 
我还发现了个问题，在按F5启动调试后，第一次响应了，走到断点按F5继续就无效了，要手动点菜单里的调试->继续。

**Comment by visualfc** [comment]
如果有编译条件的话，帮助测试一下。也可以搜索 LiteIDE交流群 328653805 找我测试。

**Comment by visualfc** [comment]
please download liteide x34.2 and test

**Comment by xdeng** [comment]
> please download liteide x34.2 and test

简单测试了下可以了，非常感谢，这对于阅读浏览代码来说非常方便。
