### ISSUE TITLE
请问软件使用的图标放在什么地方，怎么没找到。

### ISSUE THREAD

**Issue by wekay102200** [visualfc/liteide#968]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What did you do?

If possible, provide a recipe for reproducing the error.

**Comment by visualfc** [comment]
liteide 资源目录下 liteapp/qrc 目录下, default 是默认图标， gray 为灰度图标。
在 选项 - LiteApp 中可以切换图标库。
