### ISSUE TITLE
Please support wide and ultra wide screen better

### ISSUE THREAD

**Issue by janso** [visualfc/liteide#973]
### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
34.1

### What version of Go are you using (`go version`)?
go 1.10.3

### What operating system and processor architecture are you using(`go env`)?
Windows 10, AMD64

### What did you do?
I am programming

### What did you expect to see?
It would be great to see the debugger and the "build output" attached to the right border. So I would be able to utilize my screen (3440x1440 px) better. That would even help on a 16:9 screen much!

### What did you see instead?
I see my source code, the debugger and the build output stacked and the complete right side of the screen empty

**Comment by visualfc** [comment]
fixed, sidewindowsstyle support move tool window on leftside/rightside/output
https://github.com/visualfc/liteide/commit/f49298326d7ca0352ae2a6be63e92bf4ab4e6d8b
