### ISSUE TITLE
Kindly provide a BuildModule shortcut after Go 1.11

### ISSUE THREAD

**Issue by silviucm** [visualfc/liteide#975]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X34.1

### What version of Go are you using (`go version`)?
go version go1.11 linux/amd64

### What operating system and processor architecture are you using(`go env`)?
GOARCH="amd64"

### What did you do?
In a module structure with module folder A with subfolders A1, A2, A3, etc, but nothing in the main folder A (except the go.mod file), it would be nice to have a "**BuildModule**" or "**BuildAll**" functionality.

Right now, without any .go file, the Build menu is disabled (greyed out).

Please enable the "Build" menu, if a **go.mod** file is in the editor, and allow a new shortcut, "**BuildModule**" or "**BuildAll**" that will execute:

```
go build ./...
```
(maybe with a shortcut attached)

Thank you for a great tool

**Comment by visualfc** [comment]
please download liteide x34.2 and test

**Comment by silviucm** [comment]
Works as expected. Thank you.
