### ISSUE TITLE
关于GolangFmt选项问题

### ISSUE THREAD

**Issue by tryor** [visualfc/liteide#976]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
x33.4, QT:5.6.3
### What version of Go are you using (`go version`)?
go 1.10.3

### What operating system and processor architecture are you using(`go env`)?
win10,  i7八代

### What did you do?
种田的，码农

If possible, provide a recipe for reproducing the error.
1. 希望在以后的版本里，把：查看-选项-GolangFmt, "允许更新import行，增加缺少的pkg和移除未引用的pkg"，这个选项默认不要勾。我们的gopath下太多项目，许多同名包（自己的或第三方模块，主要是第三方模块），在我的新项目里，很容易自动帮我引入了我不需要的模块，我还不知道，而且还没报错。导致增加了额外时间去找问题。比如log模块，许多三方包里都有这个，方法参数都一样，编译还能正常通过，但这并不是我想要的log模块。

2. 但 移除未使用的 pkg 这个可以保留。
3. 在最新版本的 LiteIDE里，应该是x34及以上吧，自动格式化会失败。我退回x33.4就一切正常。

**Comment by visualfc** [comment]
自动更新 import 行默认是关闭的
