### ISSUE TITLE
Package local "jump to declaration", renames etc. has slowed down

### ISSUE THREAD

**Issue by bep** [visualfc/liteide#986]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?

x34.2

### What version of Go are you using (`go version`)?

go version go1.11 darwin/amd64

### What operating system and processor architecture are you using(`go env`)?

```bash
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bep/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bep/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/bep/dev/go/gohugoio/hugo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n6/s_85mm8d31j6yctssnmn_g1r0000gn/T/go-build613289738=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

In a project outside of GOPATH (built with Go Modules), the "jump to declaration" is now taking the same amount of time for local methods/fields (unexported) that for methods in other packages. 

Note that I have followed the instructions in #977 -- and everything is functionally fine, it's just very slow (10+ seconds). This is also relevant for "find usage" etc.

### What did you expect to see?

I expect almost instant "jump to" for private methods etc., as it was in the "pre Go Modules world".

**Comment by visualfc** [comment]
gotools check mod use `go list -m -json all `, this command parser gohugoio/hugo very slow.

**Comment by bep** [comment]
Yes, Hugo isn't the smallest of the Go projects out there.

Just a quick note about my current workaround for Hugo:

* Move my Hugo project back below `GOPATH`
* run `GO111MODULE=on go mod vendor` to populate the vendor dir

With that LiteIDE is back to its snappy self.

I really appreciate the work you are doing with this product.

**Comment by bep** [comment]
I can confirm that this is now fixed; thank! Really appreciated.

**Comment by visualfc** [comment]
please download x35.1 and check.

**Comment by bep** [comment]
@visualfc x35.1 works great, thanks!
