### ISSUE TITLE
如何设置编译和输出不同目录

### ISSUE THREAD

**Issue by sp0cket** [visualfc/liteide#991]
目录结构如下

```
├server    ----main包目录
┆└main.go
...  ---其他目录
├bin ---输出目录
┆├config.yml ---程序配置文件
┆├debug   ---编译输出文件
...
```

尝试过修改`TARGETBASENAME`无效，通过修改`BUILDFLAGS`添加`-o`参数可以输出到bin但是run的命令执行位置不对，只能通过修改配置文件才能实现这种操作么

**Comment by sp0cket** [comment]
预期是这样的
```
go build -o bin/debug server
cd bin
./debug
```

**Comment by visualfc** [comment]
修改 TARGETBASENAME 为 bin/server ,然后修改BUILDFLAGS 加入 -o $(TARGETNAME)  或者 -o bin/server

**Comment by sp0cket** [comment]
但是这样操作之后的working dir不对，少了一步`cd ./bin`目录，输出的文件会读取程序当前目录下的配置并输出log目录到程序的当前目录。所以run操作应该是两部分切换目录之后运行

**Comment by visualfc** [comment]
我对 gosrc.xml 进行修改 允许自定义 TARGETWORKDIR 
https://github.com/visualfc/liteide/commit/7229b3d25c43dfc3db84143d70d321e87225602b

更新 goxml 重启后，可以修改如下：
```
TARGETBASENAME.    server
TARGETWORKDIR.     $(BUILD_DIR_PATH)/bin
BUILDFLAGS              -o bin/$(TARGETNAME)
```

**Comment by sp0cket** [comment]
抱歉  还是有点问题
go build 执行的命令是` go build -o $(BUILD_DIR_PATH)/bin`
在这个例子中$(BUILD_DIR_PATH)=server/
所以-o 输出目录是在server下面的  而server下面应该只出现源码  bin目录应当在根目录下而不是和源码在一个文件夹下面  我之前提供的例子`go build -o bin/debug server`是相对在project目录下执行的

**Comment by sp0cket** [comment]
在GoLand中是分为三个目录  一个是`Working directory`用作run执行目录`Output directory`是作为-o参数输出目录，`Directory`作为build目录

**Comment by visualfc** [comment]
```
TARGETBASENAME.    server
TARGETWORKDIR.     $(BUILD_DIR_PATH)/../bin or ../bin
BUILDFLAGS              -o ../bin/$(TARGETNAME)
```

**Comment by sp0cket** [comment]
可以了  谢谢👍
