### ISSUE TITLE
Yaml files should indent with spaces by default

### ISSUE THREAD

**Issue by elegos** [visualfc/liteide#992]
### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X34.3 / 4.8.7 (64 bit)

### What version of Go are you using (`go version`)?
1.11.1

### What operating system and processor architecture are you using(`go env`)?
linux amd64

### What did you do?
I write (indented) YAML files.

### What did you expect to see?
Space-indented file

### What did you see instead?
Tab-indented file

The YAML standard forbids the tab character as indentation one. The configuration should take in consideration this and set as indentation character 2-4 spaces, instead of the default tabulation one.

**Comment by visualfc** [comment]
liteide - options - liteeditor - filetypes : setup tab size and tab to space setup.
![2018-10-22 8 32 45](https://user-images.githubusercontent.com/714279/47292559-f6638f80-d639-11e8-80c0-f6c0e3ed65a5.png)

**Comment by elegos** [comment]
I know @visualfc, but the YAML format forbids the tab indentation, it's not a preference. You'd disable "Tab To Space" for `text/yaml` totally and force it (I did the setup, but out of the box the IDE formats the file incorrectly).

**Comment by elegos** [comment]
@visualfc sorry to bother, but I think this is still an issue: YAML standard does NOT allow tabs for indentation, it will fail the parsing.

**Comment by visualfc** [comment]
change editor tabtospace default. 
setup liteapp/mimetype/liteeditor.xml => yaml tabwidth=2
https://github.com/visualfc/liteide/commit/b0b245f2b1521d657e9f17c3901ede3109e4e70b
