### ISSUE TITLE
Debugging error  unable to initialize decompress status for section .zdebug_abbrev

### ISSUE THREAD

**Issue by radiaku** [visualfc/liteide#994]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
x35.1 , qt 5.9.5 (32bit)

### What version of Go are you using (`go version`)?
go version go1.11 windows/386

### What operating system and processor architecture are you using(`go env`)?
windows 10 home. 

set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\Root\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Root\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=sse2
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Root\AppData\Local\Temp\go-build366615870=/tmp/go-build -gno-record-gcc-switches

### What did you do?
Debugging

If possible, provide a recipe for reproducing the error.

### What did you expect to see?
Running program

### What did you see instead?
./gdb.exe --tty=\\.\pipe\liteide-9892-27697 --interpreter=mi --args  C:/Users/Root/Documents/golang/google_imagescraper/google_imagescraper.debug.exe [C:/Users/Root/Documents/golang/google_imagescraper]
BFD: C:\Users\Root\Documents\golang\google_imagescraper\google_imagescraper.debug.exe: unable to initialize decompress status for section .zdebug_abbrev

**Comment by visualfc** [comment]
gdb not support go1.11

delve support go1.11 only GOARCH=amd64
debug menu change to debugger/delve

**Comment by radiaku** [comment]
> gdb not support go1.11
> 
> delve support go1.11 only GOARCH=amd64
> debug menu change to debugger/delve

Worked, but must change to win64.  I think win32 will not supported? old technology hahahah
