### ISSUE TITLE
挺急的：用ide开发不主动提示代码

### ISSUE THREAD

**Issue by chaogo** [visualfc/liteide#998]
首先麻烦大神@visualfc解决问题
**您使用的是什么版本的LiteIDE（LiteIDE关于 - 版本和构建Qt版本**）？
X35.1
**您使用的是什么版本的Go（go version）？**
go1.11
**您使用的是哪种操作系统和处理器架构（go env）？**
ubuntu18.04
**你做了什么？**
gocode 和gotools 也更新了，但是还是不可以提示引用第三方包的代码，但是编译可以通过
包括本地GOPATH写的工具包也不提示代码
第三方代码已经go get 好了

**你期望看到什么？**

能自动提示代码

![20181111121403](https://user-images.githubusercontent.com/39609358/48309018-65823300-e5ab-11e8-93de-db843a017207.png)

**Comment by visualfc** [comment]
please download x35.2 and check.

**Comment by chaogo** [comment]
> 请下载x35.2并检查。
谢谢您的回复，但是还是不可以？是Ubuntu的原因么？

**Comment by visualfc** [comment]
ctrl+` 输入 go env 回车确认, 查看一下在 LiteIDE 中的 go 环境设置。

**Comment by toffstechzhang** [comment]
X35.1，同样的问题，今天升级了macOS后，不主动提示代码了。

X35.2目前不能下载，文件损坏

**Comment by visualfc** [comment]
由于 gocode 的原因， liteide 需要放在无空格的英文目录中。

**Comment by visualfc** [comment]
please download x35.3 and check.
